

UPDATE MAEEDO SET   CAPRCO =  COALESCE((SELECT SUM(CAPRCO1) FROM MAEDDO 
                                    WHERE 
										MAEEDO.IDMAEEDO = MAEDDO.IDMAEEDO AND 
										UDTRPR = 1 AND LILG <> 'IM' ),0) +
						    COALESCE((SELECT SUM(CAPRCO2) FROM MAEDDO 
									WHERE MAEEDO.IDMAEEDO = MAEDDO.IDMAEEDO AND 
									UDTRPR = 2 AND LILG <> 'IM' ),0),
					CAPRAD = COALESCE((SELECT SUM(CAPRAD1) FROM MAEDDO 
									WHERE MAEEDO.IDMAEEDO = MAEDDO.IDMAEEDO AND 
									UDTRPR = 1 AND LILG <> 'IM' ),0) + 
							COALESCE((SELECT SUM(CAPRAD2) FROM MAEDDO 
									WHERE MAEEDO.IDMAEEDO = MAEDDO.IDMAEEDO AND 
									UDTRPR = 2 AND LILG <> 'IM' ),0),
					CAPREX = COALESCE((SELECT SUM(CAPREX1) FROM MAEDDO 
									WHERE MAEEDO.IDMAEEDO = MAEDDO.IDMAEEDO AND 
									UDTRPR = 1 AND LILG <> 'IM' ),0) + 
							COALESCE((SELECT SUM(CAPREX2) FROM MAEDDO 
									WHERE MAEEDO.IDMAEEDO = MAEDDO.IDMAEEDO AND 
									UDTRPR = 2 AND LILG <> 'IM' ),0) WHERE IDMAEEDO=#Idmaeedo#

UPDATE MAEEDO SET ESDO=CASE WHEN ROUND(CAPRCO-CAPRAD-CAPREX,5)=0 THEN 'C' ELSE '' END WHERE IDMAEEDO=#Idmaeedo#


