

-- Cerrrando producto: #Descripcion#
UPDATE MAEDDO SET CAPRAD1=CAPRAD1+#Saldo_1#,CAPRAD2=CAPRAD2+#Saldo_1# WHERE IDMAEDDO=#Idmaeddo#

UPDATE MAEDDO SET ESLIDO=CASE WHEN ROUND(CAPRCO1-CAPRAD1-CAPREX1,5)=0 THEN 'C' ELSE '' END 
	WHERE IDMAEDDO=#Idmaeddo#

	
UPDATE MAEPR SET  STOCNV1C=STOCNV1C-#Saldo_1#,STOCNV2C=STOCNV2C-#Saldo_2# 
	WHERE KOPR = '#Codigo#' 
UPDATE MAEPREM SET  STOCNV1C=STOCNV1C-#Saldo_1#,STOCNV2C=STOCNV2C-#Saldo_2# 
	WHERE EMPRESA = '#Empresa#' AND KOPR = '#Codigo#' 
UPDATE MAEST SET  STOCNV1C=STOCNV1C-#Saldo_1#,STOCNV2C=STOCNV2C-#Saldo_2# 
	WHERE EMPRESA='#Empresa#' AND  KOSU='#Sucursal#' AND  KOBO='#Bodega#' AND  KOPR='#Codigo#' 



	