'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Recursos_Proximas_Recepciones
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BkSpecialPrograms.Recursos_Proximas_Recepciones", GetType(Recursos_Proximas_Recepciones).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Use #Base_BakApp#
        '''
        '''CREATE TABLE [dbo].[#Tabla_Paso_Ppr_VS_Cnd#](
        '''    [Id]								 [int] IDENTITY(1,1) NOT NULL,
        '''    [EMPRESA]                            [Varchar](2)  DEFAULT &apos;&apos;,
        '''    [EMPRESA_INFORME]					 [Varchar](50) DEFAULT &apos;&apos;,
        '''    --[ENDO]								 [Varchar](13) DEFAULT &apos;&apos;,
        '''    --[SUENDO]							 [Varchar](10) DEFAULT &apos;&apos;,
        '''    --[NOKOEN]                             [Varchar](50) DEFAULT &apos;&apos;,
        '''    --[SULIDO]                             [Varchar](3)  DEFAULT &apos;&apos;,
        '''    --[SUCURSAL]                      [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SQLQuery_Informe_Analisis_Pendientes_Recibir_VS_Despacho() As String
            Get
                Return ResourceManager.GetString("SQLQuery_Informe_Analisis_Pendientes_Recibir_VS_Despacho", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 
        '''-- PROXIMAS RECEPCIONES FACTURAS DE COMPRA
        '''-- MERCADERIA PENDIENTE DE DESPACHO.
        '''
        '''Declare
        '''@Empresa Char(2)
        '''--@Fecha_Emision_Desde Date = &apos;#Fecha_Emision_Desde#&apos;,
        '''--@Fecha_Emision_Hasta Date = &apos;#Fecha_Emision_Hasta#&apos;
        '''
        '''Select @Empresa = &apos;#Empresa#&apos;
        '''
        '''SELECT ED.IDMAEEDO,
        '''       DD.IDMAEDDO,
        '''       ED.EMPRESA,
        '''	   ISNULL((SELECT TOP 1 RAZON FROM CONFIGP WHERE EMPRESA = @Empresa),&apos;??&apos;) As EMPRESA_INFORME,	   
        '''	   ED.TIDO,    
        '''	   ED.NUDO,
        '''	   EN.IDMAEEN,
        '''	   ED.ENDO,
        '''	   ED.SUENDO,
        '''	   EN.NOKO [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SQLQuery_Proximas_Recepciones() As String
            Get
                Return ResourceManager.GetString("SQLQuery_Proximas_Recepciones", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 
        '''
        '''Select DISTINCT IDMAEEDO,IDMAEEN,ENDO,SUENDO,NOKOEN,ENDOFI,SUENDOFI,NOENDOFI,TIDO,NUDO,FEEMDO,FEERLI,FEER,
        '''       SUDO,NOKOSU AS SUCURSAL--SULIDO,SUCURSAL,BOSULIDO,BOSULIDO,BODEGA
        '''From #Tabla_Paso#
        '''LEFT JOIN TABSU ON KOSU = SUDO
        '''Where 1 &gt; 0       
        '''#Filtro#   
        '''    
        '''       
        '''Select IDMAEEDO,IDMAEDDO,ENDO,SUENDO,NOKOEN,ENDOFI,SUENDOFI,NOENDOFI,TIDO,NUDO,FEEMDO,FEERLI,FEER,
        '''       SULIDO,SUCURSAL,BOSULIDO,BODEGA,
        '''       TIPR,KOPRCT,NOKOPR,UD0#Ud#PR,
        '''       CAPRCO#Ud#,CAPREX#Ud#,SALDO_Ud#Ud#,
        '''     [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SQLQuery_Sub_Inf_Recep_Desp_Detalle_x_Documentos() As String
            Get
                Return ResourceManager.GetString("SQLQuery_Sub_Inf_Recep_Desp_Detalle_x_Documentos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 
        '''Select DISTINCT IDMAEEN,ENDO,SUENDO,NOKOEN,ENDOFI,SUENDOFI,NOENDOFI
        '''From #Tabla_Paso#
        '''Where 1 &gt; 0
        '''#Filtro#
        '''
        '''Select DISTINCT IDMAEEDO,IDMAEEN,ENDO,SUENDO,NOKOEN,ENDOFI,SUENDOFI,NOENDOFI,TIDO,NUDO,FEEMDO,FEERLI,
        '''       SULIDO,SUCURSAL,BOSULIDO,BOSULIDO,BODEGA
        '''From #Tabla_Paso#
        '''Where 1 &gt; 0       
        '''#Filtro#   
        '''    
        '''       
        '''Select IDMAEEDO,IDMAEDDO,ENDO,SUENDO,NOKOEN,ENDOFI,SUENDOFI,NOENDOFI,TIDO,NUDO,FEEMDO,FEERLI,
        '''       SULIDO,SUCURSAL,BOSULIDO,BODEGA,
        '''       TIPR,KOPRCT,NOKOPR,UD0#Ud#PR,
        '''     [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SQLQuery_Sub_Inf_Recep_Desp_Detalle_x_Entiades() As String
            Get
                Return ResourceManager.GetString("SQLQuery_Sub_Inf_Recep_Desp_Detalle_x_Entiades", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 
        '''Select KOPRCT,NOKOPR,
        '''       --UD0#Ud#PR,
        '''       SUM(CAPRCO#Ud#) As CAPRCO#Ud#,
        '''       SUM(CAPREX#Ud#) As CAPREX#Ud#,
        '''       SUM(SALDO_Ud#Ud#) As SALDO_Ud#Ud#,
        '''       PM_TRANS,
        '''       PM_ACTUAL,
        '''       --TOT_SALDOxPRECIO,
        '''       --TOT_SALDOxPM_TRANS,
        '''       --TOT_SALDOxPM_ACTUAL,
        '''       SUM(STFI#Ud#) As STFI#Ud#,
        '''       FMPR,SUPER_FAMILIA,PFPR,FAMILIA,HFPR,SUB_FAMILIA,MRPR,MARCA,RUPR,RUBRO,CLALIBPR,CLAS_LIBRE
        '''From #Tabla_Paso#
        '''Where 1 &gt; 0
        '''#Filtro#
        '''Group By KOPRCT,NOKOPR,UD0#Ud#PR,PM_TRANS,P [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SQLQuery_Sub_Inf_Recep_Desp_Detalle_x_Producto() As String
            Get
                Return ResourceManager.GetString("SQLQuery_Sub_Inf_Recep_Desp_Detalle_x_Producto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Select SULIDO,SUCURSAL,Sum(SALDO_Ud1) As SALDO_Ud1,Sum(TOT_SALDOxPRECIOREAL) As TOT_SALDOxPRECIOREAL
        '''From BAKAPP_SA.dbo.Tbl_PasoDPM_Ppr
        '''Group By SULIDO,SUCURSAL
        '''Union 
        '''Select &apos;ZZZ&apos;,&apos;TOTAL&apos;,Sum(SALDO_Ud1),Sum(TOT_SALDOxPRECIOREAL)
        '''From BAKAPP_SA.dbo.Tbl_PasoDPM_Ppr.
        '''</summary>
        Friend Shared ReadOnly Property SQLQuery_Sub_Informes_Recep_Desp() As String
            Get
                Return ResourceManager.GetString("SQLQuery_Sub_Informes_Recep_Desp", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
