'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Recursos_Informe_Meson_Familias
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Bk_Produccion.Recursos_Informe_Meson_Familias", GetType(Recursos_Informe_Meson_Familias).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 
        '''
        '''CREATE TABLE #Paso_Vista(
        '''    [Id]                 [int] IDENTITY(1,1) NOT NULL,
        '''    [CODIGO]             [varchar](20) Default  (&apos;&apos;),
        '''	[DESCRIPCION]        [varchar](50) Default  (&apos;&apos;),
        '''	[DESCRIPCION_VISTA]  [varchar](100) Default (&apos;&apos;),
        '''	[EXCEL]              [varchar](50) Default  (&apos;&apos;)
        ''') ON [PRIMARY]
        '''
        '''Insert Into #Paso_Vista (CODIGO,DESCRIPCION,DESCRIPCION_VISTA,EXCEL) Values (&apos;Empresa&apos;,&apos;RAZON&apos;,&apos;EMPRESA&apos;,&apos;Inf_Empresa&apos;) 
        '''Insert Into #Paso_Vista (CODIGO,DESCRIPCION,DESCRIPCION_VISTA,EXCEL) Values [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Cargar_Tabla_Vista_del_Cubo() As String
            Get
                Return ResourceManager.GetString("Cargar_Tabla_Vista_del_Cubo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Declare @Fecha_Desde Date 
        '''
        '''Set @Fecha_Desde = &apos;#Fecha_Desde#&apos;
        '''
        '''SELECT REFERENCIA,IdMeson, Pd_Ms.Codmeson,Mss.Nommeson, Pd_Ms.Orden_Meson, Estado, Idpotpr, Idpotl, Idpote, Empresa,Cfp.RAZON, Numot, Orden_Potpr,Pd_Ms.Operacion, Nombreop, Nreg, Desde, Nivel, 
        '''	   Codigo, Glosa, Mp.NOKOPR As DescripcionPr,
        '''	   Mp.FMPR,Isnull(SFm.NOKOFM,&apos;&apos;) As NOKOFM,Isnull(Mp.PFPR,&apos;&apos;) As PFPR,Isnull(Ffm.NOKOPF,&apos;&apos;) As NOKOPF,Mp.HFPR,Isnull(Sbf.NOKOHF,&apos;&apos;) As NOKOHF,
        '''	   Asignado_Por, 
        '''	   FIOT,Fecha_Asignacion,
        '''	   DATE [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SQLQuery_Informe_de_tiempos_de_productos_por_meson() As String
            Get
                Return ResourceManager.GetString("SQLQuery_Informe_de_tiempos_de_productos_por_meson", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
