USE [#Base#]

CREATE TABLE [dbo].[Zw_PsLp#Funcionario#](
    [IdLista]           Int IDENTITY(1, 1) NOT NULL,
    [Select]            [Bit] Default (0),
	[Lista]             [char](3) NOT NULL,
	[Codigo]            [char](13) NOT NULL,
	[Descripcion]       [varchar](50) default '',
	[Rtu]               [float] Default (0),
	[Ud1]               [varchar](2) default '',
	[Ud2]               [varchar](2) default '',
	[Ej_Fx_documento]   [Bit] Default (0),
	[Ej_Fx_documento2]  [Bit] Default (0),
	[Formula]           [varchar](1000) default '',
	[Formula2]          [varchar](1000) default '',
	[FormulaRdUd1]      [varchar](1000) default '',
	[FormulaRdUd2]      [varchar](1000) default '',
	[Redondear]         [float] Default (0),
	[Costo]             [float] Default (0),
	[Precio]            [float] Default (0),
	[Margen]            [float] Default (0),
	[Margen_Adicional]  [float] Default (0),
	[Costo2]            [float] Default (0),
	[Precio2]           [float] Default (0),
	[Margen2]           [float] Default (0),
	[Margen_Adicional2] [float] Default (0),
	[DsctoMax]          [float] Default (0),
	[Dscto1]            [float] Default (0),
	[Dscto2]            [float] Default (0),
	[Dscto3]            [float] Default (0),
	[Dscto4]            [float] Default (0),
	[Dscto5]            [float] Default (0),
	[Flete]             [float] Default (0),
	[LtCosto]           [Char] (3) Default '',
	[CostoLt]           [float] Default (0),
	[Porc_Iva]          [float] Default (0),
	[Porc_Ila]          [float] Default (0),
	[Impuestos]         [float] Default (0),
	[Iva]               [float] Default (0),
	[Ila]               [float] Default (0),
	[Neto]              [float] Default (0),
	[Bruto]             [float] Default (0),
	[ValoresNetos]      [Bit]   Default (0),
	[Nuevo_Item]        [Bit]   Default (0),
	[Rubro]             [varchar](50) default '',
	[ClasLibre]         [varchar](50) default '',
	[Marca]             [varchar](50) default '',
	[Zona]              [varchar](50) default '',
	[SuperFamilia]      [varchar](50) default '',
	[Familia]           [varchar](50) default '',
	[SubFamilia]        [varchar](50) default '',
	[Pm]                [float]       Default (0),
	[Uc1]               [float]       Default (0),
	[Uc2]               [float]       Default (0)
 CONSTRAINT [PK_Zw_PsLp#Funcionario#] PRIMARY KEY CLUSTERED 
(
	[IdLista] ASC,
	[Lista] ASC,
	[Codigo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, 
       IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, 
       ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

--INSERT INTO Zw_PsLp#Funcionario# (Lista,Codigo,Descripcion,Rtu,Formula,Redondear,
--                                  Costo,Precio,Margen,Margen_Adicional,
--                                  Costo2,Precio2,Margen2,Margen_Adicional2,
--                                  DsctoMax,Dscto1,Dscto2,Dscto3,Dscto4,Dscto5,Flete)
--#ConsultaSql#                                  

