INSERT INTO Zw_ListaPreCosto 
(Lista, Proveedor, Codigo, CodAlternativo, CostoUd1, CostoUd2, Rtu, FechaVigencia, Desc1, Desc2, Desc3, 
Desc4)--, Desc5, Flete)
select KOLT,
       ISNULL((SELECT TOP 1 ENDO FROM MAEDDO WHERE KOPRCT = KOPR AND TIDO = 'GRC' ORDER BY FEEMLI DESC),'') AS KOEN,
       KOPR,'',PP01UD,PP02UD,RLUD,GETDATE(),DSCTONRO1,DSCTONRO2,DSCTONRO3,DSCTONRO4     
       From TABPRE 
WHERE KOLT = '#Lista#' AND PP01UD > 0 AND KOPR NOT IN (SELECT Codigo FROM Zw_ListaPreCosto WHERE Lista = 'PRO')

UPDATE Zw_ListaPreCosto SET Flete = Isnull((SELECT top 1 RECARGO FROM TABRECPR WHERE KOPR = Codigo AND  KOEN = Proveedor),0)
Where Lista = '#Lista#'


UPDATE Zw_ListaPreCosto SET 
CostoUd1 = ISNULL((SELECT PP01UD FROM TABPRE WHERE KOLT = 'PRO' AND KOPR = Codigo),0),
CostoUd2 = ISNULL((SELECT PP02UD FROM TABPRE WHERE KOLT = 'PRO' AND KOPR = Codigo),0),
Desc1 = ISNULL((SELECT DSCTONRO1 FROM TABPRE WHERE KOLT = 'PRO' AND KOPR = Codigo),0),
Desc2 = ISNULL((SELECT DSCTONRO2 FROM TABPRE WHERE KOLT = 'PRO' AND KOPR = Codigo),0),
Desc3 = ISNULL((SELECT DSCTONRO3 FROM TABPRE WHERE KOLT = 'PRO' AND KOPR = Codigo),0),
Desc4 = ISNULL((SELECT DSCTONRO4 FROM TABPRE WHERE KOLT = 'PRO' AND KOPR = Codigo),0)