BEGIN TRY
 DROP TABLE #Paso1
 END TRY
 BEGIN CATCH
END CATCH

Select #CODIGO# As CODIGO,#DESCRIPCION# As DESCRIPCION,
       DATENAME(YEAR,FEEMLI) As Ano,SUM(VANELI) As VANELI
Into #Paso1
From Zw_TblPasoMAF
Where 1 > 0
#Filtro_Sql#
Group By #CODIGO#,#DESCRIPCION#,FEEMLI
Select CODIGO,DESCRIPCION,Ano,Sum(VANELI) As Total
From #Paso1
Group By CODIGO,DESCRIPCION,Ano
Order By Ano


Drop Table #Paso1
