'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Recursos_Ver_Documento
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BkSpecialPrograms.Recursos_Ver_Documento", GetType(Recursos_Ver_Documento).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Declare @Id_DocEnc int 
        '''
        '''Select @Id_DocEnc = #Id_DocEnc#   
        '''
        '''Select Top 1 *,
        '''       ISNULL((Select Top 1 NOTIDO From TABTIDO Where TipoDoc = TIDO),&apos;&apos;) As &apos;TipoDocumento&apos;,
        '''	   --CONVERT(NVARCHAR, CONVERT(datetime, (EDO.HORAGRAB*1.0/3600)/24), 108) AS HORA,
        '''	   CAST(&apos;&apos; AS Varchar(10)) As NUMECOM,
        '''       &apos;&apos; As &apos;Ent_Fisica&apos;,
        '''       &apos;&apos; As &apos;Razon_Fisica&apos;,
        '''       &apos;No&apos; As &apos;Electronico&apos;,
        '''       &apos;Vigente&apos; As &apos;Estado&apos; 
        '''
        '''From #Base_Bakapp#Zw_Casi_DocEnc WITH ( NOLOCK )  
        '''Where  Id_DocEnc = @Id_DocEnc  
        '''        ''' [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Traer_Documento_Bakapp() As String
            Get
                Return ResourceManager.GetString("Traer_Documento_Bakapp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE @Idmaeedo int 
        '''
        '''Select @Idmaeedo = #Idmaeedo#   
        '''
        '''SELECT TOP 1 *,
        '''	   SUBSTRING(CONVERT(NVARCHAR, CONVERT(datetime, (EDO.HORAGRAB*1.0/3600)/24), 108),1,5) AS HORA,
        '''	   CAST(&apos;&apos; AS Varchar(10)) As NUMECOM,
        '''       ISNULL((SELECT TOP 1 NOKOEN FROM MAEEN WHERE KOEN = EDO.ENDO AND SUEN = EDO.SUENDO),&apos;&apos;) AS &apos;RAZON&apos;,
        '''       ISNULL(EDO.ENDOFI,&apos;&apos;) AS &apos;ENT_FISICA&apos;,
        '''       ISNULL((SELECT TOP 1 NOKOEN FROM MAEEN WHERE KOEN = EDO.ENDOFI),&apos;&apos;) AS &apos;RAZON_FISICA&apos;,
        '''       ISNULL((SELECT TOP 1 NOKOFU FROM TAB [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Traer_Documento_Random() As String
            Get
                Return ResourceManager.GetString("Traer_Documento_Random", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
