'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Recursos_Cadena_Remotas
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BkSpecialPrograms.Recursos_Cadena_Remotas", GetType(Recursos_Cadena_Remotas).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Declare @Tido Char(3),
        '''		@Ver_Todas Bit,
        '''		@CodFuncionario Char(3)
        '''
        '''Select @Tido = &apos;#Tido#&apos;,@Ver_Todas = #Ver_Todas#,@CodFuncionario = &apos;#CodFuncionario#&apos;
        '''
        '''Select Case When Edo.IDMAEEDO Is Null Then Z2.Empresa Else Edo.EMPRESA End As &apos;Empresa&apos;,
        '''	   Case When Edo.IDMAEEDO Is Null Then Z2.Sucursal Else Edo.SUDO End As &apos;Sucursal&apos;,
        '''	   Id_Enc, 
        '''	   Cast(0 As Int) As Anotaciones,
        '''	   Estado, 
        '''       Case Estado 
        '''	       When &apos;&apos; Then &apos;Enviada&apos; 
        '''		   When &apos;P&apos; then &apos;En Proceso&apos; 
        '''		   When &apos;A&apos; then &apos;Ace [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SQLQuery_Informe_Remotas_Pendientes() As String
            Get
                Return ResourceManager.GetString("SQLQuery_Informe_Remotas_Pendientes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 
        '''
        '''Select Z1.*,Z2.Fecha_Otorga,
        '''    Z3.Tido,
        '''	Z3.CodEntidad,
        '''	Z3.Nombre_Entidad,
        '''	Isnull(Z2.CodFuncionario_Solicita,&apos;&apos;) As CodFuncionario_Solicita,
        '''	Isnull(NOKOFU,&apos;???&apos;) As Nombre_Usuario_Solicita,
        '''	Isnull(Z2.CodFuncionario_Autoriza,&apos;&apos;) As CodFuncionario_Autoriza,	
        '''	Isnull(Z2.Otorga,&apos;&apos;) As Otorga,
        '''	Isnull(Z2.Permiso_Otorgado,0) As Permiso_Otorgado,
        '''	Isnull(Z2.Observaciones,0) As Observaciones,
        '''	Isnull((Select Top 1 CodFuncionario From #_Global_BaseBk#Zw_Casi_DocTom Z3 Where Z1.NroRemota = Z3.NroR [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SQLQuery_Informe_Remotas_Pendientes_Detalle() As String
            Get
                Return ResourceManager.GetString("SQLQuery_Informe_Remotas_Pendientes_Detalle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 
        '''-- CONSULTA PARA REENVIAR SOLICITUD DE PEDIDO
        '''
        '''Declare @New_Nro_Remota Varchar(10),
        '''		@Old_Nro_Remota Varchar(10),
        '''		@Id_Enc Int,
        '''		@Id_Det Int
        '''
        '''Select @New_Nro_Remota = &apos;#New_NroRemota#&apos;,
        '''	   @Old_Nro_Remota = &apos;#Old_NroRemota#&apos;,
        '''	   @Id_Enc = #Id_Enc#,
        '''	   @Id_Det = #Id_Det#
        '''
        '''Update #_Global_BaseBk#Zw_Remotas_En_Cadena_01_Enc Set Estado = &apos;r&apos;
        '''WHERE Id_Enc = @Id_Enc
        '''
        '''Insert Into #_Global_BaseBk#Zw_Remotas (Empresa, NroRemota, CodFuncionario_Solicita, CodFuncionario_Autoriza, CodPermiso, Des [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SQLQuery_Reenviar_Solicitud_De_Permiso() As String
            Get
                Return ResourceManager.GetString("SQLQuery_Reenviar_Solicitud_De_Permiso", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
