Declare @NumOT as varchar(10) = '#Numot#'

SELECT        IDPOTE, EMPRESA, NUMOT, ESTADO, FIOT, FTOT, REFERENCIA, PLANO, EXTEN, NUMPLAN, SUOT, KOFUCRE, KOFUCIE, HORAGRAB, 
              TIPOOT, ESODD, ENDO, SUENDO, FACTURAR, KOFUFACTU, MODO, TIMODO, TAMODO, KOCT01, POKOCT01, KOCT02, POKOCT02, KOCT03, 
              POKOCT03, DIASVIGCOT, FORMAPAGO, ENCARGADO, CARGO, KOPROYE, KOETAPA, OCDO, FECHAOC, FTESPPROD, PLANTAOT,
			  1 As Contador,
			  Cast(0 As Bit) As Impreso
Into #Paso_Pote
FROM          POTE
WHERE        (NUMOT = @NumOT)

SELECT        IDPOTL, IDPOTE, EMPRESA, NUMOT, NREG, ESTADO, DESDE, CODIGO, UDAD, CODNOMEN, NUMECOTI, NREGCOT, FABRICAR, REALIZADO, 
              DIFERENCIA, MARCANOM, NUMDEEST, NIVEL, GLOSA, PLANO, EXTEN, NIVELSUP, ESCADENA, PORENTRAR, NUMPLAN, INFORABODE, 
              LILG, NUMODC, NREGODC, SULIOTL, BOLIOTL, PORASIGNAR, KOFUCRE, KOFUCIE, F_COSTEO, C_FABRIC, C_INSUMOS, C_MAQUINAS, 
              C_M_OBRA, ESODD, VNSERVICIO, P_FABRIC, P_INSUMOS, P_MAQUINAS, P_M_OBRA, CCFABRIC, CCINSUMOS, CCMAQUINAS, 
              CCM_OBRA, PCFABRIC, PCINSUMOS, PCMAQUINAS, PCM_OBRA, PODESVNSER, ECUVNSERVI, OBSERVA, FIPOTL, 
              FTPOTL, PLANTA, USOS, PREFIJADO, PODESINSU, PODESMO, PODESMAQ, PODESSAL,
			  1 As Contador,
			  Cast(0 As Bit) As Impreso
Into #Paso_Potl
FROM          POTL
WHERE        (NUMOT = @NumOT)

SELECT        IDPOTD, IDPOTL, EMPRESA, NUMOT, NREG, SUBNREG, ESTADO, PERTENECE, NIVEL, AUXI, CODIGO, MARCANOM, CODNOMEN, NUMDEEST, 
              GLOSA, TIPOUNI, DOBLEU, CANTIDADF, CANTIDACF, CANTIDADR, CANTANTI, UNIDAD, UNIDADC, TIPO, OPERACION, CALIDAD, 
              NIVELSUP, NUMPLAN, LILG, NUMODC, NREGODC, SULIOTD, BOLIOTD, PNPDNREG, C_SALIDA, C_INSUMOS, P_INSUMOS, CCINSUMOS, 
              PCINSUMOS,
			  1 As Contador,
			  Cast(0 As Bit) As Impreso
Into #Paso_Potd
FROM          POTD
WHERE        (NUMOT = @NumOT)

SELECT        IDPOTPR, IDPOTL, EMPRESA, NUMOT, NREGOTL, CODIGO, 
              OPERACION, CAST('' AS VARCHAR(50)) AS NOMBRE_OPERACION,
			  ORDEN, POROPANT, PORREQCOMP, TIPOOP, ESTADO, SITPEDFAB, 
              FABRICAR, REALIZADO, SALPROXJOR, PORMAQUILA, LILG, NUMODC, NREGODC, 
			  CODMAQOT, CAST('' AS VARCHAR(50)) AS NOMBRE_MAQUINA, 
			  C_FABRIC, C_INSUMOS, C_MAQUINAS, 
              C_M_OBRA, P_FABRIC, P_INSUMOS, P_MAQUINAS, P_M_OBRA, CCFABRIC, CCINSUMOS, CCMAQUINAS, CCM_OBRA, PCFABRIC, 
              PCINSUMOS, PCMAQUINAS, 
              PCM_OBRA, NOTAS, PERMAQALT, PERMAQPAR,
              'stx;'+ltrim(rtrim(str(POTPR.IDPOTPR))) As [STX],
              'etx;'+ltrim(rtrim(str(POTPR.IDPOTPR))) As [ETX],
			  1 As Contador,
			  Cast(0 As Bit) As Impreso
Into #Paso_Potpr
FROM            POTPR
WHERE        (NUMOT = @NumOT)

UPDATE #Paso_Potpr Set NOMBRE_OPERACION = (Select top 1 NOMBREOP From POPER Where POPER.OPERACION = #Paso_Potpr.OPERACION)
UPDATE #Paso_Potpr Set NOMBRE_MAQUINA = (Select top 1 NOMBREMAQ From PMAQUI Where PMAQUI.CODMAQ = #Paso_Potpr.CODMAQOT)
 
Select * From #Paso_Pote
Select * From #Paso_Potl Order By NREG
Select * From #Paso_Potd
Select * From #Paso_Potpr

Drop Table #Paso_Pote
Drop Table #Paso_Potl
Drop Table #Paso_Potd
Drop Table #Paso_Potpr

