'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Sql_Entidad
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BkSpecialPrograms.Sql_Entidad", GetType(Sql_Entidad).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a INFORMACION DE ENTIDAD
        '''
        '''
        '''CODIGO         : #CODIGO#
        '''RUT            : #RUT#
        '''TIPO           : #TIPOSUCURSAL#
        '''
        '''RAZON SOCIAL   : #RAZON#                                             
        '''DIRECCION      : #DIRECCION#
        '''SIGLA          : #SIGLA#  
        '''PAIS           : #PAIS#                                                 
        '''CIUDAD         : #CIUDAD#
        '''COMUNA         : #COMUNA#
        '''ZONA           : #ZONA#
        '''
        '''FONO-FAX       : #TELEFONO# - #FAX#
        '''EMAIL          : #EMAIL1#
        '''EMAIL COMER.   : #EMAIL2#
        '''
        '''ASIGNACIONES
        '''
        '''TIPO  [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Informacion_Entidad() As String
            Get
                Return ResourceManager.GetString("Informacion_Entidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 
        '''Declare @Lista Char(3),
        '''        @CodEntidad Char(13)
        '''
        '''Select @Lista = &apos;#Lista#&apos;,@CodEntidad = &apos;#CodEntidad#&apos;
        '''
        '''Insert Into Zw_ListaPreCosto (Lista, Proveedor, Sucursal, CodAlternativo, Codigo, Descripcion, Descripcion_Alt, 
        '''                              CostoUd1, CostoUd2, Rtu, FechaVigencia, 
        '''                              Un_Compra, Un_MinCompra)
        '''select @Lista,KOEN,&apos;&apos;,KOPRAL,KOPR,NOKOPRAL,NOKOPRAL,
        '''        (Select top 1 Case 
        '''                          When RLUD &gt;= 1 Then PP01UD
        '''                 [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SqlQuery_Actualizar_Lista_Entidad() As String
            Get
                Return ResourceManager.GetString("SqlQuery_Actualizar_Lista_Entidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 
        '''Declare @CodEntidad Char(13),
        '''        @SucEntidad Char(10) 
        '''
        '''Select @CodEntidad = &apos;#CodEntidad#&apos;,@SucEntidad = &apos;#SucEntidad#&apos;
        '''
        '''Select CAST( &apos;&apos; AS Varchar(15)) As &apos;Rut&apos;,
        '''       *, 
        '''       Isnull((Select top 1 NOKOFU From TABFU Where KOFU = KOFUEN),&apos;&apos;) As &apos;VENDEDOR&apos;,
        '''       Isnull((Select top 1 NOKOFU From TABFU Where KOFU = COBRADOR),&apos;&apos;) As &apos;NOMCOBRADOR&apos;,
        '''       Case TIPOSUC When &apos;C&apos; Then &apos;CLIENTE&apos; When &apos;P&apos; Then &apos;PROVEEDOR&apos; Else &apos;AMBOS&apos; End As &apos;TIPOSUCURSAL&apos;,
        '''       (Select Top 1 NOKOEN From MAEE [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SqlQuery_Datos_Entidad() As String
            Get
                Return ResourceManager.GetString("SqlQuery_Datos_Entidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Declare @CodEntidad Char(13),
        '''        @SucEntidad Char(10),
        '''        @Fecha Datetime
        '''
        '''Select @CodEntidad = &apos;#CodEntidad#&apos;,@SucEntidad = &apos;#SucEntidad#&apos;,@Fecha = &apos;#Fecha#&apos;
        '''
        '''-- DEUDA TOTAL INCLUYE DOCUMENTOS TRANSITORIOS
        '''
        '''SELECT MAEVEN.*,MAEVEN.VAVE-MAEVEN.VAABVE AS SALDO,DATEDIFF(day,FEVE,GETDATE()) DIAS_ATRASO,
        '''       MAEEDO.TIDO,MAEEDO.NUDO,MAEEDO.ENDO,MAEEDO.NUDONODEFI 
        '''FROM MAEVEN LEFT JOIN MAEEDO ON MAEEDO.IDMAEEDO=MAEVEN.IDMAEEDO  
        '''WHERE  
        '''--MAEEDO.ENDO=&apos;99231000     &apos; AND
        '''--MAEEDO.NUDONODEF [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SqlQuery_deuda_doc_comerciales() As String
            Get
                Return ResourceManager.GetString("SqlQuery_deuda_doc_comerciales", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 
        '''Declare @CodEntidad Char(13),
        '''        @Empresa char(2) 
        '''
        '''Select @CodEntidad = &apos;#CodEntidad#&apos;,@Empresa = &apos;#Empresa#&apos;
        '''
        '''-- TABLA 0    DEUDA
        '''SELECT EDO.IDMAEEDO,EDO.EMPRESA, EDO.TIDO, EDO.NUDO, EDO.ENDO, EDO.SUENDO, EDO.MODO, EDO.TIMODO, EDO.TAMODO, EDO.ESPGDO, EDO.FEULVEDO, 
        '''ROUND(EDO.VABRDO,2) AS VABRDO, ROUND(EDO.VAABDO,2) AS VAABDO,ROUND(EDO.VABRDO - EDO.VAABDO,2) AS SALDO,
        '''ROUND(EDO.VAIVARET,2) AS VAIVARET, ROUND(EDO.VAIVDO,2) AS VAIVDO, 
        '''ROUND(EDO.VANEDO,2) AS VANEDO,EDO.BLOQUEAPAG,EDO.NUDONODE [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SqlQuery_InfoCreditoEntidad() As String
            Get
                Return ResourceManager.GetString("SqlQuery_InfoCreditoEntidad", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
