Declare @CodEntidad Char(13),
        @SucEntidad Char(10),
        @Fecha Datetime

Select @CodEntidad = '#CodEntidad#',@SucEntidad = '#SucEntidad#',@Fecha = '#Fecha#'

-- DEUDA TOTAL INCLUYE DOCUMENTOS TRANSITORIOS

SELECT MAEVEN.*,MAEVEN.VAVE-MAEVEN.VAABVE AS SALDO,DATEDIFF(day,FEVE,GETDATE()) DIAS_ATRASO,
       MAEEDO.TIDO,MAEEDO.NUDO,MAEEDO.ENDO,MAEEDO.NUDONODEFI 
FROM MAEVEN LEFT JOIN MAEEDO ON MAEEDO.IDMAEEDO=MAEVEN.IDMAEEDO  
WHERE  
--MAEEDO.ENDO='99231000     ' AND
--MAEEDO.NUDONODEFI = 0 AND 
MAEVEN.ESPGVE=''  AND 
MAEVEN.FEVE<=@Fecha AND  
MAEEDO.TIDO IN  ('BLV','BSV','BLX','FCV','FDB','FDV','FDX','FDZ','FEV','FVL','FVT','FVX','FVZ','RIN','ESC','FEE') AND
MAEEDO.ENDO = @CodEntidad --AND MAEEDO.SUENDO = @SucEntidad 
ORDER BY MAEEDO.ENDO ,MAEVEN.ESPGVE ,MAEVEN.FEVE  --OPTION ( FAST 20 ) 

