
Declare @CodEntidad Char(13),
        @Empresa char(2) 

Select @CodEntidad = '#CodEntidad#',@Empresa = '#Empresa#'

-- TABLA 0    DEUDA
SELECT EDO.IDMAEEDO,EDO.EMPRESA, EDO.TIDO, EDO.NUDO, EDO.ENDO, EDO.SUENDO, EDO.MODO, EDO.TIMODO, EDO.TAMODO, EDO.ESPGDO, EDO.FEULVEDO, 
ROUND(EDO.VABRDO,2) AS VABRDO, ROUND(EDO.VAABDO,2) AS VAABDO,ROUND(EDO.VABRDO - EDO.VAABDO,2) AS SALDO,
ROUND(EDO.VAIVARET,2) AS VAIVARET, ROUND(EDO.VAIVDO,2) AS VAIVDO, 
ROUND(EDO.VANEDO,2) AS VANEDO,EDO.BLOQUEAPAG,EDO.NUDONODEFI,
CASE EDO.NUDONODEFI WHEN 1 THEN 'Documento en Transito' ELSE 'Definitivo' End As 'DEFOTRANS'  
Into #SinDocumentar
FROM MAEEDO AS EDO  WITH ( NOLOCK )  
WHERE EDO.ENDO = @CodEntidad AND 
EDO.TIDO IN  ('BLV','BSV','BLX','FCV','FDB','FDV','FDX','FDZ','FEV','FVL','FVT','FVX','FVZ','RIN','ESC','FEE','NCC','NCB') 
AND EDO.ESPGDO = 'P' AND EDO.NUDONODEFI = 0  
AND EDO.EMPRESA = @Empresa  ORDER BY EDO.TIDO,EDO.NUDO 

-- TABLA 1    PAGOS EN  CTA CTE
SELECT DPCE.IDMAEDPCE,DPCE.EMPRESA,DPCE.TIDP,ISNULL((SELECT TOP 1 NOKOENDP FROM TABENDP WHERE KOENDP = DPCE.EMDP),'') AS BANCO, 
       DPCE.NUDP, DPCE.ENDP, DPCE.EMDP, DPCE.SUEMDP, DPCE.CUDP,       
       DPCE.NUCUDP, DPCE.FEEMDP, DPCE.FEVEDP, DPCE.MODP, DPCE.TIMODP, DPCE.TAMODP,       
       DPCE.VADP, DPCE.VAABDP, DPCE.VAASDP, DPCE.VAVUDP, DPCE.ESPGDP, DPCE.REFANTI 
Into #Pagos
FROM MAEDPCE AS DPCE  WITH ( NOLOCK )  
WHERE DPCE.ENDP = @CodEntidad  AND DPCE.TIDP IN  ('ATB','CHV','CPV','CRV','DEP','EFV','LTV','PAV','RBV','RGV','RIV','TJV','VUE')  
AND ( DPCE.ESPGDP = 'P' OR DPCE.ESPGDP = 'R' )  AND DPCE.EMPRESA = @Empresa 


-- TABLA 2 CHEQUES
SELECT DPCE.IDMAEDPCE,DPCE.EMPRESA,DPCE.TIDP,ISNULL((SELECT TOP 1 NOKOENDP FROM TABENDP WHERE KOENDP = DPCE.EMDP),'') AS BANCO, 
       DPCE.NUDP, DPCE.ENDP, DPCE.EMDP, DPCE.SUEMDP, DPCE.CUDP,       
       DPCE.NUCUDP, DPCE.FEEMDP, DPCE.FEVEDP, DPCE.MODP, DPCE.TIMODP, DPCE.TAMODP,       
       DPCE.VADP, DPCE.VAABDP, DPCE.VAASDP, DPCE.VAVUDP, DPCE.ESPGDP, DPCE.REFANTI 
Into #Cheques
FROM MAEDPCE AS DPCE  WITH ( NOLOCK )  
WHERE DPCE.ENDP = @CodEntidad  AND DPCE.TIDP IN  ('CHV')  
AND ( DPCE.ESPGDP = 'P' OR DPCE.ESPGDP = 'R' )  AND DPCE.EMPRESA = @Empresa

-- TABLA 3 LETRAS
SELECT DPCE.IDMAEDPCE,DPCE.EMPRESA,DPCE.TIDP,ISNULL((SELECT TOP 1 NOKOENDP FROM TABENDP WHERE KOENDP = DPCE.EMDP),'') AS BANCO, 
       DPCE.NUDP, DPCE.ENDP, DPCE.EMDP, DPCE.SUEMDP, DPCE.CUDP,       
       DPCE.NUCUDP, DPCE.FEEMDP, DPCE.FEVEDP, DPCE.MODP, DPCE.TIMODP, DPCE.TAMODP,       
       DPCE.VADP, DPCE.VAABDP, DPCE.VAASDP, DPCE.VAVUDP, DPCE.ESPGDP, DPCE.REFANTI 
Into #Letras
FROM MAEDPCE AS DPCE  WITH ( NOLOCK )  
WHERE DPCE.ENDP = @CodEntidad  AND DPCE.TIDP IN  ('LTV')  
AND ( DPCE.ESPGDP = 'P' OR DPCE.ESPGDP = 'R' )  AND DPCE.EMPRESA = @Empresa

-- TABLA 4 PAGARES
SELECT DPCE.IDMAEDPCE,DPCE.EMPRESA,DPCE.TIDP,ISNULL((SELECT TOP 1 NOKOENDP FROM TABENDP WHERE KOENDP = DPCE.EMDP),'') AS BANCO, 
       DPCE.NUDP, DPCE.ENDP, DPCE.EMDP, DPCE.SUEMDP, DPCE.CUDP,       
       DPCE.NUCUDP, DPCE.FEEMDP, DPCE.FEVEDP, DPCE.MODP, DPCE.TIMODP, DPCE.TAMODP,       
       DPCE.VADP, DPCE.VAABDP, DPCE.VAASDP, DPCE.VAVUDP, DPCE.ESPGDP, DPCE.REFANTI 
Into #Pagares
FROM MAEDPCE AS DPCE  WITH ( NOLOCK )  
WHERE DPCE.ENDP = @CodEntidad  AND DPCE.TIDP IN  ('PAV')  
AND ( DPCE.ESPGDP = 'P' OR DPCE.ESPGDP = 'R' )  AND DPCE.EMPRESA = @Empresa

-- TABLA 5 NVV
SELECT 
		EDO.IDMAEEDO,EDO.EMPRESA, EDO.TIDO, EDO.NUDO, EDO.ENDO, EDO.SUENDO, EDO.MODO, EDO.TIMODO, EDO.TAMODO, EDO.ESPGDO, EDO.FEULVEDO, 
		ROUND(EDO.VABRDO,2) AS VABRDO, ROUND(EDO.VAABDO,2) AS VAABDO,ROUND(EDO.VABRDO - EDO.VAABDO,2) AS SALDO,
		ROUND(EDO.VAIVARET,2) AS VAIVARET, ROUND(EDO.VAIVDO,2) AS VAIVDO, 
		ROUND(EDO.VANEDO,2) AS VANEDO,EDO.BLOQUEAPAG,EDO.NUDONODEFI,
		CASE EDO.NUDONODEFI WHEN 1 THEN 'Documento en Transito' ELSE 'Definitivo' End As 'DEFOTRANS'
		Into #Utilizado_NVV
		FROM MAEEDO AS EDO  WITH ( NOLOCK )  
		WHERE EDO.ENDO = @CodEntidad AND 
		EDO.TIDO IN  ('NVV') 
		AND EDO.NUDONODEFI = 0 And EDO.ESDO = '' 
		AND EDO.EMPRESA = @Empresa  ORDER BY EDO.TIDO,EDO.NUDO 

Update #Utilizado_NVV Set VAABDO = Isnull((Select Sum(VABRLI) As FCV_NVV From MAEDDO Where IDRST In (Select IDMAEDDO From MAEDDO Where IDMAEEDO = #Utilizado_NVV.IDMAEEDO)),0)
Update #Utilizado_NVV Set SALDO = ROUND(VABRDO - VAABDO,2)

Select Cast(0 As Float) AS 'SIN_DOCUMENTAR',
	   Cast(0 As Float) AS 'PAGOS',
	   Cast(0 As Float) AS 'CHEQUES',
	   Cast(0 As Float) AS 'LETRAS',
	   Cast(0 As Float) AS 'PAGARES',
	   Cast(0 As Float) AS 'NVV'
Into #Totales

Update #Totales Set SIN_DOCUMENTAR = Isnull((Select Sum(SALDO) From #SinDocumentar),0),
					CHEQUES = Isnull((Select Sum(VAASDP) From #Cheques),0),
					LETRAS = Isnull((Select Sum(VAASDP) From #Letras),0),
					PAGARES = Isnull((Select Sum(VAASDP) From #Pagares),0),
					NVV = Isnull((Select Sum(SALDO) From #Utilizado_NVV),0)

Select * From #SinDocumentar
Select * From #Pagos
Select * From #Cheques
Select * From #Letras
Select * From #Pagares

Select IDMAEEDO,TIDO,NUDO,DEFOTRANS,FEULVEDO,VABRDO,VAABDO,SALDO,NUDONODEFI From #Utilizado_NVV
Union
Select Id_DocEnc As IDMAEEDO,TipoDoc As TIDO,NroDocumento As NUDO,'Pdte. Permiso Remoto Bakapp' As DEFOTRANS, FechaUltVencimiento As FEULVEDO,
	   TotalBrutoDoc As VABRDO,0,TotalBrutoDoc As SALDO,Cast(1 As Bit) As NUDONODEFI
From   #Base_Bakapp#Zw_Casi_DocEnc
Where Id_DocEnc In (Select Id_DocEnc From #Base_Bakapp#Zw_Remotas_En_Cadena_01_Enc Where CodEntidad = @CodEntidad And Estado Not In ('A','R'))
Order By NUDO

Select * From #Totales

Drop Table #SinDocumentar
Drop Table #Pagos
Drop Table #Cheques
Drop Table #Letras
Drop Table #Pagares
Drop Table #Utilizado_NVV
Drop Table #Totales
