'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Recursos_Inf_MgProyecion
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BkSpecialPrograms.Recursos_Inf_MgProyecion", GetType(Recursos_Inf_MgProyecion).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE 
        '''
        '''@Fecha1 Date = &apos;#Fecha_Desde#&apos;,
        '''@Fecha2 Date = &apos;#Fecha_Hasta#&apos;,
        '''@Total_Neto Float,
        '''@PP_Mrg Float,
        '''@Total_Margen Float
        '''
        '''SELECT	IDMAEEDO,TIDO,NUDO,ENDO,SUENDO,KOPRCT,UDTRPR,CAPRCO1,CAPRCO2,PPPRNELT,PPPRNE,PPPRBRLT,PPPRBR,POIVLI,VAIVLI,
        '''        VANELI,VABRLI,PPPRPM, 
        '''        ROUND(PPPRPM * CAPRCO1,0) AS COSTO,
        '''		CASE WHEN VANELI &gt; 0 THEN ROUND((VANELI-(PPPRPM * CAPRCO1))/VANELI,4) ELSE 0 END AS MG,
        '''		ROUND(VANELI-ROUND(PPPRPM * CAPRCO1,0),0) AS MARGEN
        '''Into #Paso_Detalle
        '''FROM MAEDDO 
        '''WH [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SQLQuery_Revision_Margenes_SeaGarden_Con_Mediana() As String
            Get
                Return ResourceManager.GetString("SQLQuery_Revision_Margenes_SeaGarden_Con_Mediana", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
