
BEGIN TRY
 DROP TABLE #INFVEN
 END TRY
 BEGIN CATCH
END CATCH

BEGIN TRY
 DROP TABLE #INFVENR
 END TRY
 BEGIN CATCH
END CATCH

Declare @Fecha_Inicio Datetime,
        @Fecha_Fin Datetime,
        @Empresa Char(2)

Select @Fecha_Inicio = '#Fecha_Inicio#',
        @Fecha_Fin = '#Fecha_Fin#',
        @Empresa = '#Empresa#'

SELECT CAST( 0 AS Bit) AS Chk, 
       EDO.IDMAEEDO,VEN.IDMAEVEN, EDO.ENDO,EDO.SUENDO,
	   Isnull((Select top 1 RTEN From MAEEN Where KOEN = EDO.ENDO And SUEN = EDO.SUENDO),'') As RTEN,	
	   CAST('' AS Varchar(15)) AS RUT,
       Isnull((Select top 1 NOKOEN From MAEEN Where KOEN = EDO.ENDO And SUEN = EDO.SUENDO),'') As NOKOEN,
       EDO.TIDO,
       Isnull((Select Top 1 NOTIDO From TABTIDO Where TIDO = EDO.TIDO),'') As Tipo,
       EDO.NUDO,
       EDO.FEEMDO,VEN.FEVE,DATEDIFF(DD,FEEMDO,FEVE) AS DIAS,DATEDIFF(DD,GETDATE(),FEVE) AS DIAS_ATRASO,
	(CASE  
		WHEN EDO.TIMODO='E' THEN VEN.VAVE*EDO.TAMODO*( 
			CASE 
				WHEN EDO.TIDO IN ('NCV','NCX','NEV') OR EDO.TIDO='NCC' THEN -1 
				ELSE 1 
			END) 
		ELSE VEN.VAVE*( 
			CASE 
				WHEN EDO.TIDO IN ('NCV','NCX','NEV') OR EDO.TIDO='NCC' THEN -1 
				ELSE 1 
			END) 
	END) AS VAVE ,

	(CASE  
		WHEN EDO.TIMODO='E' THEN VEN.VAABVE*EDO.TAMODO*( 
			CASE 
				WHEN EDO.TIDO IN ('NCV','NCX','NEV') OR EDO.TIDO='NCC' THEN -1 
				ELSE 1 
			END ) 
		ELSE VEN.VAABVE*( 
			CASE 
				WHEN EDO.TIDO IN ('NCV','NCX','NEV') OR EDO.TIDO='NCC' THEN -1 
				ELSE 1 
			END ) 
	END) AS VAABVE ,
	CAST( 0 AS Float) AS SALDO,
    VEN.ESPGVE,
    CAST( 0 AS Bit) AS SOSPECHA_STOCK,
    CAST( 0 AS Bit) AS SOSPECHA_DEVOLUCION,
    CAST( 0 AS Bit) AS REVISADO_PAGAR,
    CAST( 0 AS Bit) AS AUTORIZADO_PAGAR,
    EDO.FEULVEDO,
    'Documentos' as Deuda,
    CAST('MAEEDO' As Varchar(10)) As ARCHIRVE,
    EDO.IDMAEEDO AS IDRVE,
    CAST(
         Isnull((Select Top 1 CONVERT(VARCHAR, FEVENTO, 103)+' -> '+KOTABLA+' -> '+KOCARAC+' -> '+NOKOCARAC  
		 From MEVENTO 
		 Where KOTABLA = 'COBRANZA' And ARCHIRVE = 'MAEEDO' And IDRVE = EDO.IDMAEEDO Order by IDEVENTO Desc),'') 
         As Varchar(1000)) As 'ULT_EVENTO'    
		
INTO #INFVEN 		 

FROM MAEVEN AS VEN WITH ( NOLOCK )  
	INNER JOIN MAEEDO AS EDO ON EDO.IDMAEEDO=VEN.IDMAEEDO  
	LEFT JOIN MAEEN WITH (NOLOCK) ON MAEEN.KOEN=EDO.ENDO AND MAEEN.SUEN=EDO.SUENDO  
	LEFT JOIN TABSU ON TABSU.KOSU=EDO.SUDO  
	LEFT JOIN TABFU ON TABFU.KOFU=EDO.KOFUDO  
	LEFT JOIN TABLUG ON TABLUG.LUVT=EDO.LUVTDO  	

WHERE 
    EDO.NUDONODEFI = 0 AND
	EDO.TIDO IN ('BLC','FCC','FCT','FDC','NCB','NCC','RGA') AND 
	EDO.EMPRESA = @Empresa  AND 
	VEN.FEVE  BETWEEN @Fecha_Inicio AND @Fecha_Fin AND 
	VEN.ESPGVE <> 'C' 
    --#Filtro_Adicional
     
ORDER BY EDO.FEEMDO	
		
UPDATE #INFVEN SET SALDO = COALESCE(VAVE-VAABVE ,0.0) 





