-- INSERTA DOCUMENTOS DE PAGO PENDIENTES DE LA ENTIDAD


INSERT INTO #INFVEN(IDMAEEDO,IDMAEVEN,ENDO,SUENDO,RTEN,RUT,NOKOEN,TIDO,NUDO,FEEMDO,FEVE,DIAS,DIAS_ATRASO,VAVE,VAABVE,SALDO,ESPGVE,SOSPECHA_STOCK,SOSPECHA_DEVOLUCION,FEULVEDO)
SELECT DPCE.IDMAEDPCE AS IDMAEEDO,0 AS IDMAEVEN,DPCE.ENDP AS ENDO,'' AS SUENDO,
       (SELECT TOP 1 RTEN FROM MAEEN WHERE KOEN = DPCE.ENDP) AS RTEN,
       CAST('' AS Varchar(15)) AS RUT,
       (SELECT TOP 1 NOKOEN FROM MAEEN WHERE KOEN = DPCE.ENDP) AS NOKOEN,DPCE.TIDP AS TIDO,DPCE.NUDP AS NUDO,
       DPCE.FEEMDP AS FEEMDO, DPCE.FEVEDP AS FEVE,
       DATEDIFF(DD,DPCE.FEEMDP,DPCE.FEVEDP) AS DIAS,DATEDIFF(DD,GETDATE(),DPCE.FEVEDP) AS DIAS_ATRASO,
       DPCE.VADP AS VAVE,DPCE.VAABDP AS VAABVE,(DPCE.VADP - DPCE.VAABDP) AS SALDO,
       '' AS ESPGVE,CAST( 0 AS Bit) AS SOSPECHA_STOCK,CAST( 0 AS Bit) AS SOSPECHA_DEVOLUCION,
       DPCE.FEVEDP ASFEULVEDO
   	    
FROM MAEDPCE AS DPCE  WITH ( NOLOCK )  
WHERE 
	DPCE.ENDP In (Select Distinct ENDO From #INFVEN)  AND 
	--DPCE.TIDP IN  ('ATB','CHV','CPV','CRV','DEP','EFV','LTV','PAV','RBV','RGV','RIV','TJV','VUE')  AND 
    DPCE.TIDP IN  ('ATB','CHV','CPV','CRV','DEP','LTV','PAV','RBV','RGV','RIV','VUE')  AND 	
	( DPCE.ESPGDP = 'P' OR DPCE.ESPGDP = 'R' )  AND 
	DPCE.EMPRESA = '01' And 
	DPCE.FEVEDP  BETWEEN @Fecha_Inicio AND @Fecha_Fin 
  
-----------------------------------------------------------------------------------------------------------	 


