'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Recursos_Inf_Compras_Vencimiento
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BkSpecialPrograms.Recursos_Inf_Compras_Vencimiento", GetType(Recursos_Inf_Compras_Vencimiento).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;html&gt;
        '''&lt;head&gt;
        '''&lt;title&gt;Documento Comercial&lt;/title&gt;
        '''&lt;meta http-equiv=&apos;Content-Type&apos; content=&apos;text/html; charset=iso-8859-1&apos; /&gt;
        '''    &lt;style type=&quot;text/css&quot;&gt;
        '''        .style17
        '''        {
        '''            width: 109px;
        '''        }
        '''        .style20
        '''        {
        '''            width: 87px;
        '''        }
        '''        .style21
        '''        {
        '''            width: 144px;
        '''        }
        '''        .style22
        '''        {
        '''            width: 174px;
        '''        }
        '''        .style23
        '''        {
        '''            width: 320px;
        '''        }
        '''        .style25
        '''    [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Crear_Html_Facturas_Cobranza() As String
            Get
                Return ResourceManager.GetString("Crear_Html_Facturas_Cobranza", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;html&gt;
        '''&lt;head&gt;
        '''&lt;title&gt;Documento Comercial&lt;/title&gt;
        '''&lt;meta http-equiv=&apos;Content-Type&apos; content=&apos;text/html; charset=iso-8859-1&apos; /&gt;
        '''    &lt;style type=&quot;text/css&quot;&gt;
        '''        .style17
        '''        {
        '''            width: 109px;
        '''        }
        '''        .style20
        '''        {
        '''            width: 87px;
        '''        }
        '''        .style21
        '''        {
        '''            width: 144px;
        '''        }
        '''        .style23
        '''        {
        '''            width: 320px;
        '''        }
        '''        .style25
        '''        {
        '''            width: 149px;
        '''        }
        '''        .style26
        '''    [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Crear_Html_Facturas_Pago_Proveedores() As String
            Get
                Return ResourceManager.GetString("Crear_Html_Facturas_Pago_Proveedores", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;html&gt;
        '''&lt;head&gt;
        '''&lt;title&gt;Documento Comercial&lt;/title&gt;
        '''&lt;meta http-equiv=&apos;Content-Type&apos; content=&apos;text/html; charset=iso-8859-1&apos; /&gt;
        '''
        '''&lt;/head&gt;
        '''&lt;body&gt;
        ''' &lt;p&gt;
        ''' &lt;br&gt;
        ''' &lt;/p&gt;
        ''' &lt;table border=&quot;0&quot; cellspacing=&quot;2&quot; cellpadding=&quot;2&quot; summary=&quot;Especificaci&amp;oacute;n del Detalle del Documento &quot; style=&quot;width: 1100px; height: 50px&quot;&gt;
        '''		&lt;tr&gt; 
        '''			&lt;td bgcolor=&quot;#B4C6E7&quot; style = &quot;width: 130px&quot; align=&quot;left&quot;&gt;&lt;b&gt;&lt;font size=4&gt;PROVEEDOR&lt;/font&gt;&lt;/b&gt;&lt;/td&gt; 
        '''			&lt;td bgcolor=&quot;#D9E1F2&quot; style = &quot;width:690px&quot; align=&quot;left&quot;&gt;&lt;b&gt;#Razon_Social#&lt;/b&gt;&lt;/ [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Crear_Html_Facturas_Pago_Proveedores2() As String
            Get
                Return ResourceManager.GetString("Crear_Html_Facturas_Pago_Proveedores2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;tr&gt; 
        '''        &lt;td class=&quot;style31&quot; align=&quot;center&quot;&gt;&lt;b&gt;&lt;font size=4&gt;#Ncc#&lt;/font&gt;&lt;/b&gt;&lt;/td&gt;
        '''        &lt;td class=&quot;style32&quot; align=&quot;center&quot;&gt;&lt;b&gt;&lt;font size=4&gt;#Documento#&lt;/font&gt;&lt;/b&gt;&lt;/td&gt;
        '''        &lt;td class=&quot;style25&quot; align=&quot;center&quot;&gt;&lt;b&gt;&lt;font size=4&gt;#Valor#&lt;/font&gt;&lt;/b&gt;&lt;/td&gt; 
        '''      &lt;/tr&gt;.
        '''</summary>
        Friend Shared ReadOnly Property Enc_Nota_Credito_Inf_Pago_Proveedor() As String
            Get
                Return ResourceManager.GetString("Enc_Nota_Credito_Inf_Pago_Proveedor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 
        '''BEGIN TRY
        ''' DROP TABLE #INFVEN
        ''' END TRY
        ''' BEGIN CATCH
        '''END CATCH
        '''
        '''BEGIN TRY
        ''' DROP TABLE #INFVENR
        ''' END TRY
        ''' BEGIN CATCH
        '''END CATCH
        '''
        '''Declare @Fecha_Inicio Datetime,
        '''        @Fecha_Fin Datetime,
        '''        @Empresa Char(2)
        '''
        '''Select @Fecha_Inicio = &apos;#Fecha_Inicio#&apos;,
        '''        @Fecha_Fin = &apos;#Fecha_Fin#&apos;,
        '''        @Empresa = &apos;#Empresa#&apos;
        '''
        '''SELECT CAST( 0 AS Bit) AS Chk, 
        '''       EDO.IDMAEEDO,VEN.IDMAEVEN, EDO.ENDO,EDO.SUENDO,
        '''	   Isnull((Select top 1 RTEN From MAEEN Where KOEN = EDO.ENDO And SUEN = EDO. [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Informe_Vencimientos_Compras_Anuales() As String
            Get
                Return ResourceManager.GetString("Informe_Vencimientos_Compras_Anuales", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a -- INSERTA DOCUMENTOS DE PAGO PENDIENTES DE LA ENTIDAD
        '''
        '''
        '''INSERT INTO #INFVEN(IDMAEEDO,IDMAEVEN,ENDO,SUENDO,RTEN,RUT,NOKOEN,TIDO,NUDO,FEEMDO,FEVE,DIAS,DIAS_ATRASO,VAVE,VAABVE,SALDO,ESPGVE,SOSPECHA_STOCK,SOSPECHA_DEVOLUCION,FEULVEDO)
        '''SELECT DPCE.IDMAEDPCE AS IDMAEEDO,0 AS IDMAEVEN,DPCE.ENDP AS ENDO,&apos;&apos; AS SUENDO,
        '''       (SELECT TOP 1 RTEN FROM MAEEN WHERE KOEN = DPCE.ENDP) AS RTEN,
        '''       CAST(&apos;&apos; AS Varchar(15)) AS RUT,
        '''       (SELECT TOP 1 NOKOEN FROM MAEEN WHERE KOEN = DPCE.ENDP) AS NOKOEN,DPCE.TIDP A [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Informe_Vencimientos_Pagos_Clientes() As String
            Get
                Return ResourceManager.GetString("Informe_Vencimientos_Pagos_Clientes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 
        '''BEGIN TRY
        ''' DROP TABLE #INFVEN
        ''' END TRY
        ''' BEGIN CATCH
        '''END CATCH
        '''
        '''BEGIN TRY
        ''' DROP TABLE #INFVENR
        ''' END TRY
        ''' BEGIN CATCH
        '''END CATCH
        '''
        '''Declare @Fecha_Inicio Datetime,
        '''        @Fecha_Fin Datetime,
        '''        @Empresa Char(2)
        '''
        '''Select @Fecha_Inicio = &apos;#Fecha_Inicio#&apos;,
        '''        @Fecha_Fin = &apos;#Fecha_Fin#&apos;,
        '''        @Empresa = &apos;#Empresa#&apos;
        '''
        '''SELECT CAST( 0 AS Bit) AS Chk, 
        '''       EDO.IDMAEEDO,VEN.IDMAEVEN, EDO.ENDO,EDO.SUENDO,
        '''       Isnull((Select top 1 RTEN From MAEEN Where KOEN = EDO.ENDO And SUEN = E [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Informe_Vencimientos_Ventas_Anuales() As String
            Get
                Return ResourceManager.GetString("Informe_Vencimientos_Ventas_Anuales", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
