SELECT Top 1
       IDMAEEDO, 
       EMPRESA, 
       TIDO As 'Tipo',
       (SELECT TOP 1 NOTIDO FROM TABTIDO WHERE TABTIDO.TIDO = MAEEDO.TIDO) AS 'Tipo_Documento', 
       NUDO As 'Numero', 
       ENDO As 'CodEntidad', 
       SUENDO As 'SucEntidad', 
       ENDOFI As 'CodEntidadFisica', 
       TIGEDO, 
       SUDO As 'Sucursal_Doc', 
       LUVTDO As 'Cto_Costo', 
       FEEMDO As 'Fecha_Emision', 
       KOFUDO As 'Cod_Funcionario', 
       ESDO As 'Estado_Doc', 
       ESPGDO As 'Estado_Pago', 
       CAPRCO As 'Cant_Total', 
       CAPRAD As 'Cant_Despachada', 
       CAPREX As 'Cant_Desp_Guia', 
       CAPRNC As 'Cant_Nota_Credito', 
       MEARDO As 'Bruto_Neto', 
       MODO As 'Moneda_Doc', 
       TIMODO As 'Tipo_moneda_Doc', 
       TAMODO AS 'Tama_Moneda', 
       NUCTAP, 
       VACTDTNEDO, 
       VACTDTBRDO, 
       NUIVDO As 'Nro_iva', 
       POIVDO As 'Iva_Porc', 
       VAIVDO As 'Iva_Valor', 
       NUIMDO As 'Nro_Ila', 
       VAIMDO As 'Ila_Valor', 
       VANEDO As 'Neto', 
       VABRDO As 'Bruto', 
       POPIDO, 
       VAPIDO, 
       FE01VEDO As 'Fecha_1er_Venc', 
       FEULVEDO As 'Fecha_Ult_Venc', 
       NUVEDO, 
       VAABDO As 'Valor_Abonado', 
       MARCA, 
       FEER As 'Fecha_Retiro', 
       KOTU As 'Cod_Turno', 
       LCLV, 
       convert(nvarchar, convert(datetime, (HORAGRAB*1.0/3600)/24), 108) AS 'Hora_Emision'
       
FROM   MAEEDO
