SELECT TABLE_NAME AS TABLA,
       COLUMN_NAME AS COLUMNA,
       DATA_TYPE AS TIPO_DE_DATO,
       CHARACTER_OCTET_LENGTH AS VALOR_MAXIMO,
       COLUMN_DEFAULT AS VALOR_POR_DEFECTO,
       IS_NULLABLE AS ACEPTA_NULOS,
       ORDINAL_POSITION AS POSISION
             
        FROM INFORMATION_SCHEMA.COLUMNS
Where TABLE_NAME = '#Tabla_Original#'
ORDER BY TABLE_NAME,ORDINAL_POSITION

-- ********************************************************

SELECT TABLE_NAME AS TABLA,
       COLUMN_NAME AS COLUMNA,
       DATA_TYPE AS TIPO_DE_DATO,
       CHARACTER_OCTET_LENGTH AS VALOR_MAXIMO,
       COLUMN_DEFAULT AS VALOR_POR_DEFECTO,
       IS_NULLABLE AS ACEPTA_NULOS,
       ORDINAL_POSITION AS POSISION
             
        FROM INFORMATION_SCHEMA.COLUMNS
Where TABLE_NAME = '#Tabla_Nueva#'
ORDER BY TABLE_NAME,ORDINAL_POSITION

