'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Recursos_Producto
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BkSpecialPrograms.Recursos_Producto", GetType(Recursos_Producto).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 
        '''Declare 
        '''
        '''@TIPR char(3),
        '''@KOPR char(13),
        '''@NOKOPR varchar(50),
        '''@KOPRRA char(6),
        '''@NOKOPRRA varchar(20),
        '''@KOPRTE char(20),
        '''@KOGE char(13),
        '''@NMARCA char(1),
        '''@UD01PR char(2),
        '''@UD02PR char(2),
        '''@RLUD float,
        '''@POIVPR float,
        '''@NUIMPR float,
        '''@RGPR char(1),
        '''@STMIPR float,
        '''@STMAPR float,
        '''@MRPR char(20),
        '''@ATPR char(3),
        '''@RUPR char(3),
        '''@STFI1 float,
        '''@STDV1 float,
        '''@STOCNV1 float,
        '''@STFI2 float,
        '''@STDV2 float,
        '''@STOCNV2 float,
        '''@PPUL01 float,
        '''@PPUL02 float,
        '''@MOUL char(3),
        '''@TIMOUL char(1),
        '''@TAUL fl [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SqlQuery_Crear_Producto() As String
            Get
                Return ResourceManager.GetString("SqlQuery_Crear_Producto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 
        '''Declare 
        '''
        '''@TIPR char(3),
        '''@KOPR char(13),
        '''@NOKOPR varchar(50),
        '''@KOPRRA char(6),
        '''@NOKOPRRA varchar(20),
        '''@KOPRTE char(20),
        '''@KOGE char(13),
        '''@NMARCA char(1),
        '''@UD01PR char(2),
        '''@UD02PR char(2),
        '''@RLUD float,
        '''@POIVPR float,
        '''@NUIMPR float,
        '''@RGPR char(1),
        '''@STMIPR float,
        '''@STMAPR float,
        '''@MRPR char(20),
        '''@ATPR char(3),
        '''@RUPR char(3),
        '''@STFI1 float,
        '''@STDV1 float,
        '''@STOCNV1 float,
        '''@STFI2 float,
        '''@STDV2 float,
        '''@STOCNV2 float,
        '''@PPUL01 float,
        '''@PPUL02 float,
        '''@MOUL char(3),
        '''@TIMOUL char(1),
        '''@TAUL fl [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SqlQuery_Editar_Producto() As String
            Get
                Return ResourceManager.GetString("SqlQuery_Editar_Producto", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
