'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Recursos_Kardex
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BkSpecialPrograms.Recursos_Kardex", GetType(Recursos_Kardex).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE 
        '''@Empresa char(2),
        '''@Codigo char(13),
        '''@ListaPrecio Char(3)
        '''
        '''select @Empresa = &apos;#Empresa#&apos;,@ListaPrecio = &apos;#ListaPrecio#&apos;
        '''
        '''SELECT Top 200
        '''       MP.TIPR,
        '''       MP.KOPR,
        '''       MP.NOKOPR,
        '''       MP.UD01PR,
        '''       MP.UD02PR,
        '''       MP.RLUD,
        '''       Isnull( TP.PP01UD,0) As PP01UD,
        '''       Isnull( TP.PP01UD,0) As PP02UD
        '''  FROM MAEPR MP INNER JOIN MAEPREM 
        '''    ON MAEPREM.KOPR=MP.KOPR 
        '''    AND MAEPREM.EMPRESA=@Empresa  
        '''        LEFT JOIN TABPRE TP 
        '''    ON MP.KOPR=TP.KOPR 
        '''    AND TP.KOLT [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Kardex_por_producto() As String
            Get
                Return ResourceManager.GetString("Kardex_por_producto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE 
        '''@Empresa char(2),
        '''@Codigo char(13),
        '''@ListaPrecio Char(3),
        '''@Kofu Char(3)
        '''
        '''Select @Empresa = &apos;#Empresa#&apos;,@ListaPrecio = &apos;#ListaPrecio#&apos;,@Codigo = &apos;#Codigo#&apos;, @Kofu = &apos;#Kofu#&apos;
        '''
        '''SELECT 
        '''       MST.EMPRESA,
        '''       MST.KOSU,
        '''       MST.KOBO,
        '''       LTRIM(RTRIM(MST.KOSU))+&apos;-&apos;+LTRIM(RTRIM(MST.KOBO)) as SUC_BOD,
        '''       MST.KOPR,
        '''       MST.STFI#Ud#,        -- STOCK FISICO
        '''       MST.STDV#Ud#,        -- STOCK DEVENGADO
        '''       MST.DESPNOFAC#Ud#,   -- DESPACHADO SIN FACTURAR 
        '''       MST.STOCNV [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Kardex_Stock_Productos_por_Suc_Bod() As String
            Get
                Return ResourceManager.GetString("Kardex_Stock_Productos_por_Suc_Bod", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
