SELECT 
       EDO.IDMAEEDO,EDO.TIDO,EDO.NUDO,EDO.ENDO,EDO.SUENDO,EDO.TIGEDO,EDO.SUDO,EDO.LUVTDO,EDO.FEEMDO,
       EDO.KOFUDO,EDO.ESDO,EDO.ESPGDO,EDO.CAPRCO,EDO.CAPRAD,EDO.CAPREX,EDO.CAPRNC,EDO.MEARDO,
       EDO.MODO,EDO.TIMODO,EDO.TAMODO,EDO.NUCTAP,EDO.VACTDTNEDO,EDO.VACTDTBRDO,EDO.NUIVDO,
       EDO.POIVDO,
        CASE WHEN TIDO = 'NCC' THEN EDO.VAIVDO * -1 ELSE EDO.VAIVDO END AS VAIVDO,
	   EDO.NUIMDO,
	   CASE WHEN TIDO = 'NCC' THEN EDO.VAIMDO * -1 ELSE EDO.VAIMDO END AS VAIMDO,
	   CASE WHEN TIDO = 'NCC' THEN EDO.VANEDO * -1 ELSE EDO.VANEDO END AS VANEDO,
	   Cast(0 As Float) As AFECTO,
	   CASE WHEN TIDO = 'NCC' THEN EDO.VABRDO * -1 ELSE EDO.VABRDO END AS VABRDO,
       EDO.POPIDO,EDO.VAPIDO,
	   EDO.FE01VEDO,EDO.FEULVEDO,EDO.NUVEDO,EDO.VAABDO,EDO.MARCA,EDO.FEER,EDO.NUTRANSMI,EDO.TRANSMASI,
	   (SELECT TOP 1 NUMECOM  FROM CCOMPRD1 AS D1 WITH ( NOLOCK ) INNER JOIN CCOMPRD AS D ON D.IDCOMPRD=D1.IDCOMPRD  
	   INNER JOIN CCOMPRE AS E ON E.IDCOMPRE=E.IDCOMPRE  WHERE D1.IDRST=EDO.IDMAEEDO AND D1.ARCHIRST='MAEEDO' ) AS NUCOCO,
	   EDO.KOTU,EDO.LIBRO,EDO.LCLV,EDO.ESFADO,EDO.KOTRPCVH,EDO.NULICO,EDO.PERIODO,EDO.NUDONODEFI,
	   EDO.POIVARET,EDO.VADEIVDO,EDO.VAIVARET,EDO.RESUMEN,EDO.SUBTIDO,EDO.TIDOELEC,
	   (CASE WHEN EDO.TIDOELEC=1 THEN '1' ELSE '0' END ) AS ELECTRO,EN.LVEN,EN.CRSD,EN.CRCH,EN.RTEN,EN.NOKOEN,EDO.FECHATRIB,
			(SELECT SUM(CASE WHEN (DDO.POIVLI=0.0  
					AND DDO.VAIVLI=0.0  
						AND DDO.VANELI>0.0  
							AND DDO.LILG NOT IN ('CR','IM')) THEN DDO.VANELI ELSE 0.0 END)  
			FROM MAEDDO AS DDO WITH (NOLOCK) WHERE EDO.IDMAEEDO=DDO.IDMAEEDO AND EDO.TIDO<>'DIN') AS EXENTO
	   Into #Paso	   
	   FROM MAEEDO AS EDO WITH (NOLOCK)  
			LEFT JOIN MAEEN AS EN ON EDO.ENDO=EN.KOEN AND EDO.SUENDO=EN.SUEN  
	   WHERE 
		(EDO.EMPRESA='#Empresa#'  AND 
		 EDO.LIBRO LIKE '#Libro#%'  AND 
		 (EDO.LCLV IS NULL OR EDO.LCLV = { d '1900-01-01' }) AND 
		  EDO.TIDO IN ('DIN','FCC','FCT','FDC','NCC') AND EDO.NUDONODEFI=0) 
		  #Filtro#


Update #Paso Set AFECTO = VANEDO - EXENTO

Select * From #Paso

Drop Table #Paso

