Select SULIDO,SUCURSAL,Sum(SALDO_Ud1) As SALDO_Ud1,Sum(TOT_SALDOxPRECIO) As TOT_SALDOxPRECIO
From BAKAPP_SA.dbo.Tbl_PasoDPM_Ppr
Group By SULIDO,SUCURSAL
Union 
Select 'ZZZ','TOTAL',Sum(SALDO_Ud1),Sum(TOT_SALDOxPRECIO)
From BAKAPP_SA.dbo.Tbl_PasoDPM_Ppr