Public Class Zw_Casi_DocEnc
    Public Property Id_DocEnc As Integer
    Public Property Modalidad As String
    Public Property Empresa As String
    Public Property Sucursal As String
    Public Property TipoDoc As String
    Public Property NroDocumento As String
    Public Property CodEntidad As String
    Public Property CodSucEntidad As String
    Public Property Nombre_Entidad As String
    Public Property FechaEmision As DateTime?
    Public Property Fecha_1er_Vencimiento As DateTime?
    Public Property FechaUltVencimiento As DateTime?
    Public Property FechaRecepcion As DateTime?
    Public Property Cuotas As Integer
    Public Property Dias_1er_Vencimiento As Integer
    Public Property Dias_Vencimiento As Integer
    Public Property ListaPrecios As String
    Public Property CodEntidadFisica As String
    Public Property CodSucEntidadFisica As String
    Public Property Nombre_Entidad_Fisica As String
    Public Property Contacto_Ent As String
    Public Property CodFuncionario As String
    Public Property NomFuncionario As String
    Public Property Centro_Costo As String
    Public Property Moneda_Doc As String
    Public Property Valor_Dolar As Double
    Public Property TotalNetoDoc As Double
    Public Property TotalIvaDoc As Double
    Public Property TotalIlaDoc As Double
    Public Property TotalBrutoDoc As Double
    Public Property CantTotal As Double
    Public Property CantDesp As Double
    Public Property DocEn_Neto_Bruto As String
    Public Property Es_ValeTransitorio As Boolean
    Public Property Es_Electronico As Boolean
    Public Property TipoMoneda As String
    Public Property Vizado As Boolean
    Public Property Fun_Auto_Deuda_Ven As String
    Public Property Id_DocEnc_Padre As Integer
    Public Property Bloquea_Doc As Boolean
    Public Property Fun_Auto_Stock_Ins As String
    Public Property Fun_Auto_Cupo_Exe As String
    Public Property SubTido As String
    Public Property Fun_Auto_Fecha_Des As String
    Public Property Stand_by As Boolean
    Public Property Fun_Auto_Sol_Compra As String
    Public Property Tasadorig_Doc As Double
    Public Property Reserva_NroOCC As Boolean
    Public Property Reserva_Idmaeedo As Integer
    Public Property Bodega_Destino As String
    Public Property RevFincred As Boolean
    Public Property IdFincred As Integer
    Public Property MontoFincred As Double
End Class
