Public Class Zw_Casi_DocObs
    Public Property Id_DocEnc As Integer
    Public Property Observaciones As String
    Public Property Forma_pago As String
    Public Property Orden_compra As String
    Public Property Obs1 As String
    Public Property Obs2 As String
    Public Property Obs3 As String
    Public Property Obs4 As String
    Public Property Obs5 As String
    Public Property Obs6 As String
    Public Property Obs7 As String
    Public Property Obs8 As String
    Public Property Obs9 As String
    Public Property Obs10 As String
    Public Property Obs11 As String
    Public Property Obs12 As String
    Public Property Obs13 As String
    Public Property Obs14 As String
    Public Property Obs15 As String
    Public Property Obs16 As String
    Public Property Obs17 As String
    Public Property Obs18 As String
    Public Property Obs19 As String
    Public Property Obs20 As String
    Public Property Obs21 As String
    Public Property Obs22 As String
    Public Property Obs23 As String
    Public Property Obs24 As String
    Public Property Obs25 As String
    Public Property Obs26 As String
    Public Property Obs27 As String
    Public Property Obs28 As String
    Public Property Obs29 As String
    Public Property Obs30 As String
    Public Property Obs31 As String
    Public Property Obs32 As String
    Public Property Obs33 As String
    Public Property Obs34 As String
    Public Property Obs35 As String
    Public Property Placa As String
    Public Property CodRetirador As String
End Class
