Public Class Zw_Casi_DocDet
    Public Property Id_DocEnc As Integer
    Public Property Id_DocDet As Integer
    Public Property Empresa As String
    Public Property Sucursal As String
    Public Property Bodega As String
    Public Property UnTrans As Integer
    Public Property Lincondest As Boolean
    Public Property NroLinea As String
    Public Property Codigo As String
    Public Property CodigoProv As String
    Public Property UdTrans As String
    Public Property Cantidad As Double
    Public Property TipoValor As String
    Public Property Precio As Double
    Public Property DescuentoPorc As Double
    Public Property DescuentoValor As Double
    Public Property Descripcion As String
    Public Property PrecioNetoUd As Double
    Public Property PrecioNetoUdLista As Double
    Public Property PrecioBrutoUd As Double
    Public Property PrecioBrutoUdLista As Double
    Public Property Rtu As Double
    Public Property Ud01PR As String
    Public Property CantUd1 As Double
    Public Property CDespUd1 As Double
    Public Property CaprexUd1 As Double
    Public Property CaprncUd1 As Double
    Public Property CodVendedor As String
    Public Property Prct As Boolean
    Public Property Tict As String
    Public Property Tipr As String
    Public Property DsctoNeto As Double
    Public Property DsctoBruto As Double
    Public Property Ud02PR As String
    Public Property CantUd2 As Double
    Public Property CDespUd2 As Double
    Public Property CaprexUd2 As Double
    Public Property CaprncUd12 As Double
    Public Property ValVtaDescMax As Boolean
    Public Property ValVtaStockInf As Boolean
    Public Property CodLista As String
    Public Property DescMaximo As Double
    Public Property NroDscto As Integer
    Public Property NroImpuestos As Integer
    Public Property PorIva As Double
    Public Property PorIla As Double
    Public Property ValIvaLinea As Double
    Public Property ValIlaLinea As Double
    Public Property ValSubNetoLinea As Double
    Public Property ValNetoLinea As Double
    Public Property ValBrutoLinea As Double
    Public Property Costo As Double
    Public Property PmLinea As Double
    Public Property PmSucLinea As Double
    Public Property PmIFRS As Double
    Public Property PrecioNetoRealUd1 As Double
    Public Property PrecioNetoRealUd2 As Double
    Public Property FechaEmision_Linea As DateTime?
    Public Property FechaRecepcion_Linea As DateTime?
    Public Property Idmaeedo_Dori As Integer
    Public Property Idmaeddo_Dori As Integer
    Public Property CantUd1_Dori As Double
    Public Property CantUd2_Dori As Double
    Public Property Estado As String
    Public Property Emprepa As String
    Public Property Tidopa As String
    Public Property NudoPa As String
    Public Property Endopa As String
    Public Property Nulidopa As String
    Public Property SubTotal As Double
    Public Property StockBodega As Double
    Public Property UbicacionBod As String
    Public Property DsctoRealPorc As Double
    Public Property DsctoRealValor As Double
    Public Property DsctoGlobalSuperado As Boolean
    Public Property Tiene_Dscto As Boolean
    Public Property CantidadCalculo As Double
    Public Property Operacion As String
    Public Property Potencia As Double
    Public Property PrecioCalculo As Double
    Public Property OCCGenerada As Boolean
    Public Property Bloqueapr As String
    Public Property Observa As String
    Public Property CodFunAutoriza As String
    Public Property CodPermiso As String
    Public Property Nuevo_Producto As Boolean
    Public Property Solicitado_bodega As Boolean
    Public Property Moneda As String
    Public Property Tipo_Moneda As String
    Public Property Tipo_Cambio As Double
    Public Property Ecuacion As String
    Public Property Stock_desde_WMS As Boolean
    Public Property Total_Costo As Double
    Public Property Margen_Valor As Double
    Public Property Margen_Porc As Double
    Public Property Crear_CPr As Boolean
    Public Property Id_CPr As Integer
    Public Property Proyecto As String
    Public Property Centro_Costo As String
    Public Property Id_Oferta As Integer
    Public Property Es_Padre_Oferta As Boolean
    Public Property Oferta As String
    Public Property Padre_Oferta As Integer
    Public Property Aplica_Oferta As Boolean
    Public Property Hijo_Oferta As Integer
    Public Property Cantidad_Oferta As Double
    Public Property Porcdesc_Oferta As Double
    Public Property Tasadorig As Double
    Public Property FunValida_Compra As String
    Public Property IdDet_Ori As Integer
    Public Property Recargo_Campo As String
    Public Property Recargo_Valor As Double
    Public Property Recargo_Distribuido As Boolean
    Public Property TieneOccPdte As Boolean
    Public Property PrecioListaUd1_Prov As Double
    Public Property PrecioListaUd2_Prov As Double
    Public Property Pesoubic As Double
    Public Property SumaKilos As Double
    Public Property CostoLista As Double
    Public Property Id_OtSvr As Integer
    Public Property Semilla_Svr As Integer
    Public Property Nmarca As String
    Public Property RtuVariable As Boolean
    Public Property Espuntosvta As Boolean
    Public Property ModFechVto As Boolean
    Public Property Condicionado As Boolean
End Class
