Public Class Zw_Inv_FotoInventario
    Public Property Id As Integer
    Public Property IdInventario As Integer
    Public Property Estado As Boolean
    Public Property Empresa As String
    Public Property Sucursal As String
    Public Property Bodega As String
    Public Property Tipr As String
    Public Property Codigo As String
    Public Property CodigoRap As String
    Public Property CodigoTec As String
    Public Property Descripcion As String
    Public Property StFisicoUd1 As Double
    Public Property StFisicoUd2 As Double
    Public Property Cant_Inventariada As Double
    Public Property Dif_Inv_Cantidad As Double
    Public Property Dif_Inv_Costo As Double
    Public Property Costo As Double
    Public Property PPP As Double
    Public Property PUltCompra As Double
    Public Property PLCostoPR As Double
    Public Property Total_Costo_Foto As Double
    Public Property Total_Costo_Inv As Double
    Public Property FechaFoto As DateTime?
    Public Property HoraFoto As DateTime?
    Public Property Recontado As Boolean
    Public Property Cerrado As Boolean
    Public Property Levantado As Boolean
    Public Property Diferencia As String
    Public Property NoInventariar As Boolean
    Public Property IdHojaUltReconteo As Integer
    Public Property SuperFamilia As String
    Public Property Familia As String
    Public Property SubFamilia As String
    Public Property Nom_SuperFamilia As String
    Public Property Nom_Familia As String
    Public Property Nom_SubFamilia As String
    Public Property Marca As String
    Public Property Nom_Marca As String
    Public Property Rubro As String
    Public Property Nom_Rubro As String
    Public Property ClasLibre As String
    Public Property Nom_ClasLibre As String
    Public Property Zona As String
    Public Property Nom_Zona As String

End Class
