DECLARE @Empresa       Char( 2),
        @Codigo        Char(13) 
        
Select @Empresa = '#Empresa#',@Codigo = '#Codigo#'

SELECT TOP #NroDocumentos#
              MAEDDO.IDMAEEDO,
              MAEDDO.ENDO,
              MAEDDO.SUENDO,
              MAEEN.NOKOEN,
              ISNULL(MAEDDO.ENDOFI,'') AS ENDOFI,
              ISNULL((SELECT TOP 1 NOKOEN FROM MAEEN WHERE KOEN = MAEDDO.ENDOFI),'') AS NOMENDOFI,
              MAEDDO.TIDO,
              MAEDDO.NUDO,
			  MAEDDO.SULIDO,
			  MAEDDO.BOSULIDO,
              MAEDDO.FEEMLI,
              MAEDDO.KOPRCT,
			  MAEDDO.NOKOPR,
              CASE MAEDDO.UDTRPR WHEN 1 THEN MAEDDO.UD01PR ELSE MAEDDO.UD02PR END AS UN,
              CASE MAEDDO.UDTRPR WHEN 1 THEN MAEDDO.CAPRCO1 ELSE MAEDDO.CAPRCO2 END AS CANTIDAD,
              MAEDDO.VANELI,
              MAEEDO.MODO,
              CASE MAEDDO.UDTRPR WHEN 1 THEN MAEDDO.PPPRNERE1 ELSE MAEDDO.PPPRNERE2 END AS PRECIOUD,
              MAEDDO.UDTRPR,
              MAEEDO.ENDOFI,
              ISNULL((SELECT TOP 1 E.NOKOEN FROM MAEEN AS E WHERE E.KOEN=MAEEDO.ENDOFI),'') AS NOKOFI  
FROM MAEDDO  WITH ( NOLOCK )  INNER JOIN MAEEDO ON MAEEDO.IDMAEEDO=MAEDDO.IDMAEEDO  
             LEFT JOIN MAEEN ON MAEDDO.ENDO=MAEEN.KOEN AND MAEDDO.SUENDO=MAEEN.SUEN  
WHERE 
      MAEDDO.EMPRESA = @Empresa AND 
      MAEDDO.KOPRCT = @Codigo  AND 
      MAEDDO.FEEMLI < GETDATE() AND 
      MAEDDO.TIDO In #TipoDocumento#
      #Filtro_Entidad#
AND MAEDDO.LILG IN ('SI','GR')  
ORDER BY MAEDDO.FEEMLI DESC 