'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class _24_Recursos
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BkSpecialPrograms.24_Recursos", GetType(_24_Recursos).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE 
        '''
        '''@Empresa   Char(2),
        '''@Sucursal  Char(3),
        '''@Bodega    Char(3),
        '''@Codigo    Char(13),
        '''@Orden     Int,
        '''@StockUd1  Float,
        '''@StockUd2  Float,
        '''@Fecha     Datetime  
        '''
        '''Select @Empresa  = &apos;#Empresa#&apos;,
        '''       @Sucursal = &apos;#Sucursal#&apos;,
        '''       @Bodega   = &apos;#Bodega#&apos;, 
        '''	   @Orden    = #Int#,
        '''	   @Fecha    = &apos;#Fecha#&apos;
        '''	   
        '''--IF EXISTS (SELECT * FROM sysobjects WHERE name=&apos;Zw_TblStockConsolid&apos;) BEGIN
        '''--DROP TABLE Zw_TblStockConsolid
        '''--END
        '''
        '''
        '''SELECT D.KOPRCT,D.EMPRESA,E.TIDO,E.SUBTIDO,D.SULIDO,D. [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Consolidación_de_Stock_por_producto() As String
            Get
                Return ResourceManager.GetString("Consolidación_de_Stock_por_producto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE 
        '''@Empresa char(2),
        '''@Sucursal char(3),
        '''@Bodega char(3),
        '''@Codigo char(13)
        '''
        '''Select @Empresa = &apos;#Empresa#&apos;,@Sucursal = &apos;#Sucursal#&apos;,@Bodega = &apos;#Bodega#&apos;,@Codigo = &apos;#Codigo#&apos;
        '''
        '''
        '''BEGIN TRY
        ''' DROP TABLE #_TblPaso
        ''' END TRY
        ''' BEGIN CATCH
        '''END CATCH
        '''
        '''SELECT #Top#
        '''       MAEEDO.IDMAEEDO,
        '''       MAEEDO.HORAGRAB,
        '''       convert(nvarchar, convert(datetime, (MAEEDO.HORAGRAB*1.0/3600)/24), 108) AS HORA,
        '''       MAEEDO.TIDO,
        '''       MAEEDO.SUBTIDO,
        '''       MAEEDO.NUDO,
        '''       MAEDDO.NULIDO*1 as NULIDO [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Kardex_de_inventario() As String
            Get
                Return ResourceManager.GetString("Kardex_de_inventario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE 
        '''@Empresa char(2),
        '''@Codigo char(13),
        '''@ListaPrecio Char(3)
        '''
        '''Select @Empresa = &apos;#Empresa#&apos;,@ListaPrecio = &apos;#ListaPrecio#&apos;
        '''
        '''SELECT 
        '''       MP.TIPR,
        '''       MP.KOPR,
        '''       MP.NOKOPR,
        '''       MP.UD01PR,
        '''       MP.UD02PR,
        '''       MP.RLUD,
        '''       TP.PP01UD,
        '''       TP.PP02UD
        '''  FROM MAEPR MP INNER JOIN MAEPREM 
        '''    ON MAEPREM.KOPR=MP.KOPR 
        '''    AND MAEPREM.EMPRESA=@Empresa  
        '''        LEFT JOIN TABPRE TP 
        '''    ON MP.KOPR=TP.KOPR 
        '''    AND TP.KOLT=@ListaPrecio   
        '''WHERE  
        '''    MP.ATPR&lt;&gt;&apos;OCU&apos; AND [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Listado_Productos_con_precio() As String
            Get
                Return ResourceManager.GetString("Listado_Productos_con_precio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE 
        '''@Empresa char(2),
        '''@Sucursal char(3),
        '''@Bodega char(3),
        '''@Fecha datetime
        '''
        '''select @Empresa = &apos;#Empresa#&apos;,
        '''       @Sucursal = &apos;#Sucursal#&apos;,
        '''       @Bodega = &apos;#Bodega#&apos;,
        '''       @Fecha = &apos;#Fecha#&apos;
        '''
        '''SELECT 
        ''' SUM(CASE 
        '''       WHEN MAEDDO.CAPRAD1 &lt;&gt; 0 THEN 
        '''           CASE 
        '''             WHEN MAEDDO.TIDO IN (&apos;NCV&apos;) THEN CAPRCO1*-1
        '''             WHEN MAEDDO.TIDO IN (&apos;FCV&apos;,&apos;BLV&apos;,&apos;GDV&apos;) THEN CAPRCO1
        '''             ELSE 0
        '''            END
        '''       WHEN MAEDDO.TIDO IN (&apos;GDV&apos;) THEN 
        '''           CASE 
        ''' [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SQLQuery_01_Mov_Ventas_Diario() As String
            Get
                Return ResourceManager.GetString("SQLQuery_01_Mov_Ventas_Diario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT  Top #CantidadDoc#
        '''        Cast(0 As Bit) As Chk,
        '''        IDMAEEDO,
        '''        Edo.TIDO,
        '''        --ISNULL((SELECT TOP 1 NOTIDO FROM TABTIDO WHERE TIDO = MAEEDO.TIDO),&apos;&apos;) AS &apos;TipoDoc&apos;,
        '''        Isnull(Tid.NOTIDO,&apos;&apos;) As &apos;TipoDoc&apos;,
        '''		NUDO,
        '''        ENDO,
        '''        SUENDO,
        '''        --ISNULL((SELECT TOP 1 NOKOEN FROM MAEEN WHERE KOEN = ENDO AND SUEN = SUENDO ),&apos;&apos;) AS RAZON,
        '''        Isnull(Mae1.NOKOEN,&apos;&apos;) As RAZON,
        '''		ENDOFI,
        '''        #Campo_SUENDOFI#
        '''        --ISNULL((SELECT TOP 1 NOKOEN FROM MAEEN WHE [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SQLQuery_Buscar_Docmuento() As String
            Get
                Return ResourceManager.GetString("SQLQuery_Buscar_Docmuento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE 
        '''@Empresa char(2),
        '''@Sucursal char(3),
        '''@Bodega char(3),
        '''@Fecha datetime
        '''
        '''select @Empresa = &apos;#Empresa#&apos;,
        '''       @Sucursal = &apos;#Sucursal#&apos;,
        '''       @Bodega = &apos;#Bodega#&apos;,
        '''       @Fecha = &apos;#Fecha#&apos;
        '''
        '''SELECT 
        '''  ISNULL(SUM(CASE 
        '''               WHEN MAEDDO.CAPRAD1 &lt;&gt; 0 THEN 
        '''                CASE 
        '''                 WHEN MAEDDO.TIDO IN (&apos;FCC&apos;,&apos;NCV&apos;,&apos;GRI&apos;,&apos;GRC&apos;,&apos;GRD&apos;,&apos;GRP&apos;) THEN CAPRCO1
        '''                 WHEN MAEDDO.TIDO IN (&apos;FCV&apos;,&apos;BLV&apos;,&apos;BSV&apos;,&apos;NCC&apos;,&apos;GDV&apos;,&apos;GDI&apos;,&apos;GDP&apos;,&apos;GDD&apos;,&apos;GTI&apos;) THEN CAPRCO1*-1
        '''    [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SQLQuery_Mov_Stock_Diario() As String
            Get
                Return ResourceManager.GetString("SQLQuery_Mov_Stock_Diario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE 
        '''@Empresa char(2),
        '''@Sucursal char(3),
        '''@Bodega char(3),
        '''@Codigo char(13),
        '''@nWhile int,
        '''@nRegistros int,
        '''@Ul_Id int,
        '''@Stock_Fi float,
        '''@Mes_Ac varchar(20),
        '''@Mes_Ul varchar(20)
        '''
        '''--@Fecha1 date,
        '''--@Fecha2 date
        '''
        '''select @Empresa = &apos;#Empresa#&apos;,@Sucursal = &apos;#Sucursal#&apos;,@Bodega = &apos;#Bodega#&apos;,@Codigo = &apos;#Codigo#&apos;,@Stock_Fi = 0
        '''--@Fecha1 = &apos;20130901&apos;,@Fecha2 = &apos;20140831&apos;
        '''
        '''--drop table _Zw_Paso_Quiebre_Stock 
        '''
        '''CREATE TABLE [dbo].[_Zw_Paso_Quiebre_Stock](
        '''    [Id]                   [int] IDENT [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SQLQuery_Quiebre_Stock() As String
            Get
                Return ResourceManager.GetString("SQLQuery_Quiebre_Stock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE 
        '''@Empresa char(2),
        '''@Codigo char(13),
        '''@ListaPrecio Char(3)
        '''
        '''Select @Empresa = &apos;#Empresa#&apos;,@ListaPrecio = &apos;#ListaPrecio#&apos;,@Codigo = &apos;#Codigo#&apos;
        '''
        '''SELECT 
        '''       MST.EMPRESA,
        '''       MST.KOSU,
        '''       MST.KOBO,
        '''       LTRIM(RTRIM(MST.KOSU))+&apos;-&apos;+LTRIM(RTRIM(MST.KOBO)) as SUC_BOD,
        '''       MST.KOPR,
        '''       MST.STFI#Ud#,        -- STOCK FISICO
        '''       MST.STDV#Ud#,        -- STOCK DEVENGADO
        '''       MST.DESPNOFAC#Ud#,   -- DESPACHADO SIN FACTURAR 
        '''       MST.STOCNV#Ud#,      -- STOCK COMPROMETIDO
        ''' [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Stock_Productos_por_Suc_Bod() As String
            Get
                Return ResourceManager.GetString("Stock_Productos_por_Suc_Bod", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
