DECLARE 
@Codigo char(13)

Set @Codigo = '#Codigo#'


Select KOSU,KOBO,KOSU+KOBO as SucBod,
       (SELECT NOKOBO FROM TABBO WHERE KOSU = MS.KOSU AND KOBO = MS.KOBO) AS BODEGA,
       SUM(STFI1) AS STFI1,SUM(STFI2) AS STFI2,                     -- STOCK FISICO;                              Stock fisico
       SUM(STDV1) AS STDV1,SUM(STDV2) AS STDV2,                     -- STOCK DEVENGADO, FACTURADO SIN DESPACHAR;  Devengado
       SUM(DESPNOFAC1) AS DESPNOFAC1,SUM(DESPNOFAC2) AS DESPNOFAC2, -- STOCK DESPACHADO SIN FACTURA DE VENTA;     Desp. S/Fact
       SUM(STOCNV1) AS STOCNV1,SUM(STOCNV2) AS STOCNV2,             -- STOCK COMPROMETIDO NVV, NVI;               Compromet.          
       SUM(STDV1C) AS STDV1C,SUM(STDV2C) AS STDV2C,                 -- STOCK FACTURADO EN COMPRA NO RECEPCIONADO; Comp.N/Rec
	   SUM(RECENOFAC1) AS RECENOFAC1,SUM(RECENOFAC2) AS RECENOFAC2, -- STOCK RECEPCIONADO SIN FACTURA DE COMPRA;  Rece.s/Fac
       SUM(STOCNV1C) AS STOCNV1C,SUM(STOCNV2C) AS STOCNV2C          -- ORDENES DE COMPRA PENDIENTE;               Pedido  
       from MAEST AS MS where KOPR = @Codigo
       GROUP BY KOSU,KOBO