DECLARE 
@Codigo char(13),
@IdOCC int,
@IdFCC int,
@IdGRC int

Set @Codigo = '#Codigo#'

-- MUESTRA LOS ULTIMOS MOVIMIENTOS DEL PRODUCTO.
      
   Set @IdFCC = (Select TOP 1 IDMAEEDO FROM MAEDDO WHERE KOPRCT = @Codigo AND TIDO = 'FCC' ORDER BY FEEMLI DESC)
   Set @IdOCC = (Select TOP 1 IDMAEEDO FROM MAEDDO WHERE KOPRCT = @Codigo AND TIDO = 'OCC' ORDER BY FEEMLI DESC)
   Set @IdGRC = (Select TOP 1 IDMAEEDO FROM MAEDDO WHERE KOPRCT = @Codigo AND TIDO = 'GRC' ORDER BY FEEMLI DESC)

  SELECT TOP 1 'Orden de Compra' as 'Documento', TIDO+'-'+NUDO AS Doc,FEEMLI as Fecha,
                ENDO,SUENDO,ISNULL((SELECT TOP 1 NOKOEN FROM MAEEN WHERE KOEN = MD.ENDO AND SUEN = MD.SUENDO),'') AS NOKOEN, 
                CASE UDTRPR WHEN 1 THEN UD01PR ELSE UD02PR END AS 'UD',
                CASE UDTRPR WHEN 1 THEN CAPRCO1 ELSE CAPRCO2 END AS 'CANTIDAD',
                VANELI,VAIVLI,VABRLI
                FROM MAEDDO AS MD
                WHERE IDMAEEDO = @IdOCC
  union
  SELECT TOP 1 'Guía de Recepción' as 'Documento',TIDO+'-'+NUDO AS Doc,FEEMLI as Fecha,
                ENDO,SUENDO,ISNULL((SELECT TOP 1 NOKOEN FROM MAEEN WHERE KOEN = MD.ENDO AND SUEN = MD.SUENDO),'') AS NOKOEN, 
                CASE UDTRPR WHEN 1 THEN UD01PR ELSE UD02PR END AS 'UD',
                CASE UDTRPR WHEN 1 THEN CAPRCO1 ELSE CAPRCO2 END AS 'CANTIDAD',
                VANELI,VAIVLI,VABRLI
                FROM MAEDDO AS MD
                WHERE IDMAEEDO = @IdGRC
  UNION
  SELECT TOP 1 'Factura de compra' as 'Documento',TIDO+'-'+NUDO AS Doc,FEEMLI as Fecha,
               ENDO,SUENDO,ISNULL((SELECT TOP 1 NOKOEN FROM MAEEN WHERE KOEN = MD.ENDO AND SUEN = MD.SUENDO),'') AS NOKOEN, 
               CASE UDTRPR WHEN 1 THEN UD01PR ELSE UD02PR END AS 'UD',
               CASE UDTRPR WHEN 1 THEN CAPRCO1 ELSE CAPRCO2 END AS 'CANTIDAD',
               VANELI,VAIVLI,VABRLI
               FROM MAEDDO AS MD
               WHERE IDMAEEDO = @IdFCC
			   
			   
			   