

SELECT PDATFAD.*,Cast(0 As Bit) As En_Proceso,
      Cast(FLOOR(HORAINI) AS Float) as Hh_Ini,
	  Cast(ROUND(HORAINI- floor(HORAINI),2)*100 AS Float) as Mi_Ini,
	  Cast(FLOOR(HORATER) AS Float) as Hh_Ter,
	  Cast(ROUND(HORATER- floor(HORATER),2)*100 AS Float) as Mi_Ter,
      convert(Float,DATEPART (HH,Getdate()))+(convert(Float,DATEPART (MI,Getdate()))/100) As Hora_Actual,Cast(0 As Float) As Tiempo_Actual,
POBREFAD.OBRERO,Cast('' AS Varchar(50)) AS NOMBREOB,POBREFAD.TIEMPOOB,UDADOP=POPER.UDAD,POPER.OPERACION AS COD_OP,POPER.NOMBREOP,POPER.TIPOOP,
PMAQUI.CODMAQ AS COD_MAQ,PMAQUI.NOMBREMAQ,POTL.IDPOTL,POTL.FABRICAR,MAEPR.NOKOPR,
       POTE.MODO,POTE.TAMODO  
Into #Paso1
FROM PDATFAD WITH ( NOLOCK ) 
	LEFT OUTER JOIN POPER ON PDATFAD.OPERACION=POPER.OPERACION 
		LEFT OUTER JOIN PMAQUI ON PDATFAD.CODMAQ=PMAQUI.CODMAQ 
			LEFT OUTER JOIN POTL ON PDATFAD.NUMOT=POTL.NUMOT AND PDATFAD.NREGOTL = POTL.NREG 
				LEFT OUTER JOIN POTE ON PDATFAD.NUMOT=POTE.NUMOT 
					LEFT OUTER JOIN MAEPR ON PDATFAD.CODIGO=MAEPR.KOPR 
						LEFT OUTER JOIN POBREFAD ON PDATFAD.IDPDATFAD=POBREFAD.IDPDATFAD 
	WHERE 1 > 0
	--PDATFAD.FECHINI >= {d '2018-08-01'} AND PDATFAD.FECHTER <= Getdate()  
	--And POTE.NUMOT IN ('0000025917') --
	ORDER BY POTE.NUMOT,PDATFAD.FECHINI, PDATFAD.CODMAQ, PDATFAD.HORAINI 

Update #Paso1 Set Tiempo_Actual = Hora_Actual-HORAINI
Where REALJOR = 0

Update #Paso1 Set NOMBREOB = Isnull((Select Top 1 NOMBREOB From PMAEOB Where OBRERO = CODIGOOB),'')

Update #Paso1 Set En_Proceso = (Select Top 1 REQCONFIR From PDATFAE Z2 Where Z1.IDPDATFAE = Z2.IDPDATFAE) From #Paso1 Z1
Update #Paso1 Set FECHINI = DATEADD(HH,Hh_Ini,FECHINI)
Update #Paso1 Set FECHINI = DATEADD(MI,Mi_Ini,FECHINI)
Update #Paso1 Set FECHTER = DATEADD(HH,Hh_Ter,FECHTER)
Update #Paso1 Set FECHTER = DATEADD(MI,Mi_Ter,FECHTER)

Select --NUMOT,NUMDF,NREGOTL, 
       Case When En_Proceso = 1 Then 'En Proceso' else '' end As 'Estado',
	   CASE WHEN En_Proceso = 1 THEN DATEDIFF(DD,FECHINI,GETDATE()) ELSE DATEDIFF(DD,FECHINI,FECHTER) END  AS 'Dif_Dias',
       cast(CASE WHEN En_Proceso = 1 THEN GETDATE() - FECHINI ELSE FECHTER - FECHINI END as Time) As 'Dif_Hora',
	   --FECHINI,FECHTER,
	   GETDATE() AS FECHA_ACTUAL, 
       --HORAINI,HORATER,Hora_Actual,
	   --Round(Tiempo_Actual,2) As Tiempo_Actual,
	   --TIEMPOOB,
	   --Tiempo_Actual,
	   --REALJOR, 
	   *
	   Into #Paso2
	    From #Paso1
	   --WHERE NUMOT > '0000000041'
	   --And NREGOTL = '00004'
	   Order by NUMOT,NREGOTL
	      --Where En_Proceso = 1

		  --25917 , 25437
--Select  * From #Paso2

-- INFORME    MAQUINAS
--/*
Select CODMAQ,NOMBREMAQ,NUMOT,OPERACION,NOMBREOP,OBRERO,NOMBREOB,Estado,FECHINI,FECHA_ACTUAL,Dif_Dias,Dif_Hora,FABRICAR,REALJOR,CODIGO,NOKOPR,NREGOTL 
FROM #Paso2

/*
-- INFORME POR OPERARIOS
Select OBRERO,NOMBREOB,NUMOT,CODMAQ,NOMBREMAQ,OPERACION,NOMBREOP,Estado,FECHINI,FECHA_ACTUAL,Dif_Dias,Dif_Hora,FABRICAR,REALJOR,CODIGO,NOKOPR,NREGOTL   
FROM #Paso2
*/

Drop Table #Paso1
Drop Table #Paso2


/*

SELECT GETDATE(),
       CAST(Getdate() as Time) As La_Hora,
	   convert(Float,DATEPART (HH,Getdate())) AS HORA,
       convert(Float,DATEPART (MM,Getdate())) AS MINUTOS,
	   convert(Float,DATEPART (HH,Getdate()))+(convert(Float,DATEPART (MM,Getdate()))/100) As Hora_Actual,Cast(0 As Float) As  Tiempo_Actual
*/


