DECLARE 

@Fecha_Inicio Date    = '#Fecha_Inicio#', 
@Fecha_Fin    Date    = '#Fecha_Fin#'
 

UPDATE #Tabla_Paso# SET FMPR = '',PFPR = '',HFPR = '',MRPR = '',CLALIBPR = '',RUPR = '',ZOPR = '',SUPER_FAMILIA = '',
                        FAMILIA = '',SUB_FAMILIA = '',MARCA = '',RUBRO_PR = '',CLAS_LIBRE = '',ZONA_PR = '',
						RUEN = '',ZOEN = '',ACTIEN = '',TIPOEN = '',TAMAEN = '',RUBRO_EN = '',ZONA_EN = '', 
						ACTIVIDAD_ECONOMICA = '',TIPO_ENTIDAD = '',TAMANO_EMPRESA = '',
						BODEGA = '',VENDEDOR = '',FUNCIONARIO = ''

WHERE FEEMDO BETWEEN @Fecha_Inicio AND @Fecha_Fin

-- ACTUALIZACION CLASIFICACIONES DE PRODUCTOS

UPDATE #Tabla_Paso# SET 
FMPR = ISNULL((SELECT FMPR FROM MAEPR WITH (NOLOCK) WHERE KOPR=KOPRCT),''), 
PFPR = ISNULL((SELECT PFPR FROM MAEPR WITH (NOLOCK) WHERE KOPR=KOPRCT),''), 
HFPR = ISNULL((SELECT HFPR FROM MAEPR WITH (NOLOCK) WHERE KOPR=KOPRCT),''), 
MRPR = ISNULL((SELECT MRPR FROM MAEPR WITH (NOLOCK) WHERE KOPR=KOPRCT),''), 
CLALIBPR = ISNULL((SELECT CLALIBPR FROM MAEPR WITH (NOLOCK) WHERE KOPR=KOPRCT),''), 
RUPR = ISNULL((SELECT RUPR FROM MAEPR WITH (NOLOCK) WHERE KOPR=KOPRCT),''), 
ZOPR = ISNULL((SELECT ZONAPR FROM MAEPR WITH (NOLOCK) WHERE KOPR=KOPRCT),''), 

-- ACTUALIZACION CLASIFICACIONES DE ENTIDADES
KOFUEN = (SELECT KOFUEN FROM MAEEN Me WITH (NOLOCK) WHERE #Tabla_Paso#.ENDO+SUENDO = Me.KOEN+SUEN),
VENDEDOR_ASIGNADO = ISNULL((SELECT TOP 1 NOKOFU FROM TABFU WHERE KOFU = KOFUEN),''),
RUEN = ISNULL((SELECT RUEN FROM MAEEN Me WITH (NOLOCK) WHERE #Tabla_Paso#.ENDO+SUENDO = Me.KOEN+SUEN),''),
ZOEN = ISNULL((SELECT ZOEN FROM MAEEN Me WITH (NOLOCK) WHERE #Tabla_Paso#.ENDO+SUENDO = Me.KOEN+SUEN),''),
ACTIEN = ISNULL((SELECT ACTIEN FROM MAEEN Me WITH (NOLOCK) WHERE #Tabla_Paso#.ENDO+SUENDO = Me.KOEN+SUEN),''),
TIPOEN = ISNULL((SELECT TIPOEN FROM MAEEN Me WITH (NOLOCK) WHERE #Tabla_Paso#.ENDO+SUENDO = Me.KOEN+SUEN),''),
TAMAEN = ISNULL((SELECT TAMAEN FROM MAEEN Me WITH (NOLOCK) WHERE #Tabla_Paso#.ENDO+SUENDO = Me.KOEN+SUEN),''),

BODEGA = ISNULL((SELECT TOP 1 NOKOBO FROM TABBO Tb WHERE Tb.EMPRESA = #Tabla_Paso#.EMPRESA And Tb.KOSU = SULIDO And Tb.KOBO = BOSULIDO ),''),
VENDEDOR = ISNULL((SELECT TOP 1 NOKOFU FROM TABFU WHERE KOFU = KOFULIDO),''),
FUNCIONARIO = ISNULL((SELECT TOP 1 NOKOFU FROM TABFU WHERE KOFU = KOFUDO),'')

WHERE FEEMDO BETWEEN @Fecha_Inicio AND @Fecha_Fin

--ACTIEN = (SELECT ACTIEN FROM MAEEN Me WITH (NOLOCK) WHERE #Tabla_Paso#.ENDO+SUENDO = Me.KOEN+SUEN),

UPDATE #Tabla_Paso# SET 
SUPER_FAMILIA = ISNULL((SELECT TOP 1 NOKOFM FROM TABFM Tf WHERE Tf.KOFM = #Tabla_Paso#.FMPR),'Sin Super Famila'),
FAMILIA = ISNULL((SELECT TOP 1 NOKOPF FROM TABPF Pf WHERE Pf.KOFM = #Tabla_Paso#.FMPR And Pf.KOPF = #Tabla_Paso#.PFPR ),'Sin Famila'),
SUB_FAMILIA = ISNULL((SELECT TOP 1 NOKOHF FROM TABHF Hf WHERE Hf.KOFM = #Tabla_Paso#.FMPR And Hf.KOPF = #Tabla_Paso#.PFPR And Hf.KOHF = #Tabla_Paso#.HFPR ),'Sin Sub-Famila'),                                                   
MARCA = ISNULL((SELECT TOP 1 NOKOMR FROM TABMR Tm WHERE Tm.KOMR = #Tabla_Paso#.MRPR),'Sin Marca'),
RUBRO_PR = ISNULL((SELECT TOP 1 NOKORU FROM TABRU Tr WHERE Tr.KORU = #Tabla_Paso#.RUPR),'Sin Rubro'),
CLAS_LIBRE = ISNULL((SELECT TOP 1 NOKOCARAC FROM TABCARAC Tr WHERE Tr.KOTABLA = 'CLALIBPR' AND Tr.KOCARAC = #Tabla_Paso#.CLALIBPR),'Sin Clasificación'),
ZONA_PR = ISNULL((SELECT TOP 1 NOKOZO FROM TABZO Tr WHERE Tr.KOZO = #Tabla_Paso#.ZOPR),'Sin Zona'), 

RUBRO_EN = ISNULL((SELECT TOP 1 NOKORU FROM TABRU Tr WHERE Tr.KORU = #Tabla_Paso#.RUEN),'Sin Rubro'),
ZONA_EN = ISNULL((SELECT TOP 1 NOKOZO FROM TABZO Tr WHERE Tr.KOZO = #Tabla_Paso#.ZOEN),'Sin Zona'), 

ACTIVIDAD_ECONOMICA = ISNULL((SELECT TOP 1 NOKOCARAC 
	FROM TABCARAC Tr WHERE Tr.KOTABLA = 'ACTIVIDADE' AND Tr.KOCARAC = #Tabla_Paso#.ACTIEN),'Sin Activadad Economica'),
TIPO_ENTIDAD = ISNULL((SELECT TOP 1 NOKOCARAC 
	FROM TABCARAC Tr WHERE Tr.KOTABLA = 'TIPOENTIDA' AND Tr.KOCARAC = #Tabla_Paso#.TIPOEN),'Sin Tipo Entidad'),
TAMANO_EMPRESA = ISNULL((SELECT TOP 1 NOKOCARAC 
	FROM TABCARAC Tr WHERE Tr.KOTABLA = 'TAMA¥OEMPR' AND Tr.KOCARAC = #Tabla_Paso#.CLALIBPR),'Sin Tamaño Empresa')

WHERE FEEMDO BETWEEN @Fecha_Inicio AND @Fecha_Fin	





