
 /*
DECLARE 

@Fecha_Inicio Date    = '#Fecha_Inicio#', 
@Fecha_Fin    Date    = '#Fecha_Fin#',
@Empresa      Char(2) = '#Empresa#' 
 

BEGIN TRY
 DROP TABLE #INFVEN
 END TRY
 BEGIN CATCH
END CATCH

BEGIN TRY
 DROP TABLE #Tabla_Paso#
 END TRY
 BEGIN CATCH
END CATCH

BEGIN TRY
 DROP TABLE #Paso
 END TRY
 BEGIN CATCH
END CATCH
*/

/*
SELECT IDMAEDDO  Into #Paso From MAEDDO WHERE IDMAEDDO IN
(
Select IDMAEDDO From MAEDDO
WHERE 1 > 0 

AND EMPRESA= @Empresa 
AND TIDO IN ('BLV','BLX','BSV','ESC','FCV','FDB','FDV','FDX','FDZ','FEE','FEV','FVL','FVT','FVX',
	  			   'FVZ','FXV','FYV','NCE','NCV','NCX','NCZ','NEV','RIN') 
AND FEEMLI BETWEEN @Fecha_Inicio AND @Fecha_Fin  
AND IDMAEEDO IN (SELECT IDMAEEDO FROM MAEEDO WHERE NUDONODEFI=0 AND ESDO<>'N')   
--AND IDMAEEDO Not In (Select IDMAEEDO From #Tabla_Paso#)  
#Filtro_Externo#
)
*/



SELECT  EDO.IDMAEEDO, 
        DDO.IDMAEDDO, 
        DDO.EMPRESA,
        EDO.TIDO, 
        EDO.NUDO, 
        Isnull(EN.RTEN,'') As RTEN,
        CAST('' AS VARCHAR(15)) AS RUT,
        EDO.ENDO,
        EDO.SUENDO,
        Isnull((SELECT TOP 1 NOKOEN FROM MAEEN WHERE KOEN = EDO.ENDO AND SUEN = EDO.SUENDO),'???') AS RAZON,
        CAST('' AS CHAR(3)) AS KOFUEN,
        CAST('' AS VARCHAR(50)) AS VENDEDOR_ASIGNADO,
        Isnull(EN.RUEN,'') As RUEN,
		CAST('' AS VARCHAR(50)) AS RUBRO_EN,
        Isnull(EN.ZOEN,'') As ZOEN,
        CAST('' AS VARCHAR(50)) AS ZONA_EN,
        Isnull(EN.ACTIEN,'') As ACTIEN,
        CAST('' AS VARCHAR(50)) AS ACTIVIDAD_ECONOMICA,
        Isnull(EN.TIPOEN,'') As TIPOEN,
        CAST('' AS VARCHAR(50)) AS TIPO_ENTIDAD,
        Isnull(EN.TAMAEN,'') As TAMAEN,
        CAST('' AS VARCHAR(50)) AS TAMANO_EMPRESA,
        Isnull(EN.TRANSPOEN,'') As TRANSPOEN,
        CAST('' AS VARCHAR(50)) AS TRANSPORTISTA,
        Isnull(EN.DIEN,'') As DIEN,
	    Isnull(EN.CIEN,'') As CIEN,
	    Isnull(CIUDAD.NOKOCI,'') As CIUDAD,
	    Isnull(EN.CMEN,'') As CMEN,
	    Isnull(COMUNA.NOKOCM,'') AS COMUNA, 
        EDO.SUDO,
        TABSU.NOKOSU AS SUCURSAL,
        DATENAME(MONTH,DDO.FEEMLI)+'.'+DATENAME(YEAR,DDO.FEEMLI) AS Mes_Ano,
        DATENAME(WEEKDAY,DDO.FEEMLI) AS Dia_Palabra,
        DATENAME(MONTH,DDO.FEEMLI) AS Mes_Palabra,
        DAY(DDO.FEEMLI) As Dia,
        MONTH(DDO.FEEMLI) As Mes,
        YEAR(DDO.FEEMLI) As Ano,
        EDO.FEEMDO, 
        EDO.FEULVEDO, 
        EDO.KOFUDO, 
        CAST('' AS VARCHAR) AS 'FUNCIONARIO',
        EDO.MODO, 
        EDO.TIMODO, 
		EDO.TAMODO,
		EDO.CAPRAD, 
		EDO.CAPREX,
		EDO.VANEDO, 
		EDO.VAIVDO, 
		EDO.VABRDO,
		DDO.LILG, 
		DDO.NULIDO, 
		DDO.SULIDO, 
		DDO.LUVTLIDO, 
		DDO.BOSULIDO, 
		CAST('' AS VARCHAR (50)) AS BODEGA,
		DDO.KOFULIDO, 
		CAST('' AS VARCHAR) AS 'VENDEDOR',
		COALESCE(DDO.PRCT,0) AS PRCT, 
		DDO.TICT, 
		DDO.TIPR, 
		DDO.NUSEPR, 
		DDO.KOPRCT, 
		DDO.NOKOPR,
		CASE
                   WHEN DDO.UDTRPR = 1 THEN
                        DDO.UD01PR
                   ELSE DDO.UD02PR
        END AS UD,
		DDO.UDTRPR, 
		DDO.RLUDPR,
		CASE  
			WHEN DDO.PRCT = 1 THEN 0  
			WHEN EDO.TIDO IN ('GDV','GDP','GDD','GRC','GRP','GRI') AND DDO.PRCT = 0 THEN DDO.CAPRCO1-DDO.CAPREX1  
			WHEN EDO.TIDO IN ('NCV','NCC','NCX','NEV') AND DDO.PRCT = 0             THEN DDO.CAPRCO1*(-1)         
			ELSE DDO.CAPRCO1 
		END AS CAPRCO1,
			DDO.CAPRAD1, 
			DDO.CAPREX1, 
			DDO.CAPRNC1, 
			DDO.UD01PR,
		CASE  
			WHEN DDO.PRCT = 1 THEN 0  
			WHEN EDO.TIDO IN ('GDV','GDP','GDD','GRC','GRP','GRI') AND DDO.PRCT = 0 THEN DDO.CAPRCO2-DDO.CAPREX2  
			WHEN EDO.TIDO IN ('NCV','NCC','NCX','NEV') AND DDO.PRCT = 0             THEN DDO.CAPRCO2*(-1)         
			ELSE DDO.CAPRCO2 
		END AS CAPRCO2,
		DDO.CAPRAD2, DDO.CAPREX2, DDO.CAPRNC2, DDO.UD02PR,DDO.PPPRNE, DDO.PPPRBR, 
		DDO.VANELI,
		DDO.VAIVLI,
		DDO.VAIMLI, 
		DDO.VABRLI, 
		DDO.FEEMLI, 
		DDO.FEERLI, 
		DDO.PPPRPM, 
		Isnull((SELECT TOP 1 PM FROM MAEPREM WHERE EMPRESA = DDO.EMPRESA AND KOPR = DDO.KOPRCT),0) AS PM,
		DDO.PPPRPMIFRS, 
		DDO.POTENCIA,
		DDO.ESLIDO, 
		DDO.PPPRNERE1, 
		DDO.PPPRNERE2,
		COALESCE(TABCT.RECAPRRE,0) AS RECAPRRE,
		CASE DDO.PRCT WHEN 1 THEN '_ct_' ELSE COALESCE(PR.FMPR,'') END AS FMPR,
		--PR.FMPR,
	    CAST('' AS VARCHAR(50)) AS SUPER_FAMILIA,
	    Isnull(PR.PFPR,'') As PFPR,
	    CAST('' AS VARCHAR(50)) AS FAMILIA,
	    Isnull(PR.HFPR,'') As HFPR,
	    CAST('' AS VARCHAR(50)) AS SUB_FAMILIA,
	    Isnull(PR.MRPR,'') As MRPR,
	    CAST('' AS VARCHAR(50)) AS MARCA,
	    Isnull(PR.RUPR,'') As RUPR,
	    CAST('' AS VARCHAR(50)) AS RUBRO_PR,
	    Isnull(PR.CLALIBPR,'') As CLALIBPR,
	    CAST('' AS VARCHAR(200)) AS CLAS_LIBRE,
	    Isnull(PR.ZONAPR,'') AS 'ZOPR',
	    CAST('' AS VARCHAR(50)) AS ZONA_PR,
		ROUND((DDO.PPPRPM * DDO.CAPRCO1) * 
			( CASE 
				WHEN EDO.TIDO IN ('NCV','NCX','NEV','NCC') THEN -1.0 
				ELSE 1.0 
			END ),2) AS COSTO,
		CASE  
			WHEN EDO.TIMODO='E' THEN DDO.VANELI*EDO.TAMODO* ( 
								CASE 
									WHEN EDO.TIDO IN ('NCV','NCX','NEV','NCC') THEN -1.0 
									ELSE 1.0 
								END )  
			ELSE DDO.VANELI * ( CASE 
									WHEN EDO.TIDO IN ('NCV','NCX','NEV','NCC') THEN -1.0 
									ELSE 1.0 
								END )  
		END AS MONTO,
		Isnull(OBDO.OCDO,'') As OCDO 

INTO #Tabla_Paso#

FROM MAEEDO EDO WITH ( NOLOCK ) 
	LEFT JOIN MAEDDO AS DDO WITH (NOLOCK) ON 
		EDO.IDMAEEDO=DDO.IDMAEEDO AND DDO.LILG NOT IN ('GR','IM')  
			LEFT JOIN MAEEDOOB AS OBDO WITH (NOLOCK) ON 
				EDO.IDMAEEDO=OBDO.IDMAEEDO  
					LEFT JOIN MAEPR PR WITH (NOLOCK) ON 
						 PR.KOPR=DDO.KOPRCT  
							LEFT JOIN MAEEN WITH (NOLOCK) ON 
								MAEEN.KOEN=EDO.ENDO AND 
									MAEEN.SUEN=EDO.SUENDO  
										LEFT JOIN TABCT WITH (NOLOCK) ON 
											DDO.KOPRCT=TABCT.KOCT AND DDO.PRCT=1  
												LEFT JOIN TABSU WITH ( NOLOCK ) ON 
													TABSU.KOSU=EDO.SUDO
										   			   LEFT JOIN MAEEN EN WITH ( NOLOCK ) ON 
						                                 EDO.ENDO = EN.KOEN AND EDO.SUENDO = EN.SUEN
						                                   LEFT JOIN TABCI CIUDAD  WITH ( NOLOCK ) ON 
													         CIUDAD.KOPA=EN.PAEN AND 
													          CIUDAD.KOCI=EN.CIEN  
														         LEFT JOIN TABCM COMUNA  WITH ( NOLOCK ) ON 
														           COMUNA.KOPA=EN.PAEN AND 
														           COMUNA.KOCI=EN.CIEN AND 
														           COMUNA.KOCM=EN.CMEN  
--WHERE  DDO.IDMAEDDO IN (SELECT IDMAEDDO FROM #Paso)
WHERE  DDO.IDMAEEDO IN (#Idmaeedo#)
ORDER BY EDO.IDMAEEDO 
	
--CREATE UNIQUE INDEX Ix_#Tabla_Paso#_01 ON #Tabla_Paso# (IDMAEDDO)

/*

UPDATE #Tabla_Paso# SET BODEGA = ISNULL((SELECT TOP 1 NOKOBO FROM TABBO Tb WHERE Tb.EMPRESA = #INFVEN.EMPRESA And Tb.KOSU = SULIDO And Tb.KOBO = BOSULIDO ),'')
UPDATE #Tabla_Paso# SET VENDEDOR = ISNULL((SELECT TOP 1 NOKOFU FROM TABFU WHERE KOFU = KOFULIDO),'')
UPDATE #Tabla_Paso# SET FUNCIONARIO = ISNULL((SELECT TOP 1 NOKOFU FROM TABFU WHERE KOFU = KOFUDO),'')

Update #Tabla_Paso# Set VANELI = VANELI * -1,
                   VAIVLI = VAIVLI * -1,  
                   VAIMLI = VAIMLI * -1,
                   VABRLI = VABRLI * -1
Where TIDO In ('NCV','NCX','NEV','NCZ')  

--Select * Into #Tabla_Paso# From #INFVEN
--Select * Into #Tabla_Paso#_02 From #INFVEN




CREATE INDEX Ix_#Tabla_Paso#_02 ON #Tabla_Paso# (ENDO,SUENDO)
CREATE INDEX Ix_#Tabla_Paso#_03 ON #Tabla_Paso# (KOPRCT)
CREATE INDEX Ix_#Tabla_Paso#_04 ON #Tabla_Paso# (SULIDO,BOSULIDO)
CREATE INDEX Ix_#Tabla_Paso#_05 ON #Tabla_Paso# (KOFUDO)
CREATE INDEX Ix_#Tabla_Paso#_06 ON #Tabla_Paso# (KOFULIDO)
CREATE INDEX Ix_#Tabla_Paso#_07 ON #Tabla_Paso# (IDMAEEDO)
CREATE INDEX Ix_#Tabla_Paso#_08 ON #Tabla_Paso# (FEEMLI)
CREATE INDEX Ix_#Tabla_Paso#_09 ON #Tabla_Paso# (FMPR)
CREATE INDEX Ix_#Tabla_Paso#_10 ON #Tabla_Paso# (FMPR,PFPR)
CREATE INDEX Ix_#Tabla_Paso#_11 ON #Tabla_Paso# (FMPR,PFPR,HFPR)
CREATE INDEX Ix_#Tabla_Paso#_12 ON #Tabla_Paso# (MRPR)
CREATE INDEX Ix_#Tabla_Paso#_13 ON #Tabla_Paso# (RUPR)
CREATE INDEX Ix_#Tabla_Paso#_14 ON #Tabla_Paso# (ZOPR)
CREATE INDEX Ix_#Tabla_Paso#_15 ON #Tabla_Paso# (CLALIBPR)
CREATE INDEX Ix_#Tabla_Paso#_16 ON #Tabla_Paso# (KOFUEN)
CREATE INDEX Ix_#Tabla_Paso#_17 ON #Tabla_Paso# (ACTIEN)
CREATE INDEX Ix_#Tabla_Paso#_18 ON #Tabla_Paso# (TIPOEN)
CREATE INDEX Ix_#Tabla_Paso#_19 ON #Tabla_Paso# (TAMAEN)
CREATE INDEX Ix_#Tabla_Paso#_20 ON #Tabla_Paso# (KOFUEN)
CREATE INDEX Ix_#Tabla_Paso#_21 ON #Tabla_Paso# (ZOEN)
CREATE INDEX Ix_#Tabla_Paso#_22 ON #Tabla_Paso# (RUEN)

UPDATE #Tabla_Paso# SET FMPR = '',PFPR = '',HFPR = '',MRPR = '',CLALIBPR = '',RUPR = '',ZOPR = '',SUPER_FAMILIA = '',
                         FAMILIA = '',SUB_FAMILIA = '',MARCA = '',RUBRO_PR = '',CLAS_LIBRE = '',ZONA_PR = '',
						 RUEN = '',ZOEN = '',ACTIEN = '',TIPOEN = '',TAMAEN = '',RUBRO_EN = '',ZONA_EN = '', 
						 ACTIVIDAD_ECONOMICA = '',TIPO_ENTIDAD = '',TAMANO_EMPRESA = '',
						 BODEGA = '',VENDEDOR = '',FUNCIONARIO = ''

WHERE FEEMDO BETWEEN @Fecha_Inicio AND @Fecha_Fin


-- ACTUALIZACION CLASIFICACIONES DE PRODUCTOS

UPDATE #Tabla_Paso# SET 
FMPR = (SELECT FMPR FROM MAEPR WITH (NOLOCK) WHERE KOPR=KOPRCT), 
PFPR = (SELECT PFPR FROM MAEPR WITH (NOLOCK) WHERE KOPR=KOPRCT), 
HFPR = (SELECT HFPR FROM MAEPR WITH (NOLOCK) WHERE KOPR=KOPRCT), 
MRPR = (SELECT MRPR FROM MAEPR WITH (NOLOCK) WHERE KOPR=KOPRCT), 
CLALIBPR = (SELECT CLALIBPR FROM MAEPR WITH (NOLOCK) WHERE KOPR=KOPRCT), 
RUPR = (SELECT RUPR FROM MAEPR WITH (NOLOCK) WHERE KOPR=KOPRCT), 
ZOPR = (SELECT ZONAPR FROM MAEPR WITH (NOLOCK) WHERE KOPR=KOPRCT), 

-- ACTUALIZACION CLASIFICACIONES DE ENTIDADES
KOFUEN = (SELECT KOFUEN FROM MAEEN Me WITH (NOLOCK) WHERE #Tabla_Paso#.ENDO+SUENDO = Me.KOEN+SUEN),
VENDEDOR_ASIGNADO = ISNULL((SELECT TOP 1 NOKOFU FROM TABFU WHERE KOFU = KOFUEN),''),
RUEN = (SELECT RUEN FROM MAEEN Me WITH (NOLOCK) WHERE #Tabla_Paso#.ENDO+SUENDO = Me.KOEN+SUEN),
ZOEN = (SELECT ZOEN FROM MAEEN Me WITH (NOLOCK) WHERE #Tabla_Paso#.ENDO+SUENDO = Me.KOEN+SUEN),
ACTIEN = (SELECT ACTIEN FROM MAEEN Me WITH (NOLOCK) WHERE #Tabla_Paso#.ENDO+SUENDO = Me.KOEN+SUEN),
TIPOEN = (SELECT TIPOEN FROM MAEEN Me WITH (NOLOCK) WHERE #Tabla_Paso#.ENDO+SUENDO = Me.KOEN+SUEN),
TAMAEN = (SELECT TAMAEN FROM MAEEN Me WITH (NOLOCK) WHERE #Tabla_Paso#.ENDO+SUENDO = Me.KOEN+SUEN),
BODEGA = ISNULL((SELECT TOP 1 NOKOBO FROM TABBO Tb WHERE Tb.EMPRESA = #Tabla_Paso#.EMPRESA And Tb.KOSU = SULIDO And Tb.KOBO = BOSULIDO ),''),
VENDEDOR = ISNULL((SELECT TOP 1 NOKOFU FROM TABFU WHERE KOFU = KOFULIDO),''),
FUNCIONARIO = ISNULL((SELECT TOP 1 NOKOFU FROM TABFU WHERE KOFU = KOFUDO),'')

--WHERE FEEMDO BETWEEN @Fecha_Inicio AND @Fecha_Fin


UPDATE #Tabla_Paso# SET

RUBRO_EN = ISNULL((SELECT TOP 1 NOKORU FROM TABRU Tr WHERE Tr.KORU = #Tabla_Paso#.RUEN),'Sin Rubro'),
ZONA_EN = ISNULL((SELECT TOP 1 NOKOZO FROM TABZO Tr WHERE Tr.KOZO = #Tabla_Paso#.ZOEN),'Sin Zona'), 

ACTIVIDAD_ECONOMICA = ISNULL((SELECT TOP 1 NOKOCARAC 
	FROM TABCARAC Tr WHERE Tr.KOTABLA = 'ACTIVIDADE' AND Tr.KOCARAC = #Tabla_Paso#.ACTIEN),'Sin Activadad Economica'),
TIPO_ENTIDAD = ISNULL((SELECT TOP 1 NOKOCARAC 
	FROM TABCARAC Tr WHERE Tr.KOTABLA = 'TIPOENTIDA' AND Tr.KOCARAC = #Tabla_Paso#.TIPOEN),'Sin Tipo Entidad'),
TAMANO_EMPRESA = ISNULL((SELECT TOP 1 NOKOCARAC 
	FROM TABCARAC Tr WHERE Tr.KOTABLA = 'TAMA¥OEMPR' AND Tr.KOCARAC = #Tabla_Paso#.CLALIBPR),'Sin Tamaño Empresa'),

SUPER_FAMILIA = ISNULL((SELECT TOP 1 NOKOFM FROM TABFM Tf WHERE Tf.KOFM = #Tabla_Paso#.FMPR),'Sin Super Famila'),
FAMILIA = ISNULL((SELECT TOP 1 NOKOPF FROM TABPF Pf WHERE Pf.KOFM = #Tabla_Paso#.FMPR And Pf.KOPF = #Tabla_Paso#.PFPR ),'Sin Famila'),
SUB_FAMILIA = ISNULL((SELECT TOP 1 NOKOHF FROM TABHF Hf WHERE Hf.KOFM = #Tabla_Paso#.FMPR And Hf.KOPF = #Tabla_Paso#.PFPR And Hf.KOHF = #Tabla_Paso#.HFPR ),'Sin Sub-Famila'),                                                   
MARCA = ISNULL((SELECT TOP 1 NOKOMR FROM TABMR Tm WHERE Tm.KOMR = #Tabla_Paso#.MRPR),'Sin Marca'),
RUBRO_PR = ISNULL((SELECT TOP 1 NOKORU FROM TABRU Tr WHERE Tr.KORU = #Tabla_Paso#.RUPR),'Sin Rubro'),
CLAS_LIBRE = ISNULL((SELECT TOP 1 NOKOCARAC FROM TABCARAC Tr WHERE Tr.KOTABLA = 'CLALIBPR' AND Tr.KOCARAC = #Tabla_Paso#.CLALIBPR),'Sin Clasificación'),
ZONA_PR = ISNULL((SELECT TOP 1 NOKOZO FROM TABZO Tr WHERE Tr.KOZO = #Tabla_Paso#.ZOPR),'Sin Zona') 

WHERE FEEMDO BETWEEN @Fecha_Inicio AND @Fecha_Fin


Update #Tabla_Paso# Set VANELI = VANELI * -1,
                        VAIVLI = VAIVLI * -1,  
                        VAIMLI = VAIMLI * -1,
                        VABRLI = VABRLI * -1
Where TIDO In ('NCV','NCX','NEV','NCZ') And VANELI > 0



Select Count(*) From #Tabla_Paso#

--DROP TABLE #INFVEN
--DROP TABLE #Paso
*/
