
Insert Into #Tabla_Paso# (
IDMAEEDO
,IDMAEDDO 
,EMPRESA 
,TIDO 
,NUDO 
,RTEN 
,RUT 
,ENDO 
,SUENDO 
,RAZON 
,KOFUEN 
,VENDEDOR_ASIGNADO 
,RUEN 
,RUBRO_EN 
,ZOEN 
,ZONA_EN 
,ACTIEN 
,ACTIVIDAD_ECONOMICA 
,TIPOEN 
,TIPO_ENTIDAD 
,TAMAEN 
,TAMANO_EMPRESA 
,TRANSPOEN 
,TRANSPORTISTA 
,DIEN 
,CIEN 
,CIUDAD 
,CMEN 
,COMUNA 
,SUDO 
,SUCURSAL 
,Mes_Ano 
,Dia_Palabra 
,Mes_Palabra 
,Dia 
,Mes 
,Ano 
,FEEMDO 
,FEULVEDO 
,KOFUDO 
,FUNCIONARIO 
,MODO 
,TIMODO 
,TAMODO 
,CAPRAD 
,CAPREX 
,VANEDO 
,VAIVDO 
,VABRDO 
,LILG 
,NULIDO 
,SULIDO 
,LUVTLIDO 
,BOSULIDO 
,BODEGA 
,KOFULIDO 
,VENDEDOR 
,PRCT 
,TICT 
,TIPR 
,NUSEPR 
,KOPRCT 
,NOKOPR 
,UD 
,UDTRPR 
,RLUDPR 
,CAPRCO1 
,CAPRAD1 
,CAPREX1 
,CAPRNC1 
,UD01PR 
,CAPRCO2 
,CAPRAD2 
,CAPREX2 
,CAPRNC2 
,UD02PR 
,PPPRNE 
,PPPRBR 
,VANELI 
,VAIVLI 
,VAIMLI 
,VABRLI 
,FEEMLI 
,FEERLI 
,PPPRPM 
,PM 
,PPPRPMIFRS 
,POTENCIA 
,ESLIDO 
,PPPRNERE1 
,PPPRNERE2 
,RECAPRRE 
,FMPR 
,SUPER_FAMILIA 
,PFPR 
,FAMILIA 
,HFPR 
,SUB_FAMILIA 
,MRPR 
,MARCA 
,RUPR 
,RUBRO_PR 
,CLALIBPR 
,CLAS_LIBRE 
,ZOPR 
,ZONA_PR 
,COSTO 
,MONTO
,OCDO 
,SUCURSALLIDO 
,KOLTPR 
,NOKOLTPR 
,LVEN 
,NOLVEN 
--,KOGRU 
--,NOKOGRU 
--,KOGRUDT 
--,NOKOGRUDT
)


SELECT  EDO.IDMAEEDO As 'IDMAEEDO', 
        DDO.IDMAEDDO As 'IDMAEDDO', 
        DDO.EMPRESA As 'EMPRESA',
        EDO.TIDO As 'TIDO', 
        EDO.NUDO As 'NUDO', 
        Isnull(EN.RTEN,'') As 'RTEN',
        CAST('' AS VARCHAR(15)) AS 'RUT',
        EDO.ENDO As 'ENDO',
        EDO.SUENDO As 'SUENDO',
        Isnull((SELECT TOP 1 NOKOEN FROM MAEEN WHERE KOEN = EDO.ENDO AND SUEN = EDO.SUENDO),'???') As 'RAZON',
        CAST('' AS CHAR(3)) AS 'KOFUEN',
        CAST('' AS VARCHAR(50)) AS 'VENDEDOR_ASIGNADO',
        Isnull(EN.RUEN,'') As 'RUEN',
		CAST('' AS VARCHAR(50)) AS 'RUBRO_EN',
        Isnull(EN.ZOEN,'') As 'ZOEN',
        CAST('' AS VARCHAR(50)) AS 'ZONA_EN',
        Isnull(EN.ACTIEN,'') As 'ACTIEN',
        CAST('' AS VARCHAR(50)) 'AS ACTIVIDAD_ECONOMICA',
        Isnull(EN.TIPOEN,'') As 'TIPOEN',
        CAST('' AS VARCHAR(50)) AS 'TIPO_ENTIDAD',
        Isnull(EN.TAMAEN,'') As 'TAMAEN',
        CAST('' AS VARCHAR(50)) AS 'TAMANO_EMPRESA',
        Isnull(EN.TRANSPOEN,'') As 'TRANSPOEN',
        CAST('' AS VARCHAR(50)) AS 'TRANSPORTISTA',
        Isnull(EN.DIEN,'') As 'DIEN',
	    Isnull(EN.CIEN,'') As 'CIEN',
	    Isnull(CIUDAD.NOKOCI,'') As 'CIUDAD',
	    Isnull(EN.CMEN,'') As 'CMEN',
	    Isnull(COMUNA.NOKOCM,'') AS 'COMUNA', 
        EDO.SUDO  As 'SUDO',
        TABSU.NOKOSU AS 'SUCURSAL',
        DATENAME(MONTH,DDO.FEEMLI)+'.'+DATENAME(YEAR,DDO.FEEMLI) AS 'Mes_Ano',
        DATENAME(WEEKDAY,DDO.FEEMLI) AS 'Dia_Palabra',
        DATENAME(MONTH,DDO.FEEMLI) AS 'Mes_Palabra',
        DAY(DDO.FEEMLI) As 'Dia',
        MONTH(DDO.FEEMLI) As 'Mes',
        YEAR(DDO.FEEMLI) As 'Ano',
        EDO.FEEMDO As 'FEEMDO', 
        EDO.FEULVEDO As 'FEULVEDO', 
        EDO.KOFUDO As 'KOFUDO', 
        CAST('' AS VARCHAR) AS 'FUNCIONARIO',
        EDO.MODO As 'MODO', 
        EDO.TIMODO As 'TIMODO', 
		EDO.TAMODO As 'TAMODO',
		EDO.CAPRAD As 'CAPRAD', 
		EDO.CAPREX As 'CAPREX',
		EDO.VANEDO As 'VANEDO', 
		EDO.VAIVDO As 'VAIVDO', 
		EDO.VABRDO As 'VABRDO',
		DDO.LILG As 'LILG', 
		DDO.NULIDO As 'NULIDO', 
		DDO.SULIDO As 'SULIDO', 
		DDO.LUVTLIDO As 'LUVTLIDO', 
		DDO.BOSULIDO As 'BOSULIDO', 
		CAST('' AS VARCHAR (50)) AS 'BODEGA',
		DDO.KOFULIDO As 'KOFULIDO', 
		CAST('' AS VARCHAR) AS 'VENDEDOR',
		COALESCE(DDO.PRCT,0) AS 'PRCT', 
		DDO.TICT As 'TICT', 
		DDO.TIPR As 'TIPR', 
		DDO.NUSEPR As 'NUSEPR', 
		DDO.KOPRCT As 'KOPRCT', 
		DDO.NOKOPR As 'NOKOPR',
		CASE
                   WHEN DDO.UDTRPR = 1 THEN
                        DDO.UD01PR
                   ELSE DDO.UD02PR
        END AS 'UD',
		DDO.UDTRPR As 'UDTRPR', 
		DDO.RLUDPR As 'RLUDPR',
		CASE  
			WHEN DDO.PRCT = 1 THEN 0  
			WHEN EDO.TIDO IN ('GDV','GDP','GDD','GRC','GRP','GRI') AND DDO.PRCT = 0 THEN DDO.CAPRCO1-DDO.CAPREX1  
			WHEN EDO.TIDO IN ('NCV','NCC','NCX','NEV') AND DDO.PRCT = 0             THEN DDO.CAPRCO1*(-1)         
			ELSE DDO.CAPRCO1 
		END AS 'CAPRCO1',
			DDO.CAPRAD1, 
			DDO.CAPREX1, 
			DDO.CAPRNC1, 
			DDO.UD01PR,
		CASE  
			WHEN DDO.PRCT = 1 THEN 0  
			WHEN EDO.TIDO IN ('GDV','GDP','GDD','GRC','GRP','GRI') AND DDO.PRCT = 0 THEN DDO.CAPRCO2-DDO.CAPREX2  
			WHEN EDO.TIDO IN ('NCV','NCC','NCX','NEV') AND DDO.PRCT = 0             THEN DDO.CAPRCO2*(-1)         
			ELSE DDO.CAPRCO2 
		END AS 'CAPRCO2',
		DDO.CAPRAD2 As 'CAPRAD2', 
        DDO.CAPREX2 As 'CAPREX2', 
        DDO.CAPRNC2 As 'CAPRNC2', 
        DDO.UD02PR As 'UD02PR',
        DDO.PPPRNE As 'PPPRNE', 
        DDO.PPPRBR As 'PPPRBR', 
		DDO.VANELI As 'VANELI',
		DDO.VAIVLI As 'VAIVLI',
		DDO.VAIMLI As 'VAIMLI', 
		DDO.VABRLI As 'VABRLI', 
		DDO.FEEMLI As 'FEEMLI', 
		DDO.FEERLI As 'FEERLI', 
		DDO.PPPRPM As 'PPPRPM', 
		Isnull((SELECT TOP 1 PM FROM MAEPREM WHERE EMPRESA = DDO.EMPRESA AND KOPR = DDO.KOPRCT),0) AS 'PM',
		DDO.PPPRPMIFRS As 'PPPRPMIFRS', 
		DDO.POTENCIA As 'POTENCIA',
		DDO.ESLIDO As 'ESLIDO', 
		DDO.PPPRNERE1 As 'PPPRNERE1', 
		DDO.PPPRNERE2 As 'PPPRNERE2',
		COALESCE(TABCT.RECAPRRE,0) AS 'RECAPRRE',
		CASE DDO.PRCT WHEN 1 THEN '_ct_' ELSE COALESCE(PR.FMPR,'') END AS 'FMPR',
	    CAST('' AS VARCHAR(50)) AS 'SUPER_FAMILIA',
	    Isnull(PR.PFPR,'') As 'PFPR',
	    CAST('' AS VARCHAR(50)) AS 'FAMILIA',
	    Isnull(PR.HFPR,'') As 'HFPR',
	    CAST('' AS VARCHAR(50)) AS 'SUB_FAMILIA',
	    Isnull(PR.MRPR,'') As 'MRPR',
	    CAST('' AS VARCHAR(50)) AS 'MARCA',
	    Isnull(PR.RUPR,'') As 'RUPR',
	    CAST('' AS VARCHAR(50)) AS 'RUBRO_PR',
	    Isnull(PR.CLALIBPR,'') As 'CLALIBPR',
	    CAST('' AS VARCHAR(200)) AS 'CLAS_LIBRE',
	    Isnull(PR.ZONAPR,'') AS 'ZOPR',
	    CAST('' AS VARCHAR(50)) AS 'ZONA_PR',
		ROUND((DDO.PPPRPM * DDO.CAPRCO1) * 
			( CASE 
				WHEN EDO.TIDO IN ('NCV','NCX','NEV','NCC') THEN -1.0 
				ELSE 1.0 
			END ),2) AS 'COSTO',
		CASE  
			WHEN EDO.TIMODO='E' THEN DDO.VANELI*EDO.TAMODO* ( 
								CASE 
									WHEN EDO.TIDO IN ('NCV','NCX','NEV','NCC') THEN -1.0 
									ELSE 1.0 
								END )  
			ELSE DDO.VANELI * ( CASE 
									WHEN EDO.TIDO IN ('NCV','NCX','NEV','NCC') THEN -1.0 
									ELSE 1.0 
								END )  
		END AS 'MONTO',
		Isnull(OBDO.OCDO,'') As 'OCDO',
		CAST('' AS VARCHAR (50)) AS 'SUCURSALLIDO',
        Isnull(DDO.KOLTPR,'') As 'KOLTPR',
		Isnull(TP1.NOKOLT,'') As 'NOKOLTPR',
		Isnull(MAEEN.LVEN,'') As 'LVEN',
		Isnull(TP2.NOKOLT,'') As 'NOLVEN'
        --,Isnull((Select Top 1 KOGRU From TABFUGD Where KOFU = DDO.KOFULIDO Order By ORDEN),''),
        --Isnull((Select Top 1 g.NOKOGRU From TABFUGE g Inner Join TABFUGD d On g.KOGRU = d.KOGRU Where d.KOFU = DDO.KOFULIDO),''),
        --'',''
       
        --,'','','','' Poner aca los valores de los GRUPOS de VENDEDORES
--INTO #Tabla_Paso#
FROM MAEEDO EDO WITH ( NOLOCK ) 
	LEFT JOIN MAEDDO AS DDO WITH (NOLOCK) ON 
		EDO.IDMAEEDO=DDO.IDMAEEDO AND DDO.LILG NOT IN ('GR','IM')  
	LEFT JOIN MAEEDOOB AS OBDO WITH (NOLOCK) ON 
		EDO.IDMAEEDO=OBDO.IDMAEEDO  
	LEFT JOIN MAEPR PR WITH (NOLOCK) ON 
	    PR.KOPR=DDO.KOPRCT  
	LEFT JOIN MAEEN WITH (NOLOCK) ON 
		MAEEN.KOEN=EDO.ENDO AND 
		MAEEN.SUEN=EDO.SUENDO  
	LEFT JOIN TABCT WITH (NOLOCK) ON 
		DDO.KOPRCT=TABCT.KOCT AND DDO.PRCT=1  
	LEFT JOIN TABSU WITH ( NOLOCK ) ON 
		TABSU.EMPRESA = EDO.EMPRESA AND TABSU.KOSU=EDO.SUDO
	LEFT JOIN MAEEN EN WITH ( NOLOCK ) ON 
	    EDO.ENDO = EN.KOEN AND EDO.SUENDO = EN.SUEN
	LEFT JOIN TABCI CIUDAD  WITH ( NOLOCK ) ON 
	    CIUDAD.KOPA=EN.PAEN AND 
	    CIUDAD.KOCI=EN.CIEN  
	LEFT JOIN TABCM COMUNA  WITH ( NOLOCK ) ON 
	    COMUNA.KOPA=EN.PAEN AND 
	    COMUNA.KOCI=EN.CIEN AND 
	    COMUNA.KOCM=EN.CMEN  
    LEFT JOIN TABPP TP1 ON TP1.KOLT = SUBSTRING(DDO.KOLTPR ,6,3)
	LEFT JOIN TABPP TP2 ON TP2.KOLT = SUBSTRING(MAEEN.LVEN ,6,3)
WHERE  DDO.IDMAEEDO IN (#Idmaeedo#)
ORDER BY EDO.IDMAEEDO 


Update #Tabla_Paso# Set VANELI = VANELI * -1,
                        VAIVLI = VAIVLI * -1,  
                        VAIMLI = VAIMLI * -1,
                        VABRLI = VABRLI * -1
Where TIDO In ('NCV','NCX','NEV','NCZ') And VANELI > 0 And IDMAEEDO IN (#Idmaeedo#)

/*--KOGRU
Update #Tabla_Paso# Set KOGRU = Isnull((Select Top 1 KOGRU From TABFUGD Where KOFU = KOFULIDO Order By ORDEN),''),
                        NOKOGRU = Isnull((Select Top 1 g.NOKOGRU 
                                            From TABFUGE g Inner Join TABFUGD d On g.KOGRU = d.KOGRU 
                                                Where d.KOFU = KOFULIDO),'')
Where IDMAEEDO IN (#Idmaeedo#)


Update #Tabla_Paso# Set KOGRUDT = Isnull(Bk.Grupo,''),NOKOGRUDT = Isnull(G.NOKOGRU,'')
From #Global_BaseBk#Zw_Docu_Det Bk
Inner Join #Tabla_Paso# Tp On Bk.Idmaeddo = Tp.IDMAEDDO
Left Join TABFUGE G On Bk.Grupo = G.KOGRU
Where Tp.IDMAEEDO IN (#Idmaeedo#)
*/--KOGRU







