'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class _SQLquery
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BkSpecialPrograms._SQLquery", GetType(_SQLquery).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a -- &apos;STOCK COMPRAS NO RECEPCIONADAS ************ STDV1C
        '''
        '''BEGIN TRY
        ''' DROP TABLE #INF_STOCK
        ''' END TRY
        ''' BEGIN CATCH
        '''END CATCH
        '''
        '''DECLARE 
        '''
        '''@Empresa   Char(2),
        '''@Sucursal  Char(3),
        '''@Bodega    Char(3),
        '''@Codigo    Char(13),
        '''@Fecha     Date  
        '''
        '''Select @Empresa  = &apos;#Empresa#&apos;,
        '''       @Sucursal = &apos;#Sucursal#&apos;,
        '''       @Bodega   = &apos;#Bodega#&apos;, 
        '''	   @Codigo   = &apos;#@Codigo#&apos;,
        '''	   @Fecha    = &apos;#Fecha#&apos;
        '''
        '''SELECT D.KOPRCT,D.EMPRESA,E.TIDO,E.SUBTIDO,D.SULIDO,D.BOSULIDO,
        '''        	   
        '''	   D.CAPRCO1 - (D.CAPREX1 [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Consolidacion_Stock_Compras_no_recepcionadas_X_producto() As String
            Get
                Return ResourceManager.GetString("Consolidacion_Stock_Compras_no_recepcionadas_X_producto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 
        ''' --STOCK COMPROMETIDO ************ STOCNV1
        '''
        '''BEGIN TRY
        ''' DROP TABLE #INF_STOCK
        ''' END TRY
        ''' BEGIN CATCH
        '''END CATCH
        '''
        '''DECLARE 
        '''
        '''@Empresa   Char(2),
        '''@Sucursal  Char(3),
        '''@Bodega    Char(3),
        '''@Codigo    Char(13),
        '''@Fecha     Date  
        '''
        '''Select @Empresa  = &apos;#Empresa#&apos;,
        '''       @Sucursal = &apos;#Sucursal#&apos;,
        '''       @Bodega   = &apos;#Bodega#&apos;, 
        '''	   @Codigo   = &apos;#@Codigo#&apos;,
        '''	   @Fecha    = &apos;#Fecha#&apos;
        '''
        '''SELECT D.KOPRCT,D.EMPRESA,E.TIDO,E.SUBTIDO,D.SULIDO,D.BOSULIDO,
        '''       
        '''	   D.CAPRCO1 - (D.CAPREX1 + D.CAPRAD1) A [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Consolidacion_Stock_Comprometido_X_producto() As String
            Get
                Return ResourceManager.GetString("Consolidacion_Stock_Comprometido_X_producto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 
        '''-- &apos;STOCK DESPACHADO SIN FACTURAR ************ DESPNOFAC1
        '''
        '''BEGIN TRY
        ''' DROP TABLE #INF_STOCK
        ''' END TRY
        ''' BEGIN CATCH
        '''END CATCH
        '''
        '''DECLARE 
        '''
        '''@Empresa   Char(2),
        '''@Sucursal  Char(3),
        '''@Bodega    Char(3),
        '''@Codigo    Char(13),
        '''@Fecha  Date  
        '''
        '''Select @Empresa  = &apos;#Empresa#&apos;,
        '''       @Sucursal = &apos;#Sucursal#&apos;,
        '''       @Bodega   = &apos;#Bodega#&apos;, 
        '''	   @Codigo   = &apos;#@Codigo#&apos;,
        '''	   @Fecha    = &apos;#Fecha#&apos;
        '''
        '''SELECT D.KOPRCT,D.EMPRESA,E.TIDO,E.SUBTIDO,D.SULIDO,D.BOSULIDO,
        '''
        '''	   D.CAPRCO1 - (D.CAPREX1 + D.CAPRA [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Consolidacion_Stock_Despachado_Sin_Facturar_X_producto() As String
            Get
                Return ResourceManager.GetString("Consolidacion_Stock_Despachado_Sin_Facturar_X_producto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a -- &apos;STOCK DEVENGADO ************ STDV1
        '''
        '''BEGIN TRY
        ''' DROP TABLE #INF_STOCK
        ''' END TRY
        ''' BEGIN CATCH
        '''END CATCH
        '''
        '''DECLARE 
        '''
        '''@Empresa   Char(2),
        '''@Sucursal  Char(3),
        '''@Bodega    Char(3),
        '''@Codigo    Char(13),
        '''@Fecha  Date  
        '''
        '''Select @Empresa  = &apos;#Empresa#&apos;,
        '''       @Sucursal = &apos;#Sucursal#&apos;,
        '''       @Bodega   = &apos;#Bodega#&apos;, 
        '''	   @Codigo   = &apos;#@Codigo#&apos;,
        '''	   @Fecha    = &apos;#Fecha#&apos;
        '''
        '''SELECT D.KOPRCT,D.EMPRESA,D.TIDO,E.SUBTIDO,D.SULIDO,D.BOSULIDO,
        '''
        '''       D.CAPRCO1 - (D.CAPREX1 + D.CAPRAD1) AS &apos;CantidadUd [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Consolidacion_Stock_Devengado_X_producto() As String
            Get
                Return ResourceManager.GetString("Consolidacion_Stock_Devengado_X_producto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 
        '''--  &apos;STOCK PEDIDO *************** STOCNV1C
        '''
        '''BEGIN TRY
        ''' DROP TABLE #INF_STOCK
        ''' END TRY
        ''' BEGIN CATCH
        '''END CATCH
        '''
        '''DECLARE 
        '''
        '''@Empresa   Char(2),
        '''@Sucursal  Char(3),
        '''@Bodega    Char(3),
        '''@Codigo    Char(13),
        '''@Fecha  Date  
        '''
        '''Select @Empresa  = &apos;#Empresa#&apos;,
        '''       @Sucursal = &apos;#Sucursal#&apos;,
        '''       @Bodega   = &apos;#Bodega#&apos;, 
        '''	   @Codigo   = &apos;#@Codigo#&apos;,
        '''	   @Fecha    = &apos;#Fecha#&apos;
        '''
        '''--E.SUBTIDO
        '''SELECT D.KOPRCT,D.EMPRESA,D.TIDO,D.SULIDO,D.BOSULIDO,
        '''       D.CAPRCO1 - (D.CAPREX1 + D.CAPRAD1) AS &apos;Can [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Consolidacion_Stock_En_Transito() As String
            Get
                Return ResourceManager.GetString("Consolidacion_Stock_En_Transito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a --STOCK FISICO ************** STFI1
        '''
        '''BEGIN TRY
        ''' DROP TABLE #INF_STOCK
        ''' END TRY
        ''' BEGIN CATCH
        '''END CATCH
        '''
        '''DECLARE 
        '''
        '''@Empresa   Char(2),
        '''@Sucursal  Char(3),
        '''@Bodega    Char(3),
        '''@Codigo    Char(13),
        '''@Fecha  Date  
        '''
        '''Select @Empresa  = &apos;#Empresa#&apos;,
        '''       @Sucursal = &apos;#Sucursal#&apos;,
        '''       @Bodega   = &apos;#Bodega#&apos;, 
        '''	   @Codigo   = &apos;#@Codigo#&apos;,
        '''	   @Fecha    = &apos;#Fecha#&apos;
        '''
        '''SELECT D.KOPRCT,D.EMPRESA,E.TIDO,E.SUBTIDO,D.SULIDO,D.BOSULIDO,
        '''        CASE  
        '''             WHEN E.TIDO IN (&apos;FCV&apos;,&apos;FDB&apos;,&apos;FDV&apos; [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Consolidacion_Stock_Fisico_X_producto() As String
            Get
                Return ResourceManager.GetString("Consolidacion_Stock_Fisico_X_producto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 
        '''--  &apos;STOCK PEDIDO *************** STOCNV1C
        '''
        '''BEGIN TRY
        ''' DROP TABLE #INF_STOCK
        ''' END TRY
        ''' BEGIN CATCH
        '''END CATCH
        '''
        '''DECLARE 
        '''
        '''@Empresa   Char(2),
        '''@Sucursal  Char(3),
        '''@Bodega    Char(3),
        '''@Codigo    Char(13),
        '''@Fecha  Date  
        '''
        '''Select @Empresa  = &apos;#Empresa#&apos;,
        '''       @Sucursal = &apos;#Sucursal#&apos;,
        '''       @Bodega   = &apos;#Bodega#&apos;, 
        '''	   @Codigo   = &apos;#@Codigo#&apos;,
        '''	   @Fecha    = &apos;#Fecha#&apos;
        '''
        '''--E.SUBTIDO
        '''SELECT D.KOPRCT,D.EMPRESA,D.TIDO,D.SULIDO,D.BOSULIDO,
        '''       D.CAPRCO1 - (D.CAPREX1 + D.CAPRAD1) AS &apos;Can [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Consolidacion_Stock_Pedido_X_producto() As String
            Get
                Return ResourceManager.GetString("Consolidacion_Stock_Pedido_X_producto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a -- &apos;STOCK RECEPCIONADO SIN FACTURAR ************ RECENOFAC1
        '''
        '''BEGIN TRY
        ''' DROP TABLE #INF_STOCK
        ''' END TRY
        ''' BEGIN CATCH
        '''END CATCH
        '''
        '''DECLARE 
        '''
        '''@Empresa   Char(2),
        '''@Sucursal  Char(3),
        '''@Bodega    Char(3),
        '''@Codigo    Char(13),
        '''@Fecha  Date  
        '''
        '''Select @Empresa  = &apos;#Empresa#&apos;,
        '''       @Sucursal = &apos;#Sucursal#&apos;,
        '''       @Bodega   = &apos;#Bodega#&apos;, 
        '''	   @Codigo   = &apos;#@Codigo#&apos;,
        '''	   @Fecha    = &apos;#Fecha#&apos;
        '''
        '''SELECT D.KOPRCT,D.EMPRESA,E.TIDO,E.SUBTIDO,D.SULIDO,D.BOSULIDO,
        '''       
        '''	   D.CAPRCO1 - (D.CAPREX1 +  [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Consolidacion_Stock_Recepcionado_sin_facturar_X_producto() As String
            Get
                Return ResourceManager.GetString("Consolidacion_Stock_Recepcionado_sin_facturar_X_producto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Declare @Empresa Char(2) = &apos;#Empresa#&apos;,
        '''        @Codigo Char(13) = &apos;#Codigo#&apos;
        '''
        '''UPDATE MAEPR SET 
        '''                 STFI1 = ISNULL((select SUM(STFI1) From MAEST Ms WHERE Ms.KOPR = MAEPR.KOPR),0),
        '''                 STFI2 = ISNULL((select SUM(STFI2) From MAEST Ms WHERE Ms.KOPR = MAEPR.KOPR),0),
        '''                 STDV1 = ISNULL((select SUM(STDV1) From MAEST Ms WHERE Ms.KOPR = MAEPR.KOPR),0),
        '''                 STDV2 = ISNULL((select SUM(STDV2) From MAEST Ms WHERE Ms.KOPR = MAEPR.KOPR),0),
        '''                 
        ''' [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Consolidacion_Total_MAEPR_MAEPREM_X_producto() As String
            Get
                Return ResourceManager.GetString("Consolidacion_Total_MAEPR_MAEPREM_X_producto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Declare @Empresa Char(2) = &apos;#Empresa#&apos;
        '''
        '''Update #Tabla_Paso# Set Dif_StockF_Ud1 = STFI1-StockF_Ud1,
        '''                        Dif_StockF_Ud2 = STFI1-StockF_Ud2,
        '''				        Dif_StockDev_Ud1 = STDV1-StockDev_Ud1,
        '''					    Dif_StockDev_Ud2 = STDV2-StockDev_Ud2,
        '''					    Dif_StockDsf_Ud1 = DESPNOFAC1-StockDsf_Ud1,
        '''					    Dif_StockDsf_Ud2 = DESPNOFAC2-StockDsf_Ud2,
        '''					    Dif_StockCom_Ud1 = STOCNV1-StockCom_Ud1,
        '''					    Dif_StockCom_Ud2 = STOCNV2-StockCom_Ud2,
        '''					    Dif_StockCnr_Ud1 = STDV1C-Stoc [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Consolidacion_Total_MAEST_MAEPR_MAEPREM_Bakapp() As String
            Get
                Return ResourceManager.GetString("Consolidacion_Total_MAEST_MAEPR_MAEPREM_Bakapp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 
        '''CREATE TABLE [dbo].[#Paso](
        '''	[EMPRESA]           [char](2)  Default (&apos;&apos;),
        '''	[KOSU]              [char](3)	Default (&apos;&apos;),
        '''	[KOBO]              [char](3)	Default (&apos;&apos;),
        '''	[KOPR]              [char](13)	Default (&apos;&apos;),
        '''	[NOKOPR]            [varchar](50)	Default (&apos;&apos;),
        '''	[STFI1]             [float]	Default(0),
        '''    [STFI2]             [float]	Default(0),
        '''	StockF_Ud1          [float]    Default(0),
        '''	StockF_Ud2          [float]    Default(0),
        '''	Dif_StockF_Ud1      [float]    Default(0),
        '''	Dif_StockF_Ud2      [f [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Creacion_Tabla_Paso_Conolidacion_Stock() As String
            Get
                Return ResourceManager.GetString("Creacion_Tabla_Paso_Conolidacion_Stock", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
