
SELECT IDMAEDPCD,IDMAEDPCE AS IDPC,FEASDP as FECHA,IDRST,
       VAASDP AS MONTO,
       CAST('' AS VARCHAR(3)) AS TIDO,
       CAST('' AS VARCHAR(10)) AS NUDO,
       CAST('' AS VARCHAR(50)) AS ENTIDAD,
       CAST('' AS VARCHAR(3)) AS TID_DOC,
       CAST('' AS VARCHAR(20)) AS NRO_DOC
Into #Paso
FROM MAEDPCD WHERE IDMAEDPCE IN 
#Filtro_Idmaedpce#

UPDATE #Paso SET TIDO = (SELECT TIDO FROM MAEEDO WHERE IDMAEEDO = IDRST),
                 NUDO = (SELECT NUDO FROM MAEEDO WHERE IDMAEEDO = IDRST),
                 ENTIDAD = (SELECT TOP 1 NOKOEN FROM MAEEN WHERE KOEN = (SELECT ENDP FROM MAEDPCE WHERE IDMAEDPCE =IDPC)),
                 TID_DOC = (SELECT TIDP  FROM MAEDPCE WHERE IDMAEDPCE = IDPC),
                 NRO_DOC = (SELECT NUCUDP  FROM MAEDPCE WHERE IDMAEDPCE = IDPC),
                 FECHA = (SELECT FEVEDP  FROM MAEDPCE WHERE IDMAEDPCE = IDPC)

Select ENTIDAD,TIDO,NUDO,MONTO,TID_DOC,NRO_DOC,FECHA From #Paso

Drop Table #Paso