'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Recursos_Locales
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BkSpecialPrograms.Recursos_Locales", GetType(Recursos_Locales).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 
        '''
        '''SELECT  Id_Ot,Sub_Ot,Id_Ot_Padre,Nro_Ot,Pertenece, 
        '''        Empresa, Sucursal, Bodega, 
        '''        CodEntidad, SucEntidad, Rut,
        '''        Isnull((Select Top 1 NOKOEN From MAEEN Where KOEN = CodEntidad And SUEN = SucEntidad),&apos;&apos;) As Cliente, 
        '''        Case Chk_Serv_Domicilio When 1 Then &apos;Domicilio&apos; Else &apos;Taller&apos; End As &apos;Lugar&apos;,
        '''        Fecha_Ingreso, 
        '''        DATEDIFF(D,Fecha_Ingreso,Getdate()) AS Dias,
        '''        Fecha_Ingreso As Fecha,
        '''        Fecha_Ingreso As Hora,
        '''        --CONVERT(VARCHAR, Fecha_Ingr [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SqlQuery_Lista_OT() As String
            Get
                Return ResourceManager.GetString("SqlQuery_Lista_OT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 
        '''SELECT Distinct Id_Ot_Padre,Nro_Ot, 
        '''        Empresa, Sucursal, Bodega, 
        '''        CodEntidad, SucEntidad, Rut,
        '''        Isnull((Select Top 1 NOKOEN From MAEEN Where KOEN = CodEntidad And SUEN = SucEntidad),&apos;&apos;) As Cliente, 
        '''        Case Chk_Serv_Domicilio When 1 Then &apos;Domicilio&apos; Else &apos;Taller&apos; End As &apos;Lugar&apos;,
        '''        DATEDIFF(D,Fecha_Ingreso,Getdate()) AS Dias,
        '''        Cast(Fecha_Ingreso As Date) As Fecha
        '''        --Fecha_Ingreso As Hora
        '''Into #Paso1        
        '''
        '''FROM   #Db_BakApp#Zw_St_OT_Encabezado
        '''	Le [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SqlQuery_Lista_OT2() As String
            Get
                Return ResourceManager.GetString("SqlQuery_Lista_OT2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 
        '''
        '''
        '''Declare @Id_Ot Int = #Id_Ot# 
        '''
        '''
        '''-- ENCABEZADO TABLA (0)
        '''
        '''SELECT  Id_Ot,Nro_Ot,Sub_Ot,Id_Ot_Padre,Empresa,Sucursal,Bodega,CodEntidad,SucEntidad,Rten,Rut, 
        '''        Cast(&apos;&apos; As Varchar(50)) As	Cliente,
        '''        Fecha_Ingreso, 
        '''        Fecha_Compromiso, 
        '''        Fecha_Entrega, 
        '''        Fecha_Cierre,
        '''        CodEstado, 
        '''        (Select top 1 NombreTabla From #Db_BakApp#Zw_TablaDeCaracterizaciones 
        '''					Where Tabla = &apos;ESTADOS_ST&apos; And CodigoTabla = CodEstado) As &apos;Estado&apos;, 
        '''        CodMaquina,
        '''   [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SqlQuery_Traer_OT() As String
            Get
                Return ResourceManager.GetString("SqlQuery_Traer_OT", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
