
DECLARE 

@Fecha_Inicio Date = '#Fecha_Inicio#', 
@Fecha_Fin    Date = '#Fecha_Fin#'
 
BEGIN TRY
 DROP TABLE #INFVEN
 END TRY
 BEGIN CATCH
END CATCH

 
SELECT EDO.IDMAEEDO, EDO.TIDO, EDO.NUDO, EDO.ENDO, EDO.SUENDO, EDO.SUDO,EDO.FEEMDO, EDO.FEULVEDO, EDO.KOFUDO, EDO.MODO, EDO.TIMODO, 
		EDO.TAMODO,EDO.CAPRAD, EDO.CAPREX,EDO.VANEDO, EDO.VAIVDO, EDO.VABRDO,
		COALESCE(TABZO.NOKOZO,'') AS NOKOZO,
		COALESCE(TABRU.NOKORU,'') AS NOKORU,
		COALESCE(TABSU.NOKOSU,'') AS NOSUDO,
		COALESCE(TABFU.NOKOFU,'') AS NOKOFU,
		COALESCE(MAEEN.NOKOEN,'') AS NOKOEN,
		COALESCE(MAEEN.ZOEN,  '') AS ZOEN,
		COALESCE(MAEEN.RUEN,'') AS RUEN,
		CASE  
			WHEN EDO.TIMODO='E' THEN 
					EDO.VANEDO*EDO.TAMODO* ( 
						CASE 
							WHEN EDO.TIDO IN ('NCV','NCX','NEV') OR EDO.TIDO='NCC' THEN -1 
							ELSE 1 
							END )  
			ELSE EDO.VANEDO* ( 
						CASE 
							WHEN EDO.TIDO IN ('NCV','NCX','NEV') OR EDO.TIDO='NCC' THEN -1 
							ELSE 1 
							END )  
			END AS MONTO 
INTO #INFVEN
FROM MAEEDO EDO WITH ( NOLOCK ) 
		    LEFT JOIN MAEEN WITH ( NOLOCK ) ON 
				MAEEN.KOEN=EDO.ENDO AND MAEEN.SUEN=EDO.SUENDO  
			LEFT JOIN TABZO WITH ( NOLOCK ) ON 
				TABZO.KOZO=MAEEN.ZOEN  
			LEFT JOIN TABRU WITH ( NOLOCK ) ON 
				TABRU.KORU=MAEEN.RUEN  
			LEFT JOIN TABSU WITH ( NOLOCK ) ON 
				TABSU.KOSU=EDO.SUDO  
			LEFT JOIN TABFU WITH ( NOLOCK ) ON 
				TABFU.KOFU=EDO.KOFUDO 
WHERE 

(EDO.TIDO IN ('BLV','BLX','BSV','ESC','FCV',
              'FDB','FDV','FDX','FDZ','FEE',
              'FEV','FVL','FVT','FVX','FVZ',
              'FXV','FYV','NCE',
			  'NCV','NCX','NCZ','NEV','RIN') AND 
EDO.FEEMDO BETWEEN @Fecha_Inicio AND @Fecha_Fin AND 
EDO.EMPRESA='01' AND 
#Nudonodefi#
EDO.ESDO<>'N' ) 

-- INFORME VENTAS

SELECT KOSU AS SUDO,NOKOSU AS NOSUDO,0 AS MONTO FROM TABSU WHERE KOSU NOT IN (SELECT SUDO FROM #INFVEN)
UNION
SELECT SUDO,NOSUDO,SUM(MONTO) AS MONTO FROM #INFVEN WITH ( NOLOCK )--INTO #INF015_1 
GROUP BY SUDO,NOSUDO
--UNION
--SELECT 'ZZZ' AS SUDO, 'TOTAL' AS NOSUDO,SUM(MONTO) AS MONTO  --INTO #INF015_1 
--FROM #INFVEN WITH ( NOLOCK )  

ORDER BY SUDO ,NOSUDO

DROP  TABLE #INFVEN 