
DECLARE 

@Fecha_Inicio Date = '#Fecha_Inicio#', 
@Fecha_Fin    Date = '#Fecha_Fin#'
 
BEGIN TRY
 DROP TABLE #INFGUIAS
 END TRY
 BEGIN CATCH
END CATCH

SELECT  EDO.IDMAEEDO,EDO.TIDO,EDO.SUBTIDO,EDO.NUDO,EDO.FEEMDO,EDO.FEULVEDO,EDO.ENDO,EDO.SUENDO,MAEEN.NOKOEN,
		EDO.KOFUDO,TABFU.NOKOFU,
		EDO.SUDO,TABSU.NOKOSU,EDO.TIMODO,EDO.MODO,
		CASE 
			WHEN EDO.TIMODO='E' THEN 0.0 
			ELSE EDO.VANEDO 
		END AS NETO,
		CASE 
			WHEN EDO.TIMODO='E' THEN 0.0 
			ELSE EDO.VAIVDO 
		END AS IVA,
		CASE 
			WHEN EDO.TIMODO='E' THEN 0.0 
			ELSE EDO.VANEDO+EDO.VAIVDO+EDO.VAIMDO 
		END AS TOTAL,
		CASE 
			WHEN EDO.TIMODO='E' THEN EDO.VANEDO 
			ELSE 0.0 
		END AS VANEDO_2,
		CASE 
			WHEN EDO.TIMODO='E' THEN EDO.VAIVDO 
			ELSE 0.0 
		END AS VAIVDO_2,
		CASE 
			WHEN EDO.TIMODO='E' THEN EDO.VANEDO+EDO.VAIVDO+EDO.VAIMDO 
			ELSE 0.0 
		END AS BRUTO,
		CAST(0 AS FLOAT) AS COSTO,
		CAST(0 AS FLOAT) AS MARGEN,
		CASE 
			WHEN EDO.CAPRAD+EDO.CAPREX = 0.0 THEN ( 
				CASE 
					WHEN EDO.ESDO='N' THEN 'Nula' 
					ELSE 'No F' 
				END )  
			ELSE ( 
				CASE 
					WHEN EDO.CAPRCO=EDO.CAPRAD+EDO.CAPREX THEN 'Fact' 
					ELSE 'Parc' 
				END ) 
		END AS WW 
INTO #INFGUIAS		
FROM MAEEDO AS EDO WITH ( NOLOCK )  
	LEFT JOIN MAEEN WITH ( NOLOCK ) ON 
		MAEEN.KOEN=EDO.ENDO AND MAEEN.SUEN=EDO.SUENDO  
	LEFT JOIN TABSU WITH ( NOLOCK ) ON 
		TABSU.KOSU=EDO.SUDO  
	LEFT JOIN TABFU WITH ( NOLOCK ) ON 
		TABFU.KOFU=EDO.KOFUDO  
	
WHERE 
	EDO.TIDO IN ('GDV','GDP') AND 
	EDO.EMPRESA='01'  AND 
	EDO.FEEMDO BETWEEN @Fecha_Inicio AND @Fecha_Fin 


UPDATE #INFGUIAS SET COSTO = ISNULL((SELECT SUM(PPPRPM * CAPRCO1) FROM MAEDDO Do WHERE Do.IDMAEEDO = #INFGUIAS.IDMAEEDO),0)
UPDATE #INFGUIAS SET MARGEN = CASE WHEN NETO = 0 THEN 0 ELSE ((NETO-COSTO)/NETO) * 100 END 


--SELECT SUDO,NOKOSU,FEEMDO,COUNT(TIDO) AS GUIAS,SUM(NETO) AS MONTO FROM #INFGUIAS
--GROUP BY SUDO,NOKOSU,FEEMDO
--ORDER BY SUDO,NOKOSU,FEEMDO

SELECT SUDO,NOKOSU,COUNT(TIDO) AS GUIAS,SUM(COSTO) AS COSTO,SUM(NETO) AS MONTO,(SUM(NETO)-SUM(COSTO)) as MARGEN_V,(SUM(NETO)-SUM(COSTO))/SUM(NETO) AS MARGEN FROM #INFGUIAS
GROUP BY SUDO,NOKOSU
UNION
SELECT KOSU AS SUDO,NOKOSU,0 AS GUIAS,0 AS COSTO,0 AS MONTO, 0 AS MARGEN_V, 0 AS MARGEN FROM TABSU WHERE KOSU NOT IN  (SELECT SUDO FROM #INFGUIAS) 
ORDER BY SUDO,NOKOSU

--SELECT * FROM #INFGUIAS ORDER BY NUDO

DROP  TABLE #INFGUIAS 

--SELECT PPPRPM,PPPRNERE1,* FROM MAEDDO WHERE IDMAEEDO = 357111

--SELECT SUM(PPPRPM) FROM MAEDDO WHERE IDMAEEDO = 357111

