
DECLARE 

@Fecha_Inicio Date = '#Fecha_Inicio#', 
@Fecha_Fin    Date = '#Fecha_Fin#'
 



BEGIN TRY
 DROP TABLE #INFGUIAS
 END TRY
 BEGIN CATCH
END CATCH

SELECT  EDO.IDMAEEDO, EDO.TIDO, EDO.NUDO, EDO.ENDO,EDO.SUENDO,EDO.SUDO,TABSU.NOKOSU,EDO.FEEMDO, EDO.FEULVEDO, 
		EDO.KOFUDO, EDO.MODO, EDO.TIMODO, EDO.TAMODO,EDO.CAPRAD, EDO.CAPREX,EDO.VANEDO, EDO.VAIVDO, EDO.VABRDO,
		DDO.LILG, DDO.NULIDO, DDO.SULIDO, DDO.LUVTLIDO, DDO.BOSULIDO, DDO.KOFULIDO, 
		COALESCE(DDO.PRCT,0) AS PRCT, DDO.TICT, DDO.TIPR, DDO.NUSEPR, DDO.KOPRCT, DDO.UDTRPR, DDO.RLUDPR,
		CASE  
			WHEN DDO.PRCT = 1 THEN 0  
			WHEN EDO.TIDO IN ('GDV','GDP','GDD','GRC','GRP','GRI') AND DDO.PRCT = 0 THEN DDO.CAPRCO1-DDO.CAPREX1  
			WHEN EDO.TIDO IN ('NCV','NCC','NCX','NEV') AND DDO.PRCT = 0             THEN DDO.CAPRCO1*(-1)         
			ELSE DDO.CAPRCO1 
		END AS CAPRCO1,
			DDO.CAPRAD1, DDO.CAPREX1, DDO.CAPRNC1, DDO.UD01PR,
		CASE  
			WHEN DDO.PRCT = 1 THEN 0  
			WHEN EDO.TIDO IN ('GDV','GDP','GDD','GRC','GRP','GRI') AND DDO.PRCT = 0 THEN DDO.CAPRCO2-DDO.CAPREX2  
			WHEN EDO.TIDO IN ('NCV','NCC','NCX','NEV') AND DDO.PRCT = 0             THEN DDO.CAPRCO2*(-1)         
			ELSE DDO.CAPRCO2 
		END AS CAPRCO2,
		DDO.CAPRAD2, DDO.CAPREX2, DDO.CAPRNC2, DDO.UD02PR,DDO.PPPRNE, DDO.PPPRBR, 
		DDO.VANELI,
		DDO.VABRLI, 
		DDO.FEEMLI, DDO.FEERLI, 
		--DDO.PPPRPM, -- COSTO PM
		--CAST(0 AS FLOAT) AS 'COSTO',
		(SELECT TOP 1 PM FROM MAEPREM WHERE EMPRESA = DDO.EMPRESA AND KOPR = DDO.KOPRCT) AS PM,
		DDO.PPPRPMIFRS, DDO.POTENCIA,DDO.ESLIDO, DDO.PPPRNERE1, DDO.PPPRNERE2,DDO.IDMAEDDO,
		 (CASE DDO.PRCT 
			WHEN 1 THEN '_ct_' 
			ELSE COALESCE(MAEPR.FMPR,'') 
		  END) AS FMPR,
		COALESCE(MAEPR.MRPR,  '') AS MRPR,
		COALESCE(MAEEN.ZOEN,  '') AS ZOEN,
		COALESCE(MAEEN.RUEN,'') AS RUEN,
		COALESCE(TABCT.RECAPRRE,0) AS RECAPRRE,
		COALESCE(MAEPR.PFPR,'') AS PFPR,
		COALESCE(MAEPR.HFPR,'') AS HFPR,
		DDO.PPPRPM,
		ROUND((DDO.PPPRPM * DDO.CAPRCO1) * 
			( CASE 
				WHEN EDO.TIDO IN ('NCV','NCX','NEV','NCC') THEN -1.0 
				ELSE 1.0 
			END ),2) AS COSTO,
		DDO.VANELI AS 'NETO',
		CAST(0 AS FLOAT) AS 'MARGEN',
		CASE  
			WHEN EDO.TIMODO='E' THEN DDO.VANELI*EDO.TAMODO* ( 
								CASE 
									WHEN EDO.TIDO IN ('NCV','NCX','NEV','NCC') THEN -1.0 
									ELSE 1.0 
								END )  
			ELSE DDO.VANELI * ( CASE 
									WHEN EDO.TIDO IN ('NCV','NCX','NEV','NCC') THEN -1.0 
									ELSE 1.0 
								END )  
		END AS MONTO,
		OBDO.OCDO 
INTO #INFGUIAS
FROM MAEEDO EDO WITH ( NOLOCK ) 
	LEFT JOIN MAEDDO AS DDO WITH (NOLOCK) ON 
		EDO.IDMAEEDO=DDO.IDMAEEDO AND DDO.LILG NOT IN ('GR','IM')  
	LEFT JOIN MAEEDOOB AS OBDO WITH (NOLOCK) ON 
		EDO.IDMAEEDO=OBDO.IDMAEEDO  
	LEFT JOIN MAEPR WITH (NOLOCK) ON 
		MAEPR.KOPR=DDO.KOPRCT  
	LEFT JOIN MAEEN WITH (NOLOCK) ON 
		MAEEN.KOEN=EDO.ENDO AND 
		MAEEN.SUEN=EDO.SUENDO  
	LEFT JOIN TABCT WITH (NOLOCK) ON 
		DDO.KOPRCT=TABCT.KOCT AND DDO.PRCT=1  
	LEFT JOIN TABSU WITH ( NOLOCK ) ON 
		TABSU.KOSU=EDO.SUDO
WHERE  
	EDO.EMPRESA='01'  AND 
	--#FILTRO_SUCURSALES#
	--#FILTRO_SUPER_FAMILIA# 
	EDO.TIDO IN ('GDV','GDP') AND 
	EDO.FEEMDO BETWEEN @Fecha_Inicio AND @Fecha_Fin AND 
	--EDO.NUDONODEFI=0  AND 
	EDO.ESDO<>'N' 
	
	
	ORDER BY EDO.IDMAEEDO 

ALTER TABLE #INFGUIAS ADD NOKOPRCT varchar(50) NULL,NOKOZO varchar(50) NULL,NOSUDO varchar(50) NULL,NOKOFU varchar(50) NULL,NOKOFUDO   varchar(50) NULL,NOBOSULI   varchar(50) NULL,NOKOEN     varchar(50) NULL,NORUEN     varchar(50) NULL,NOMRPR     varchar(50) NULL,NOFMPR     varchar(50) NULL,NOPFPR     varchar(50) NULL,NOHFPR     varchar(50) NULL,DEVOL1     float       NULL,DEVOL2     float       NULL,STOCKFIS   float       NULL,LISTACOST  char(8)     NULL,LISCOSMOD  float       NULL



--DROP TABLE #INFVEN

--UPDATE #INFGUIAS SET MONTO = ROUND(COSTO * MOVIMIENTO,2) 

--UPDATE #INFGUIAS SET COSTO = ISNULL((SELECT SUM(PPPRPM * CAPRCO1) FROM MAEDDO Do WHERE Do.IDMAEEDO = #INFGUIAS.IDMAEEDO),0)
UPDATE #INFGUIAS SET MARGEN = CASE WHEN NETO = 0 THEN 0 ELSE ((NETO-COSTO)/NETO) * 100 END 

--SELECT * FROM #INFGUIAS
--SELECT SUDO,NOKOSU,FEEMDO,COUNT(TIDO) AS GUIAS,SUM(NETO) AS MONTO FROM #INFGUIAS
--GROUP BY SUDO,NOKOSU,FEEMDO
--ORDER BY SUDO,NOKOSU,FEEMDO

SELECT SUDO,NOKOSU,COUNT(TIDO) AS GUIAS,SUM(COSTO) AS COSTO,SUM(NETO) AS MONTO,(SUM(NETO)-SUM(COSTO)) as MARGEN_V,(SUM(NETO)-SUM(COSTO))/SUM(NETO) AS MARGEN FROM #INFGUIAS
GROUP BY SUDO,NOKOSU
UNION
SELECT KOSU AS SUDO,NOKOSU,0 AS GUIAS,0 AS COSTO,0 AS MONTO, 0 AS MARGEN_V, 0 AS MARGEN FROM TABSU WHERE KOSU NOT IN  (SELECT SUDO FROM #INFGUIAS) 
ORDER BY SUDO,NOKOSU

--SELECT * FROM #INFGUIAS ORDER BY NUDO

DROP  TABLE #INFGUIAS 

--SELECT PPPRPM,PPPRNERE1,* FROM MAEDDO WHERE IDMAEEDO = 357111

--SELECT SUM(PPPRPM) FROM MAEDDO WHERE IDMAEEDO = 357111



