
DECLARE 

@Fecha_Inicio Date = '#Fecha_Inicio#', 
@Fecha_Fin    Date = '#Fecha_Fin#'
 


BEGIN TRY
 DROP TABLE #INFVEN
 END TRY
 BEGIN CATCH
END CATCH

SELECT  EDO.IDMAEEDO, DDO.IDMAEDDO, EDO.TIDO, EDO.NUDO, 
        EDO.ENDO,EDO.SUENDO,
        (SELECT TOP 1 NOKOEN FROM MAEEN WHERE KOEN = EDO.ENDO AND SUEN = EDO.SUENDO) AS RAZON,
        EDO.SUDO,TABSU.NOKOSU,EDO.FEEMDO, EDO.FEULVEDO, EDO.KOFUDO, EDO.MODO, EDO.TIMODO, 
		EDO.TAMODO,EDO.CAPRAD, EDO.CAPREX,EDO.VANEDO, EDO.VAIVDO, EDO.VABRDO,DDO.LILG, 
		DDO.NULIDO, DDO.SULIDO, DDO.LUVTLIDO, DDO.BOSULIDO, 
		DDO.KOFULIDO, 
		(SELECT TOP 1 NOKOFU FROM TABFU WHERE KOFU = DDO.KOFULIDO) AS VENDEDOR, 
		COALESCE(DDO.PRCT,0) AS PRCT, DDO.TICT, DDO.TIPR, DDO.NUSEPR, 
		DDO.KOPRCT, 
		DDO.NOKOPR,
		CASE
                   WHEN DDO.UDTRPR = 1 THEN
                        DDO.UD01PR
                   ELSE DDO.UD02PR
        END AS UD,
		DDO.UDTRPR, DDO.RLUDPR,
		CASE  
			WHEN DDO.PRCT = 1 THEN 0  
			WHEN EDO.TIDO IN ('GDV','GDP','GDD','GRC','GRP','GRI') AND DDO.PRCT = 0 THEN DDO.CAPRCO1-DDO.CAPREX1  
			WHEN EDO.TIDO IN ('NCV','NCC','NCX','NEV') AND DDO.PRCT = 0             THEN DDO.CAPRCO1*(-1)         
			ELSE DDO.CAPRCO1 
		END AS CAPRCO1,
			DDO.CAPRAD1, DDO.CAPREX1, DDO.CAPRNC1, DDO.UD01PR,
		CASE  
			WHEN DDO.PRCT = 1 THEN 0  
			WHEN EDO.TIDO IN ('GDV','GDP','GDD','GRC','GRP','GRI') AND DDO.PRCT = 0 THEN DDO.CAPRCO2-DDO.CAPREX2  
			WHEN EDO.TIDO IN ('NCV','NCC','NCX','NEV') AND DDO.PRCT = 0             THEN DDO.CAPRCO2*(-1)         
			ELSE DDO.CAPRCO2 
		END AS CAPRCO2,
		DDO.CAPRAD2, DDO.CAPREX2, DDO.CAPRNC2, DDO.UD02PR,DDO.PPPRNE, DDO.PPPRBR, 
		DDO.VANELI,
		DDO.VAIVLI,
		DDO.VAIMLI, 
		DDO.VABRLI, 
		DDO.FEEMLI, DDO.FEERLI, 
		DDO.PPPRPM, 
		(SELECT TOP 1 PM FROM MAEPREM WHERE EMPRESA = DDO.EMPRESA AND KOPR = DDO.KOPRCT) AS PM,
		DDO.PPPRPMIFRS, DDO.POTENCIA,DDO.ESLIDO, DDO.PPPRNERE1, DDO.PPPRNERE2,
		 (CASE DDO.PRCT 
			WHEN 1 THEN '_ct_' 
			ELSE COALESCE(MAEPR.FMPR,'') 
		  END) AS FMPR,
		COALESCE(MAEPR.MRPR,  '') AS MRPR,
		COALESCE(MAEEN.ZOEN,  '') AS ZOEN,
		COALESCE(MAEEN.RUEN,'') AS RUEN,
		COALESCE(TABCT.RECAPRRE,0) AS RECAPRRE,
		COALESCE(MAEPR.PFPR,'') AS PFPR,
		COALESCE(MAEPR.HFPR,'') AS HFPR,
		ROUND((DDO.PPPRPM * DDO.CAPRCO1) * 
			( CASE 
				WHEN EDO.TIDO IN ('NCV','NCX','NEV','NCC') THEN -1.0 
				ELSE 1.0 
			END ),2) AS COSTO,
		CASE  
			WHEN EDO.TIMODO='E' THEN DDO.VANELI*EDO.TAMODO* ( 
								CASE 
									WHEN EDO.TIDO IN ('NCV','NCX','NEV','NCC') THEN -1.0 
									ELSE 1.0 
								END )  
			ELSE DDO.VANELI * ( CASE 
									WHEN EDO.TIDO IN ('NCV','NCX','NEV','NCC') THEN -1.0 
									ELSE 1.0 
								END )  
		END AS MONTO,
		OBDO.OCDO 
INTO #INFVEN
FROM MAEEDO EDO WITH ( NOLOCK ) 
	LEFT JOIN MAEDDO AS DDO WITH (NOLOCK) ON 
		EDO.IDMAEEDO=DDO.IDMAEEDO AND DDO.LILG NOT IN ('GR','IM')  
	LEFT JOIN MAEEDOOB AS OBDO WITH (NOLOCK) ON 
		EDO.IDMAEEDO=OBDO.IDMAEEDO  
	LEFT JOIN MAEPR WITH (NOLOCK) ON 
		MAEPR.KOPR=DDO.KOPRCT  
	LEFT JOIN MAEEN WITH (NOLOCK) ON 
		MAEEN.KOEN=EDO.ENDO AND 
		MAEEN.SUEN=EDO.SUENDO  
	LEFT JOIN TABCT WITH (NOLOCK) ON 
		DDO.KOPRCT=TABCT.KOCT AND DDO.PRCT=1  
	LEFT JOIN TABSU WITH ( NOLOCK ) ON 
		TABSU.KOSU=EDO.SUDO
WHERE  
	  EDO.EMPRESA='01'  AND 
 	  EDO.TIDO IN ('BLV','BLX','BSV','ESC','FCV','FDB','FDV','FDX','FDZ','FEE','FEV','FVL','FVT','FVX',
				 'FVZ','FXV','FYV','NCE','NCV','NCX','NCZ','NEV','RIN') AND 
	  EDO.FEEMDO BETWEEN @Fecha_Inicio AND @Fecha_Fin AND 
	  --EDO.NUDONODEFI=0  AND 
	  EDO.ESDO<>'N'   
	  #Filtro_Externo#
	
	ORDER BY EDO.IDMAEEDO 

ALTER TABLE #INFVEN ADD NOKOZO varchar(50) NULL,NOSUDO varchar(50) NULL,NOKOFU varchar(50) NULL,NOKOFUDO   varchar(50) NULL,NOBOSULI   varchar(50) NULL,NOKOEN     varchar(50) NULL,NORUEN     varchar(50) NULL,NOMRPR     varchar(50) NULL,NOFMPR     varchar(50) NULL,NOPFPR     varchar(50) NULL,NOHFPR     varchar(50) NULL,DEVOL1     float       NULL,DEVOL2     float       NULL,STOCKFIS   float       NULL,LISTACOST  char(8)     NULL,LISCOSMOD  float       NULL

--UPDATE #INFVEN SET NOKOPRCT=NOKOPR FROM MAEDDO WITH (NOLOCK) WHERE MAEDDO.IDMAEDDO=#INFVEN.IDMAEDDO 
--UPDATE #INFVEN SET NOKOPRCT=NOKOCT FROM TABCT WITH (NOLOCK) WHERE TABCT.KOCT=#INFVEN.KOPRCT AND #INFVEN.PRCT = 1
UPDATE #INFVEN SET NOKOEN=(SELECT NOKOEN FROM MAEEN WITH (NOLOCK) WHERE MAEEN.KOEN=#INFVEN.ENDO AND MAEEN.SUEN=#INFVEN.SUENDO) 
UPDATE #INFVEN SET NOMRPR=TABMR.NOKOMR  FROM MAEPR WITH (NOLOCK)  LEFT JOIN TABMR WITH (NOLOCK) ON TABMR.KOMR=MAEPR.MRPR  WHERE MAEPR.KOPR=#INFVEN.KOPRCT 
UPDATE #INFVEN SET NOFMPR=TABFM.NOKOFM  FROM MAEPR WITH (NOLOCK)  LEFT JOIN TABFM WITH (NOLOCK) ON TABFM.KOFM=MAEPR.FMPR  WHERE MAEPR.KOPR=#INFVEN.KOPRCT  AND #INFVEN.PRCT=0 
UPDATE #INFVEN SET NOPFPR=TABPF.NOKOPF  FROM MAEPR WITH (NOLOCK)  LEFT JOIN TABPF WITH (NOLOCK) ON TABPF.KOFM=MAEPR.FMPR AND TABPF.KOPF=MAEPR.PFPR  WHERE MAEPR.KOPR=#INFVEN.KOPRCT  AND #INFVEN.PRCT=0 
UPDATE #INFVEN SET NOHFPR=TABHF.NOKOHF  FROM MAEPR WITH (NOLOCK)  LEFT JOIN TABHF WITH (NOLOCK) ON TABHF.KOFM=MAEPR.FMPR AND TABHF.KOPF=MAEPR.PFPR AND TABHF.KOHF=MAEPR.HFPR  WHERE MAEPR.KOPR=#INFVEN.KOPRCT  AND #INFVEN.PRCT=0 
UPDATE #INFVEN SET NOKOZO=TABZO.NOKOZO  FROM TABZO WITH (NOLOCK)  WHERE TABZO.KOZO=#INFVEN.ZOEN 
UPDATE #INFVEN SET NORUEN=TABRU.NOKORU  FROM MAEEN WITH (NOLOCK)  LEFT JOIN TABRU WITH (NOLOCK) ON TABRU.KORU=MAEEN.RUEN  WHERE MAEEN.KOEN=#INFVEN.ENDO  AND MAEEN.SUEN=#INFVEN.SUENDO 
UPDATE #INFVEN SET NOSUDO=TABSU.NOKOSU  FROM TABSU WITH (NOLOCK)  WHERE TABSU.KOSU=#INFVEN.SUDO 
UPDATE #INFVEN SET NOKOFUDO=TABFU.NOKOFU  FROM TABFU WITH (NOLOCK)  WHERE TABFU.KOFU=#INFVEN.KOFUDO 
UPDATE #INFVEN SET NOKOFU=TABFU.NOKOFU  FROM TABFU WITH (NOLOCK)  WHERE TABFU.KOFU=#INFVEN.KOFULIDO 
UPDATE #INFVEN SET NOBOSULI=TABBO.NOKOBO  FROM TABBO WITH (NOLOCK)  WHERE TABBO.KOBO=#INFVEN.BOSULIDO 
/*
SELECT TOP 20 #INFVEN.* FROM #INFVEN WITH ( NOLOCK )  ORDER BY #INFVEN.FEEMDO  OPTION ( FAST 20 ) 
SELECT TOP 20 #INFVEN.* FROM #INFVEN WITH ( NOLOCK )  ORDER BY #INFVEN.FEEMDO  OPTION ( FAST 20 ) 
*/

SELECT * FROM #INFVEN

-- ANUAL
SELECT SUDO,NOKOSU,ROUND(SUM(PM),0) AS PM,ROUND(SUM(MONTO) - SUM(PM),0) AS MARGEN,SUM(MONTO) AS MONTO 
FROM #INFVEN WITH ( NOLOCK )  
GROUP BY SUDO ,NOKOSU
ORDER BY SUDO,NOKOSU

Update #INFVEN Set VANELI = VANELI * -1,
                   VAIVLI = VAIVLI * -1,  
                   VAIMLI = VAIMLI * -1,
                   VABRLI = VABRLI * -1
Where TIDO In ('NCV','NCX','NEV','NCZ')  

SELECT KOPRCT,NOKOPR,TIDO,NUDO,FEEMLI AS FEEMDO,KOFULIDO,VENDEDOR, 
       UD,
       CASE
           WHEN UDTRPR = 1 THEN
                CAPRCO1
           ELSE CAPRCO2
       END AS CANTIDAD,
       PPPRNE,VANELI,VABRLI,ENDO,SUENDO,RAZON,IDMAEEDO,IDMAEDDO
FROM #INFVEN
Where 1 > 0

ORDER BY FEEMLI,IDMAEDDO
       
SELECT KOPRCT,NOKOPR,UD,
       SUM(CAPRCO1) AS CAPRCO1,SUM(CAPRCO2) AS CAPRCO2,PPPRNE,SUM(VANELI) AS VANELI,SUM(VABRLI) AS VABRLI FROM #INFVEN       
GROUP BY KOPRCT,NOKOPR,UD,PPPRNE


DROP TABLE #INFVEN