USE [#Base#]

CREATE TABLE [dbo].[Zw_Casi_DocObs](
	[Id_DocEnc]     [int] NOT NULL,
	[Observaciones] [varchar](250) NOT NULL DEFAULT (''),
	[Forma_pago]    [varchar](40) NOT NULL DEFAULT (''),
	[Orden_compra]  [varchar](40) NOT NULL DEFAULT (''),
	[Obs1]          [varchar](80) NOT NULL DEFAULT (''),
	[Obs2]          [varchar](80) NOT NULL DEFAULT (''),
	[Obs3]          [varchar](80) NOT NULL DEFAULT (''),
	[Obs4]          [varchar](80) NOT NULL DEFAULT (''),
	[Obs5]          [varchar](80) NOT NULL DEFAULT (''),
	[Obs6]          [varchar](80) NOT NULL DEFAULT (''),
	[Obs7]          [varchar](80) NOT NULL DEFAULT (''),
	[Obs8]          [varchar](80) NOT NULL DEFAULT (''),
	[Obs9]          [varchar](80) NOT NULL DEFAULT (''),
	[Obs10]         [varchar](80) NOT NULL DEFAULT (''),
	[Obs11]         [varchar](80) NOT NULL DEFAULT (''),
	[Obs12]         [varchar](80) NOT NULL DEFAULT (''),
	[Obs13]         [varchar](80) NOT NULL DEFAULT (''),
	[Obs14]         [varchar](80) NOT NULL DEFAULT (''),
	[Obs15]         [varchar](80) NOT NULL DEFAULT (''),
	[Obs16]         [varchar](80) NOT NULL DEFAULT (''),
	[Obs17]         [varchar](80) NOT NULL DEFAULT (''),
	[Obs18]         [varchar](80) NOT NULL DEFAULT (''),
	[Obs19]         [varchar](80) NOT NULL DEFAULT (''),
	[Obs20]         [varchar](80) NOT NULL DEFAULT (''),
	[Obs21]         [varchar](80) NOT NULL DEFAULT (''),
	[Obs22]         [varchar](80) NOT NULL DEFAULT (''),
	[Obs23]         [varchar](80) NOT NULL DEFAULT (''),
	[Obs24]         [varchar](80) NOT NULL DEFAULT (''),
	[Obs25]         [varchar](80) NOT NULL DEFAULT (''),
	[Obs26]         [varchar](80) NOT NULL DEFAULT (''),
	[Obs27]         [varchar](80) NOT NULL DEFAULT (''),
	[Obs28]         [varchar](80) NOT NULL DEFAULT (''),
	[Obs29]         [varchar](80) NOT NULL DEFAULT (''),
	[Obs30]         [varchar](80) NOT NULL DEFAULT (''),
	[Obs31]         [varchar](80) NOT NULL DEFAULT (''),
	[Obs32]         [varchar](80) NOT NULL DEFAULT (''),
	[Obs33]         [varchar](80) NOT NULL DEFAULT (''),
	[Obs34]         [varchar](80) NOT NULL DEFAULT (''),
	[Obs35]         [varchar](80) NOT NULL DEFAULT (''),
	[Placa]         [varchar](10) NOT NULL DEFAULT (''),
	[CodRetirador]  [varchar](13) NOT NULL DEFAULT (''),
 CONSTRAINT [PK_Zw_Casi_DocObs] PRIMARY KEY CLUSTERED 
(
	[Id_DocEnc] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
