USE [#Base#]


CREATE TABLE [dbo].[Zw_Casi_DocEnc](
	[Id_DocEnc]				[int] IDENTITY(1,1) NOT NULL,
	[Modalidad]             [varchar](5)	NOT NULL DEFAULT (''),
	[Empresa]               [varchar](2)	NOT NULL DEFAULT (''),
	[Sucursal]              [varchar](3)	NOT NULL DEFAULT (''),
	[TipoDoc]               [varchar](3)	NOT NULL DEFAULT (''),
	[NroDocumento]          [char](10)		NOT NULL DEFAULT (''),
	[CodEntidad]            [varchar](13)	NOT NULL DEFAULT (''),
	[CodSucEntidad]         [varchar](10)	NOT NULL DEFAULT (''),
	[Nombre_Entidad]        [varchar](50)	NOT NULL DEFAULT (''),
	[FechaEmision]          [datetime]		NULL,
	[Fecha_1er_Vencimiento] [datetime]		NULL,
	[FechaUltVencimiento]   [datetime]		NULL,
	[FechaRecepcion]        [datetime]		NULL,
	[Cuotas]                [int]			NOT NULL DEFAULT (0),
	[Dias_1er_Vencimiento]  [int]			NOT NULL DEFAULT (0),
	[Dias_Vencimiento]      [int]			NOT NULL DEFAULT (0),
	[ListaPrecios]          [varchar](50)	NOT NULL DEFAULT (''),
	[CodEntidadFisica]      [varchar](13)	NOT NULL DEFAULT (''),
	[CodSucEntidadFisica]   [varchar](50)	NOT NULL DEFAULT (''),
	[Nombre_Entidad_Fisica] [varchar](50)	NOT NULL DEFAULT (''),
	[Contacto_Ent]          [varchar](50)	NOT NULL DEFAULT (''),
	[CodFuncionario]        [varchar](3)	NOT NULL DEFAULT (''),
	[NomFuncionario]        [varchar](30)	NOT NULL DEFAULT (''),
	[Centro_Costo]          [varchar](8)	NOT NULL DEFAULT (''),
	[Moneda_Doc]            [varchar](3)	NOT NULL DEFAULT (''),
	[Valor_Dolar]           [float]			NOT NULL DEFAULT (0),
	[TotalNetoDoc]          [float]			NOT NULL DEFAULT (0),
	[TotalIvaDoc]           [float]			NOT NULL DEFAULT (0),
	[TotalIlaDoc]           [float]			NOT NULL DEFAULT (0),
	[TotalBrutoDoc]         [float]			NOT NULL DEFAULT (0),
	[CantTotal]             [float]			NOT NULL DEFAULT (0),
	[CantDesp]              [float]			NOT NULL DEFAULT (0),
	[DocEn_Neto_Bruto]      [char](1)		NOT NULL DEFAULT (''),
	[Es_ValeTransitorio]    [bit]			NOT NULL DEFAULT (0),
	[Es_Electronico]        [bit]			NOT NULL DEFAULT (0),
	[TipoMoneda]            [char](1)		NOT NULL DEFAULT (''),
	[Vizado]                [bit]			NOT NULL DEFAULT (0),
	[Fun_Auto_Deuda_Ven]    [varchar](3)	NOT NULL DEFAULT (''),
	[Id_DocEnc_Padre]       [int]			NOT NULL DEFAULT (0),
	[Bloquea_Doc]           [bit]			NOT NULL DEFAULT (0),
	[Fun_Auto_Stock_Ins]    [varchar](3)	NOT NULL DEFAULT (''),
	[Fun_Auto_Cupo_Exe]     [varchar](3)	NOT NULL DEFAULT (''),
	[SubTido]               [varchar](3)	NOT NULL DEFAULT (''),
	[Fun_Auto_Fecha_Des]    [varchar](3)	NOT NULL DEFAULT (''),
	[Stand_by]              [bit]			NOT NULL DEFAULT (0),
	[Fun_Auto_Sol_Compra]   [varchar](3)	NOT NULL DEFAULT (''),
	[Tasadorig_Doc]		    [float]			NOT NULL DEFAULT (0),
	[Reserva_NroOCC]	    [bit]			NOT NULL DEFAULT (0),
	[Reserva_Idmaeedo]	    [int]			NOT NULL DEFAULT (0),
    [Bodega_Destino]        [varchar](3)	NOT NULL DEFAULT (''),
    [RevFincred]	        [bit]			NOT NULL DEFAULT (0),
    [IdFincred]	            [int]			NOT NULL DEFAULT (0),
    [MontoFincred]	        [float]			NOT NULL DEFAULT (0),
    [TblTipoVenta]          [varchar](20)	NOT NULL DEFAULT (''),
    [CodTipoVenta]          [varchar](20)	NOT NULL DEFAULT (''),
    [Customizable]	        [bit]			NOT NULL DEFAULT (0),
    [PreVenta]              [bit]			NOT NULL DEFAULT (0),
    [Pickear]               [bit]			NOT NULL DEFAULT (0),
 CONSTRAINT [PK_Zw_Casi_DocEnc] PRIMARY KEY CLUSTERED 
(
	[Id_DocEnc] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
