USE [#Base#]


CREATE TABLE [dbo].[Zw_InterStock_Det](
	[Id_Enc]			[int]			NOT NULL DEFAULT (0),
	[Id_Det]			[int]			IDENTITY(1,1) NOT NULL,
	[Idmaeedo]			[int]			NOT NULL DEFAULT (0),
	[Idmaeddo]			[int]			NOT NULL DEFAULT (0),
	[Tido]				[char](3)		NOT NULL DEFAULT (''),
	[Nudo]				[char](10)		NOT NULL DEFAULT (''),
	[Endo]				[varchar](13)	NOT NULL DEFAULT (''),
	[Suendo]			[varchar](10)	NOT NULL DEFAULT (''),
	[Empresa]			[char](2)		NOT NULL DEFAULT (''),
	[Sucursal]			[char](3)		NOT NULL DEFAULT (''),
	[Bodega]			[char](3)		NOT NULL DEFAULT (''),
	[Codigo]			[varchar](13)	NOT NULL DEFAULT (''),
	[Caprco1]			[float]			NOT NULL DEFAULT (''),
	[Caprco2]			[float]			NOT NULL DEFAULT (''),
	[Stockinicialud1]	[float]			NOT NULL DEFAULT (''),
	[Stockinicialud2]	[float]			NOT NULL DEFAULT (''),
	[Stockantesud1]		[float]			NOT NULL DEFAULT (''),
	[Stockantesud2]		[float]			NOT NULL DEFAULT (''),
	[Stockdespuesud1]	[float]			NOT NULL DEFAULT (''),
	[Stockdespuesud2]	[float]			NOT NULL DEFAULT (''),
	[Ud1_negativo]		[bit]			NOT NULL DEFAULT (''),
	[Ud2_negativo]		[bit]			NOT NULL DEFAULT (''),
	[Comprarud1]		[float]			NOT NULL DEFAULT (''),
	[Comprarud2]		[float]			NOT NULL DEFAULT (''),
	[CodLista]			[varchar](3)	NOT NULL DEFAULT (''),
	[Costo]				[float]			NOT NULL DEFAULT (''),
	[Empresa_OCC]		[char](2)		NOT NULL DEFAULT (''),
	[Sucursal_OCC]		[varchar](3)	NOT NULL DEFAULT (''),
	[Bodega_OCC]		[varchar](3)	NOT NULL DEFAULT (''),
	[Idmaeedo_OCC]		[int]			NOT NULL DEFAULT (0),
	[Idmaeddo_OCC]		[int]			NOT NULL DEFAULT (0),
	[Tido_OCC]			[varchar](3)	NOT NULL DEFAULT (''),
	[Nudo_OCC]			[varchar](10)	NOT NULL DEFAULT (''),
	[Endo_OCC]			[varchar](13)	NOT NULL DEFAULT (''),
	[Suendo_OCC]		[varchar](10)	NOT NULL DEFAULT (''),
	[Empresa_NVV]		[char](2)		NOT NULL DEFAULT (''),
	[Sucursal_NVV]		[varchar](3)	NOT NULL DEFAULT (''),
	[Bodega_NVV]		[varchar](3)	NOT NULL DEFAULT (''),
	[Idmaeedo_NVV]		[int]			NOT NULL DEFAULT (0),
	[Idmaeddo_NVV]		[int]			NOT NULL DEFAULT (0),
	[Tido_NVV]			[char](3)		NOT NULL DEFAULT (''),
	[Nudo_NVV]			[varchar](10)	NOT NULL DEFAULT (''),
	[Endo_NVV]			[varchar](13)	NOT NULL DEFAULT (''),
	[Suendo_NVV]		[varchar](10)	NOT NULL DEFAULT (''),
	[Empresa_FCV]		[char](2)		NOT NULL DEFAULT (''),
	[Idmaeedo_FCV]		[int]			NOT NULL DEFAULT (0),
	[Idmaeddo_FCV]		[int]			NOT NULL DEFAULT (0),
	[Tido_FCV]			[char](3)		NOT NULL DEFAULT (''),
	[Nudo_FCV]			[varchar](50)	NOT NULL DEFAULT (''),
	[Empresa_FCC]		[char](2)		NOT NULL DEFAULT (''),
	[Idmaeedo_FCC]		[int]			NOT NULL DEFAULT (0),
	[Idmaeddo_FCC]		[int]			NOT NULL DEFAULT (0),
	[Tido_FCC]			[char](3)		NOT NULL DEFAULT (''),
	[Nudo_FCC]			[varchar](10)	NOT NULL DEFAULT (''),
 CONSTRAINT [PK_Zw_InterStock_Det] PRIMARY KEY CLUSTERED 
(
	[Id_Det] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
