USE [#Base#]

CREATE TABLE [dbo].[Zw_Inv_FotoInventario](
	[Id]				[int] IDENTITY(1,1) NOT NULL,
	[IdInventario]		[int]			NOT NULL DEFAULT (0),
	[Estado]			[bit]			NOT NULL DEFAULT (0),
	[Empresa]			[char](2)		NOT NULL DEFAULT (''),
	[Sucursal]			[char](3)		NOT NULL DEFAULT (''),
	[Bodega]			[char](3)		NOT NULL DEFAULT (''),
	[Tipr]				[char](3)		NOT NULL DEFAULT (''),
	[Codigo]			[varchar](13)	NOT NULL DEFAULT (''),
	[CodigoRap]			[varchar](6)	NOT NULL DEFAULT (''),
	[CodigoTec]			[varchar](20)	NOT NULL DEFAULT (''),
	[Descripcion]		[varchar](50)	NOT NULL DEFAULT (''),
	[StFisicoUd1]		[float]			NOT NULL DEFAULT (0),
	[StFisicoUd2]		[float]			NOT NULL DEFAULT (0),
	[Cant_Inventariada] [float]			NOT NULL DEFAULT (0),
	[Dif_Inv_Cantidad]	[float]			NOT NULL DEFAULT (0),
	[Dif_Inv_Costo]		[float]			NOT NULL DEFAULT (0),
	[Costo]				[float]			NOT NULL DEFAULT (0),
	[PPP]				[float]			NOT NULL DEFAULT (0),
	[PUltCompra]		[float]			NOT NULL DEFAULT (0),
	[PLCostoPR]			[float]			NOT NULL DEFAULT (0),
	[Total_Costo_Foto]	[float]			NOT NULL DEFAULT (0),
	[Total_Costo_Inv]	[float]			NOT NULL DEFAULT (0),
	[FechaFoto]			[datetime]		NULL,
	[HoraFoto]			[datetime]		NULL,
	[Recontado]			[bit]			NOT NULL DEFAULT (0),
	[Cerrado]			[bit]			NOT NULL DEFAULT (0),
	[Levantado]			[bit]			NOT NULL DEFAULT (0),
	[Diferencia]		[varchar](20)	NOT NULL DEFAULT (''),
	[NoInventariar]		[bit]			NOT NULL DEFAULT (0),
	[IdHojaUltReconteo] [int]			NOT NULL DEFAULT (0),
	[SuperFamilia]		[varchar](4)	NOT NULL DEFAULT (''),
	[Familia]			[varchar](4)	NOT NULL DEFAULT (''),
	[SubFamilia]		[varchar](4)	NOT NULL DEFAULT (''),
	[Nom_SuperFamilia]	[varchar](50)	NOT NULL DEFAULT (''),
	[Nom_Familia]		[varchar](50)	NOT NULL DEFAULT (''),
	[Nom_SubFamilia]	[varchar](50)	NOT NULL DEFAULT (''),
	[Marca]				[varchar](20)	NOT NULL DEFAULT (''),
	[Nom_Marca]			[varchar](50)	NOT NULL DEFAULT (''),
	[Rubro]				[varchar](3)	NOT NULL DEFAULT (''),
	[Nom_Rubro]			[varchar](50)	NOT NULL DEFAULT (''),
	[ClasLibre]			[varchar](20)	NOT NULL DEFAULT (''),
	[Nom_ClasLibre]		[varchar](50)	NOT NULL DEFAULT (''),
	[Zona]				[varchar](10)	NOT NULL DEFAULT (''),
	[Nom_Zona]			[varchar](50)	NOT NULL DEFAULT ('')
) ON [PRIMARY]

