USE [#Base#]


CREATE TABLE [dbo].[Zw_Prod_Archivos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Codigo] [varchar](13) NOT NULL DEFAULT (''),
	[Nombre_Archivo] [varchar](200) NOT NULL DEFAULT (''),
	[Archivo] [image] NULL,
 CONSTRAINT [PK_Zw_Prod_Archivos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]



