USE [#Base#]


CREATE TABLE [dbo].[Zw_St_OT_Encabezado](
	[Id_Ot]                                 [int] IDENTITY(1,1) NOT NULL,
	[Nro_Ot]                                [varchar](13)       NOT NULL DEFAULT (''),
	[Sub_Ot]                                [varchar](3)        NOT NULL DEFAULT (''),
	[Id_Ot_Padre]                           [int]               NOT NULL DEFAULT (0),
	[Empresa]                               [char](2)           NOT NULL DEFAULT (''),
	[Sucursal]                              [char](3)           NOT NULL DEFAULT (''),
	[Bodega]                                [char](3)           NOT NULL DEFAULT (''),
	[CodEntidad]                            [varchar](13)       NOT NULL DEFAULT (''),
	[SucEntidad]                            [varchar](10)       NOT NULL DEFAULT (''),
	[Rten]                                  [varchar](13)       NOT NULL DEFAULT (''),
	[Rut]                                   [varchar](13)       NOT NULL DEFAULT (''),
	[Fecha_Ingreso]                         [datetime]          NULL,
	[Fecha_Compromiso]                      [datetime]          NULL,
	[Fecha_Entrega]                         [datetime]          NULL,
	[Fecha_Cierre]                          [datetime]          NULL,
	[CodEstado]                             [char](2)           NOT NULL DEFAULT ('P'),
	[CodMaquina]                            [varchar](10)       NOT NULL DEFAULT (''),
	[CodMarca]                              [varchar](20)       NOT NULL DEFAULT (''),
	[CodModelo]                             [varchar](10)       NOT NULL DEFAULT (''),
	[CodCategoria]                          [varchar](10)       NOT NULL DEFAULT (''),
	[NroSerie]                              [varchar](50)       NOT NULL DEFAULT (''),
	[NroOcc_Cliente]                        [varchar](20)       NOT NULL DEFAULT (''),
	[Chk_Serv_Domicilio]                    [bit]               NOT NULL DEFAULT (0),
	[Pais]                                  [varchar](3)        NOT NULL DEFAULT (''),
	[Ciudad]                                [varchar](3)        NOT NULL DEFAULT (''),
	[Comuna]                                [varchar](3)        NOT NULL DEFAULT (''),
	[Direccion]                             [varchar](50)       NOT NULL DEFAULT (''),
	[Nombre_Contacto]                       [varchar](50)       NOT NULL DEFAULT (''),
	[Telefono_Contacto]                     [varchar](20)       NOT NULL DEFAULT (''),
	[Email_Contacto]                        [varchar](50)       NOT NULL DEFAULT (''),
	[Chk_Serv_Reparacion_Stock]             [bit]               NOT NULL DEFAULT (0),
	[Chk_Serv_Mantenimiento_Correctivo]     [bit]               NOT NULL DEFAULT (0),
	[Chk_Serv_Presupuesto_Pre_Aprobado]     [bit]               NOT NULL DEFAULT (0),
	[Chk_Serv_Recoleccion]                  [bit]               NOT NULL DEFAULT (0),
	[Chk_Serv_Mantenimiento_Preventivo]     [bit]               NOT NULL DEFAULT (0),
	[Chk_Serv_Garantia]                     [bit]               NOT NULL DEFAULT (0),
	[Chk_Serv_Demostracion_Maquina]         [bit]               NOT NULL DEFAULT (0),
	[CodTecnico_Asignado]                   [char](3)           NOT NULL DEFAULT (''),
	[CodTecnico_Repara]                     [char](3)           NOT NULL DEFAULT (''),
	[Horas_Mano_de_Obra_Asignado]           [float]             NOT NULL DEFAULT (0),
	[Horas_Mano_de_Obra_Repara]             [float]             NOT NULL DEFAULT (0),
	[Chk_Equipo_Reparado]                   [bit]               NOT NULL DEFAULT (0),
	[Idmaeedo_COV]                          [int]               NOT NULL DEFAULT (0),
	[Nudo_COV]                              [varchar](10)       NOT NULL DEFAULT (''),
	[Neto]                                  [float]             NOT NULL DEFAULT (0),
	[Iva]                                   [float]             NOT NULL DEFAULT (0),
	[Total]                                 [float]             NOT NULL DEFAULT (0),
	[Cod_Estado_Entrega]                    [varchar](10)       NOT NULL DEFAULT (''),
	[Chk_Equipo_Abandonado_Por_El_Cliente]  [bit]               NOT NULL DEFAULT (0),
	[Chk_No_Existe_COV_Ni_NVV]              [bit]               NOT NULL DEFAULT (0),
	[Codigo]                                [char](13)          NOT NULL DEFAULT (''),
	[Descripcion]                           [varchar](50)       NOT NULL DEFAULT (''),
	[Idmaeedo_GRP_PRE]                      [int]               NOT NULL DEFAULT (0),
	[Idmaeedo_GDP_PRE]                      [int]               NOT NULL DEFAULT (0),
 CONSTRAINT [PK_Zw_St_OT_Encabezado] PRIMARY KEY CLUSTERED 
(
	[Id_Ot] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


