USE [#Base#]

CREATE TABLE [dbo].[Zw_Stk_Grupos](
	[Id]		[int]			IDENTITY(1,1) NOT NULL,
	[Grupo]		[varchar](80)	NOT NULL DEFAULT (''),
	[Id_Area]	[int]			NOT NULL DEFAULT (0),
	[Id_Tipo]	[int]			NOT NULL DEFAULT (0),
 CONSTRAINT [PK_Zw_Stk_Grupos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]



