
Declare 

@TIPR char(3),
@KOPR char(13),
@NOKOPR varchar(50),
@KOPRRA char(6),
@NOKOPRRA varchar(20),
@KOPRTE char(20),
@KOGE char(13),
@NMARCA char(1),
@UD01PR char(2),
@UD02PR char(2),
@RLUD float,
@POIVPR float,
@NUIMPR float,
@RGPR char(1),
@STMIPR float,
@STMAPR float,
@MRPR char(20),
@ATPR char(3),
@RUPR char(3),
@STFI1 float,
@STDV1 float,
@STOCNV1 float,
@STFI2 float,
@STDV2 float,
@STOCNV2 float,
@PPUL01 float,
@PPUL02 float,
@MOUL char(3),
@TIMOUL char(1),
@TAUL float,
@FEUL datetime,
@PM float,
@FEPM datetime,
@FMPR char(4),
@PFPR char(4),
@HFPR char(4),
@VALI float,
@FEVALI datetime,
@TTREPR float,
@PRRG bit,
@NIPRRG char(5),
@NFPRRG char(5),
@PMIN float,
@CAMICO float,
@CAMIFA float,
@LOMIFA float,
@PLANO varchar(25),
@STDV1C float,
@STOCNV1C float,
@STDV2C float,
@STOCNV2C float,
@METRCO char(3),
@DESPNOFAC1 float,
@DESPNOFAC2 float,
@RECENOFAC1 float,
@RECENOFAC2 float,
@TRATALOTE bit,
@DIVISIBLE char(1),
@MUDEFA float,
@EXENTO bit,
@KOMODE char(13),
@PRDESRES bit,
@LISCOSTO char(8),
@STOCKASEG bit,
@ESACTFI bit,
@CLALIBPR char(10),
@KOFUPR char(3),
@KOPRDIM char(13),
@NODIM1 char(10),
@NODIM2 char(10),
@NODIM3 char(10),
@BLOQUEAPR char(1),
@ZONAPR char(10),
@CONUBIC bit,
@LTSUBIC float,
@PESOUBIC float,
@FUNCLOTE char(1),
@LOMAFA float,
@COLEGPR char(5),
@MORGPR char(3),
--@FECRPR datetime,
@FEMOPR datetime,
@LOTECAJA bit,
@STTR1 float,
@STTR2 float,
@PODEIVPR float,
@DIVISIBLE2 char(1),
@MOVETIQ bit,
@REPUESTO char(1),
@VIDAMEDIA float,
@TRATVMEDIA bit,
@PRESALCLI1 float,
@PRESALCLI2 float,
@PRESDEPRO1 float,
@PRESDEPRO2 float,
@CONSALCLI1 float,
@CONSALCLI2 float,
@CONSDEPRO1 float,
@CONSDEPRO2 float,
@DEVENGNCV1 float,
@DEVENGNCV2 float,
@DEVENGNCC1 float,
@DEVENGNCC2 float,
@DEVSINNCV1 float,
@DEVSINNCV2 float,
@DEVSINNCC1 float,
@DEVSINNCC2 float,
@STENFAB1 float,
@STENFAB2 float,
@STREQFAB1 float,
@STREQFAB2 float,
@PMME float,
@FEPMME datetime,
@VALUNFLEKM float,
@ANALIZABLE bit,
@TOLELOTE float,
@PMIFRS float,
@FEPMIFRS datetime


Select
@TIPR = '#tipr#',
@KOPR = '#kopr#',
@NOKOPR = '#nokopr#',
@KOPRRA = '#koprra#',
@NOKOPRRA = '#nokoprra#',
@KOPRTE = '#koprte#',
@KOGE = '#koge#',
@NMARCA = '#nmarca#',
@UD01PR = '#ud01pr#',
@UD02PR = '#ud02pr#',
@RLUD = #rlud#,
@POIVPR = #poivpr#,
@NUIMPR = #nuimpr#,
@RGPR = '#rgpr#',
@STMIPR = #stmipr#,
@STMAPR = #stmapr#,
@MRPR = '#mrpr#',
@ATPR = '#atpr#',
@RUPR = '#rupr#',
@STFI1 = #stfi1#,
@STDV1 = #stdv1#,
@STOCNV1 = #stocnv1#,
@STFI2 = #stfi2#,
@STDV2 = #stdv2#,
@STOCNV2 = #stocnv2#,
@PPUL01 = #ppul01#,
@PPUL02 = #ppul02#,
@MOUL = '#moul#',
@TIMOUL = '#timoul#',
@TAUL = #taul#,
@FEUL = '#feul#',
@PM = #pm#,
@FEPM = '#fepm#',
@FMPR = '#fmpr#',
@PFPR = '#pfpr#',
@HFPR = '#hfpr#',
@VALI = #vali#,
@FEVALI = '#fevali#',
@TTREPR = #ttrepr#,
@PRRG = #prrg#,
@NIPRRG = '#niprrg#',
@NFPRRG = '#nfprrg#',
@PMIN = #pmin#,
@CAMICO = #camico#,
@CAMIFA = #camifa#,
@LOMIFA = #lomifa#,
@PLANO = '#plano#',
@STDV1C = #stdv1c#,
@STOCNV1C = #stocnv1c#,
@STDV2C = #stdv2c#,
@STOCNV2C = #stocnv2c#,
@METRCO = '#metrco#',
@DESPNOFAC1 = #despnofac1#,
@DESPNOFAC2 = #despnofac2#,
@RECENOFAC1 = #recenofac1#,
@RECENOFAC2 = #recenofac2#,
@TRATALOTE = #tratalote#,
@DIVISIBLE = '#divisible#',
@MUDEFA = #mudefa#,
@EXENTO = #exento#,
@KOMODE = '#komode#',
@PRDESRES = #prdesres#,
@LISCOSTO = '#liscosto#',
@STOCKASEG = #stockaseg#,
@ESACTFI = #esactfi#,
@CLALIBPR = '#clalibpr#',
@KOFUPR = '#kofupr#',
@KOPRDIM = '#koprdim#',
@NODIM1 = '#nodim1#',
@NODIM2 = '#nodim2#',
@NODIM3 = '#nodim3#',
@BLOQUEAPR = '#bloqueapr#',
@ZONAPR = '#zonapr#',
@CONUBIC = #conubic#,
@LTSUBIC = #ltsubic#,
@PESOUBIC = #pesoubic#,
@FUNCLOTE = '#funclote#',
@LOMAFA = #lomafa#,
@COLEGPR = '#colegpr#',
@MORGPR = '#morgpr#',
--@FECRPR = '#fecrpr#',
@FEMOPR = '#femopr#',
@LOTECAJA = #lotecaja#,
@STTR1 = #sttr1#,
@STTR2 = #sttr2#,
@PODEIVPR = #podeivpr#,
@DIVISIBLE2 = '#divisible2#',
@MOVETIQ = #movetiq#,
@REPUESTO = '#repuesto#',
@VIDAMEDIA = #vidamedia#,
@TRATVMEDIA = #tratvmedia#,
@PRESALCLI1 = #presalcli1#,
@PRESALCLI2 = #presalcli2#,
@PRESDEPRO1 = #presdepro1#,
@PRESDEPRO2 = #presdepro2#,
@CONSALCLI1 = #consalcli1#,
@CONSALCLI2 = #consalcli2#,
@CONSDEPRO1 = #consdepro1#,
@CONSDEPRO2 = #consdepro2#,
@DEVENGNCV1 = #devengncv1#,
@DEVENGNCV2 = #devengncv2#,
@DEVENGNCC1 = #devengncc1#,
@DEVENGNCC2 = #devengncc2#,
@DEVSINNCV1 = #devsinncv1#,
@DEVSINNCV2 = #devsinncv2#,
@DEVSINNCC1 = #devsinncc1#,
@DEVSINNCC2 = #devsinncc2#,
@STENFAB1 = #stenfab1#,
@STENFAB2 = #stenfab2#,
@STREQFAB1 = #streqfab1#,
@STREQFAB2 = #streqfab2#,
@PMME = #pmme#,
@FEPMME = '#fepmme#',
@VALUNFLEKM = #valunflekm#,
@ANALIZABLE = #analizable#,
@TOLELOTE = #tolelote#,
@PMIFRS = #pmifrs#,
@FEPMIFRS = '#fepmifrs#'


Update MAEPR Set 
TIPR = @TIPR,
NOKOPR = @NOKOPR,
KOPRRA = @KOPRRA,
NOKOPRRA = @NOKOPRRA,
KOPRTE = @KOPRTE,
KOGE = @KOGE,
NMARCA = @NMARCA,
UD01PR = @UD01PR,
UD02PR = @UD02PR,
RLUD = @RLUD,
POIVPR = @POIVPR,
NUIMPR = @NUIMPR,
RGPR = @RGPR,
STMIPR = @STMIPR,
STMAPR = @STMAPR,
MRPR = @MRPR,
ATPR = @ATPR,
RUPR = @RUPR,
STFI1 = @STFI1,
STDV1 = @STDV1,
STOCNV1 = @STOCNV1,
STFI2 = @STFI2,
STDV2 = @STDV2,
STOCNV2 = @STOCNV2,
PPUL01 = @PPUL01,
PPUL02 = @PPUL02,
MOUL = @MOUL,
TIMOUL = @TIMOUL,
TAUL = @TAUL,
FEUL = @FEUL,
PM = @PM,
FEPM = @FEPM,
FMPR = @FMPR,
PFPR = @PFPR,
HFPR = @HFPR,
VALI = @VALI,
FEVALI = @FEVALI,
TTREPR = @TTREPR,
PRRG = @PRRG,
NIPRRG = @NIPRRG,
NFPRRG = @NFPRRG,
PMIN = @PMIN,
CAMICO = @CAMICO,
CAMIFA = @CAMIFA,
LOMIFA = @LOMIFA,
PLANO = @PLANO,
STDV1C = @STDV1C,
STOCNV1C = @STOCNV1C,
STDV2C = @STDV2C,
STOCNV2C = @STOCNV2C,
METRCO = @METRCO,
DESPNOFAC1 = @DESPNOFAC1,
DESPNOFAC2 = @DESPNOFAC2,
RECENOFAC1 = @RECENOFAC1,
RECENOFAC2 = @RECENOFAC2,
TRATALOTE = @TRATALOTE,
DIVISIBLE = @DIVISIBLE,
MUDEFA = @MUDEFA,
EXENTO = @EXENTO,
KOMODE = @KOMODE,
PRDESRES = @PRDESRES,
LISCOSTO = @LISCOSTO,
STOCKASEG = @STOCKASEG,
ESACTFI = @ESACTFI,
CLALIBPR = @CLALIBPR,
KOFUPR = @KOFUPR,
KOPRDIM = @KOPRDIM,
NODIM1 = @NODIM1,
NODIM2 = @NODIM2,
NODIM3 = @NODIM3,
BLOQUEAPR = @BLOQUEAPR,
ZONAPR = @ZONAPR,
CONUBIC = @CONUBIC,
LTSUBIC = @LTSUBIC,
PESOUBIC = @PESOUBIC,
FUNCLOTE = @FUNCLOTE,
LOMAFA = @LOMAFA,
COLEGPR = @COLEGPR,
MORGPR = @MORGPR,
--FECRPR = @FECRPR,
FEMOPR = @FEMOPR,
LOTECAJA = @LOTECAJA,
STTR1 = @STTR1,
STTR2 = @STTR2,
PODEIVPR = @PODEIVPR,
DIVISIBLE2 = @DIVISIBLE2,
MOVETIQ = @MOVETIQ,
REPUESTO = @REPUESTO,
VIDAMEDIA = @VIDAMEDIA,
TRATVMEDIA = @TRATVMEDIA,
PRESALCLI1 = @PRESALCLI1,
PRESALCLI2 = @PRESALCLI2,
PRESDEPRO1 = @PRESDEPRO1,
PRESDEPRO2 = @PRESDEPRO2,
CONSALCLI1 = @CONSALCLI1,
CONSALCLI2 = @CONSALCLI2,
CONSDEPRO1 = @CONSDEPRO1,
CONSDEPRO2 = @CONSDEPRO2,
DEVENGNCV1 = @DEVENGNCV1,
DEVENGNCV2 = @DEVENGNCV2,
DEVENGNCC1 = @DEVENGNCC1,
DEVENGNCC2 = @DEVENGNCC2,
DEVSINNCV1 = @DEVSINNCV1,
DEVSINNCV2 = @DEVSINNCV2,
DEVSINNCC1 = @DEVSINNCC1,
DEVSINNCC2 = @DEVSINNCC2,
STENFAB1 = @STENFAB1,
STENFAB2 = @STENFAB2,
STREQFAB1 = @STREQFAB1,
STREQFAB2 = @STREQFAB2,
PMME = @PMME,
FEPMME = @FEPMME,
VALUNFLEKM = @VALUNFLEKM,
ANALIZABLE = @ANALIZABLE,
TOLELOTE = @TOLELOTE,
PMIFRS = @PMIFRS,
FEPMIFRS = @FEPMIFRS

Where KOPR = @KOPR

