SELECT  Top 1
        KOEN As 'CodEntidad', 
        TIEN As 'Tipo_Entidad', 
        RTEN As 'Rut', 
        SUEN As 'SucEntidad', 
        TIPOSUC As 'Tipo_Sucursal', 
        NOKOEN As 'Razon_Social', 
        SIEN As 'Sigla', 
        GIEN As 'Giro', 
        (Select top 1 NOKOPA From TABPA Where TABPA.KOPA = MAEEN.PAEN) As 'Pais', 
        (Select top 1 NOKOCI From TABCI Where TABCI.KOPA = MAEEN.PAEN And TABCI.KOCI = MAEEN.CIEN) As 'Ciudad',
        (Select top 1 NOKOCM From TABCM 
                      Where TABCM.KOPA = MAEEN.PAEN And TABCM.KOCI = MAEEN.CIEN And TABCM.KOCM = MAEEN.CMEN) As 'Comuna',
        DIEN As 'Direccion', 
        (Select Top 1 NOKOZO From TABZO Where TABZO.KOZO = MAEEN.ZOEN) As 'Zona', 
        FOEN As 'Telefono', 
        FAEN As 'Fax', 
        CNEN As 'Cod_Pago', 
        KOFUEN As 'Vendedor', 
        LCEN As 'Lista_Costo', 
        LVEN As 'Lista_Precio', 
        CRSD As 'Credito_Sin_Documentar', 
        CRCH As 'Credito_Cheques', 
        CRLT As 'Credito_Letras', 
        CRPA As 'Credito_Pagare', 
        CRTO As 'Credito_Total', 
        CREN, 
        EMAIL As 'Email_1', 
        EMAILCOMER AS 'Email_2',
        CNEN2, 
        COBRADOR As 'Cobrador', 
        PROTEACUM, PROTEVIGE, 
        CPOSTAL As 'CodPostal', 
        HABILITA, CODCONVE, NOTRAEDEUD, 
        NOKOENAMP As 'Razon_Ampliada', 
        BLOQUEADO, DIMOPER, PREFEN, 
        BLOQENCOM, TIPOEN, ACTIEN, TAMAEN, PORPREFEN, 
        CLAVEEN, NVVPIDEPIE, RECEPELECT, ACTECO, DIASVENCI, CATTRIB, AGRETIVA, AGRETIIBB, AGRETGAN, 
        AGPERIVA, AGPERIIBB, TRANSPOEN, FECREEN, FIRMA, MOCTAEN, CTASDELAEN, 
        NACIONEN, DIRPAREN, FECNACEN, ESTCIVEN, PROFECEN, CONYUGEN, RUTCONEN,
        RUTSOCEN, SEXOEN, RELACIEN, ANEXEN1, ANEXEN2, ANEXEN3, ANEXEN4, OCCOBLI, VALIVENPAG, 
        TIPOCONTR, FEREFAUTO, DIACOBRA, CUENTABCO, KOENDPEN, SUENDPEN, RUTALUN, 
        RUTAMAR, RUTAMIE, RUTAJUE, RUTAVIE, RUTASAB, RUTADOM, CATLEGRET, IMPTORET, 
        ENTILIGA, PORCELIGA, ACTECOBCO, NVVOBLI, SECUECOM, SECUEVEN, AVISADPVEN
FROM         MAEEN

