
SELECT IDMAEEDO AS _ID,TIDO,NUDO,VABRDO,VAABDO,VABRDO-VAABDO AS SALDO,CAST(0 AS FLOAT) AS VAVE,CAST(0 AS FLOAT) AS VAABVE  
INTO #PASO_EDO
FROM MAEEDO
WHERE ROUND(VABRDO-VAABDO,0) > 0 AND TIDO  IN ('FCV','BLC','FCC','BLV')
#Filtro_Entidad#

SELECT IDMAEEDO AS ID, SUM(VAVE) AS VAVE, SUM(VAABVE) AS VAABVE
INTO #PASO_MAE
FROM MAEVEN WHERE IDMAEEDO IN (SELECT _ID FROM #PASO_EDO)
GROUP BY IDMAEEDO

UPDATE #PASO_EDO SET VAVE = (SELECT VAVE FROM #PASO_MAE WHERE _ID = ID)
UPDATE #PASO_EDO SET VAABVE = (SELECT VAABVE FROM #PASO_MAE WHERE _ID = ID)

SELECT *,(VAABDO-VAABVE) AS ABONAR INTO #PASO FROM #PASO_EDO 
WHERE SALDO <> VAVE AND VAABDO-VAABVE > 0

SELECT * FROM #PASO

--SELECT * FROM MAEVEN WHERE IDMAEEDO = 554841

--SELECT *,(SELECT ABONAR FROM #PASO WHERE _ID = IDMAEEDO ) AS ABONAR ,(SELECT ABONAR FROM #PASO WHERE _ID = IDMAEEDO )-VAVE
--FROM MAEVEN 
--WHERE IDMAEEDO IN (SELECT _ID FROM #PASO) AND ESPGVE = ''

DROP TABLE #PASO
DROP TABLE #PASO_EDO
DROP TABLE #PASO_MAE
