

SELECT *,
       (SELECT TOP 1 RTEN FROM MAEEN WHERE KOEN = ENDO AND SUEN = SUENDO) AS RTEN,
       (SELECT TOP 1 NOKOEN FROM MAEEN WHERE KOEN = ENDO AND SUEN = SUENDO) AS RAZON,
       KOFUDO,(SELECT TOP 1 NOKOFU FROM TABFU WHERE KOFU = KOFUDO) AS FUNCIONARIO
       FROM MAEEDO 
       WHERE IDMAEEDO = #Idmaeedo#


SELECT 
       --DO.KOPRCT AS KOPR, 
       DO.*,
       (SELECT TOP 1 KOPRTE FROM MAEPR WHERE KOPR = DO.KOPRCT) AS KOPRTE,
       NOKOPR,
       CASE UDTRPR 
           WHEN 1 THEN UD01PR 
           ELSE UD02PR 
           END AS UD,
       CASE UDTRPR 
           WHEN 1 THEN CAPRCO1 
           ELSE CAPRCO2
           END AS CANT,
     (SELECT TOP 1 DATOSUBIC FROM TABBOPR WHERE EMPRESA = DO.EMPRESA AND KOSU = DO.SULIDO AND KOBO = DO.BOSULIDO AND KOPR = DO.KOPRCT) 
     AS UBICACION,    
     CASE UDTRPR 
           WHEN 1 THEN 
           (SELECT TOP 1 STFI1 FROM MAEST WHERE EMPRESA = DO.EMPRESA AND KOSU = DO.SULIDO AND KOBO = DO.BOSULIDO AND KOPR = DO.KOPRCT)
           ELSE 
           (SELECT TOP 1 STFI2 FROM MAEST WHERE EMPRESA = DO.EMPRESA AND KOSU = DO.SULIDO AND KOBO = DO.BOSULIDO AND KOPR = DO.KOPRCT)
        END AS STOCK 
        
     FROM MAEDDO DO
WHERE IDMAEEDO = #Idmaeedo# AND 
      PRCT = 0 AND 
      TICT = ''     
#Orden_Detalle#
--

SELECT * FROM MAEEDOOB WHERE IDMAEEDO = #Idmaeedo#

SELECT DISTINCT TIDOPA,NUDOPA FROM MAEDDO WHERE IDMAEEDO = #Idmaeedo#