Declare @Empresa Char(2),
        @Periodo Char(4),
        @Grancue Char(2),
        @Mayor Char(3),
        @Cuenta Char(3),
        @Subauxi Varchar(13),
        @FechaDesde Datetime,
        @FechaHasta Datetime

Select @Empresa = '#Empresa#',@Periodo = '#Periodo#',@Grancue = '#Grancue#',@Mayor = '#Mayor#',@Cuenta = '#Cuenta#',@Subauxi = '#Subauxi#'
Select @FechaDesde = '#FechaDesde#', @FechaHasta = '#FechaHasta#'

Select Cast(0 As Bit) As Incluir,CCOMPRE.PERIODO,CCOMPRE.EMPRESA,CCOMPRE.NUMECOM,CCOMPRE.FECHCOM,CCOMPRD.GRADODET,CCOMPRD.ANALISIS,CCOMPRD.IDCOMPRD,CCOMPRD1.IDCOMPRD1,
		CCOMPRD1.SUBDEBE,CCOMPRD1.SUBHABER,CCOMPRD1.ANALISIS1,CCOMPRD1.ARCHIRST,CCOMPRD1.CAMPORST,CCOMPRD1.SUBGLOSA,MAEDPCE.IDMAEDPCE,MAEDPCE.TIDP,
		MAEDPCE.NUDP,MAEDPCE.ENDP,Isnull((Select Top 1 NOKOEN From MAEEN Where KOEN = MAEDPCE.ENDP),'') As 'NomCliente',
        MAEDPCE.FEEMDP,MAEDPCE.FEVEDP,MAEDPCE.VADP,MAEDPCE.VAABDP,MAEDPCE.ESPGDP,MAEDPCE.EMDP,MAEDPCE.CUDP,MAEDPCE.NUCUDP, 
		MAEDPCE.TIMODP,MAEDPCE.MODP,MAEDPCE.TAMODP,MAEDPCE.VAVUDP,
		MAEDPCE.HORAGRAB,Convert(Nvarchar, Convert(Datetime, (MAEDPCE.HORAGRAB*1.0/3600)/24), 108) As HORA,MAEEN.NOKOEN   
From CCOMPRD With (Nolock)  
	Inner Join CCOMPRE On CCOMPRD.IDCOMPRE=CCOMPRE.IDCOMPRE  
		Left Join CCOMPRD1 On CCOMPRD.IDCOMPRD=CCOMPRD1.IDCOMPRD  
			Inner Join MAEDPCE On CCOMPRD1.IDRST=MAEDPCE.IDMAEDPCE And CCOMPRD1.ARCHIRST='MAEDPCE '  
				Left Join MAEEN On MAEEN.KOEN=MAEDPCE.ENDP And MAEEN.TIPOSUC='P'  
Where 
CCOMPRE.EMPRESA = @Empresa  
And CCOMPRD.GRANCUE = @Grancue
And CCOMPRD.MAYOR  = @Mayor
And CCOMPRD.CUENTA = @Cuenta
And CCOMPRD.SUBAUXI = @Subauxi
And CCOMPRD.HABER = 0  
And CCOMPRE.PERIODO = @Periodo
And MAEDPCE.FEVEDP Between @FechaDesde And @FechaHasta
And Not Exists (Select * From MAEDPCD With (Nolock) Where MAEDPCD.ARCHIRST='MAEDPCE' And MAEDPCD.IDRST = MAEDPCE.IDMAEDPCE) 
