'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Recursos_Formato_Documento
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BkSpecialPrograms.Recursos_Formato_Documento", GetType(Recursos_Formato_Documento).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Declare @Idmaedpce as int = #Idmaedpce#
        '''
        '''
        '''SELECT TOP 1 
        '''       Mc.*,convert(nvarchar, convert(datetime, (HORAGRAB*1.0/3600)/24), 108) AS &apos;HORA_GRAB&apos;,
        '''       (Select NOKOCJ From TABCJ Cj Where Cj.EMPRESA = Mc.EMPRESA And Cj.KOSU = Mc.SUREDP And Cj.KOCJ = Mc.CJREDP) AS CAJA,
        '''       (Select NOKOSU From TABSU Su Where Su.EMPRESA = Mc.EMPRESA And Su.KOSU = Mc.SUREDP) AS SUCURSAL,
        '''       Tdp.NOKOENDP,Tdp.CTACTE,
        '''       -- MAEEN
        '''       Een.IDMAEEN, Een.KOEN, Een.TIEN, Een.RTEN, Een.SUEN, Een.TIPOSUC, Een. [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SQLQuery_Traer_Cheque_Letra_Para_Imprimir() As String
            Get
                Return ResourceManager.GetString("SQLQuery_Traer_Cheque_Letra_Para_Imprimir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Declare @Idmaeedo As int
        '''
        '''Set @Idmaeedo = #Idmaeedo#
        '''
        '''--UPDATE MAEEDO SET RUTCONTACT = &apos;13239873&apos; WHERE IDMAEEDO = @Idmaeedo
        '''
        '''SELECT 
        '''       -- MAEEDO 
        '''       Edo.IDMAEEDO, Edo.EMPRESA, Edo.TIDO, Edo.NUDO, Edo.TIDO+Edo.NUDO As &apos;Bk_Tido_Nudo&apos;, Edo.ENDO, Edo.SUENDO, Edo.ENDOFI, Edo.TIGEDO, Edo.SUDO,Sucedo.NOKOSU As &apos;NOMSUDO&apos;,
        '''	   Edo.LUVTDO, Edo.FEEMDO, Edo.KOFUDO, Resp.NOKOFU As &apos;Resp_NOKOFU&apos;, Edo.ESDO, Edo.ESPGDO, 
        '''       Edo.CAPRCO, Edo.CAPRAD, Edo.CAPREX, Edo.CAPRNC, Edo.MEARDO, Edo.MODO, Edo.TI [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SQLQuery_Traer_Documento_Para_Imprimir() As String
            Get
                Return ResourceManager.GetString("SQLQuery_Traer_Documento_Para_Imprimir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 
        '''
        '''SELECT Id, CodSolicitud, Estado, Funcionario, 
        '''       (Select NOKOFU From TABFU Where KOFU = Funcionario) As Nokofu,
        '''       Codigo, Descripcion, 
        '''       Empresa, Sucursal, Bodega, 
        '''	   (Select Top 1 RAZON From CONFIGP Where EMPRESA = Empresa) as Razon,
        '''	   (Select Top 1 NOKOSU From TABSU Where EMPRESA = Empresa And KOSU = Sucursal) As Nokosu,
        '''	   (Select Top 1 NOKOBO From TABBO Where EMPRESA = Empresa And KOSU = Sucursal And KOBO = Bodega) As Nokobo,
        '''	   Ubicacion, 
        '''	   (Select Top 1 STFI1 From  [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SQLQuery_Traer_Prod_Sol_Bodega() As String
            Get
                Return ResourceManager.GetString("SQLQuery_Traer_Prod_Sol_Bodega", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
