
Select DISTINCT IDMAEEN,ENDO,SUENDO,NOKOEN,ENDOFI,SUENDOFI,NOENDOFI
From #Tabla_Paso# Ps
Where 1 > 0
#Filtro#

Select DISTINCT IDMAEEDO,IDMAEEN,ENDO,SUENDO,NOKOEN,ENDOFI,SUENDOFI,NOENDOFI,TIDO,NUDO,OBDO,OCDO,FEEMDO,FEERLI,
       SULIDO,SUCURSAL,BOSULIDO,BOSULIDO,BODEGA
From #Tabla_Paso# Ps
Where 1 > 0       
#Filtro#   
    
  /*     
Select IDMAEEDO,IDMAEDDO,ENDO,SUENDO,NOKOEN,ENDOFI,SUENDOFI,NOENDOFI,TIDO,NUDO,OBDO,OCDO,FEEMDO,FEERLI,
       SULIDO,SUCURSAL,BOSULIDO,BODEGA,
       TIPR,KOPRCT,NOKOPR,UD0#Ud#PR,
       CAPRCO#Ud#,CAPREX#Ud#,SALDO_Ud#Ud#,
       MODO,TIMODO,TAMOPPPR,PPPRNE,PPPRNERE#Ud#,PM_TRANS,PM_ACTUAL,
       TOT_SALDOxPRECIO,TOT_SALDOxPRECIOREAL,
       TOT_SALDOxPM_TRANS,TOT_SALDOxPM_ACTUAL,STFI#Ud#,
       FMPR,SUPER_FAMILIA,PFPR,FAMILIA,HFPR,SUB_FAMILIA,MRPR,MARCA,RUPR,RUBRO,CLALIBPR,CLAS_LIBRE
From #Tabla_Paso#
Where 1 > 0
#Filtro#
Order by IDMAEDDO
*/

Select Ps.IDMAEEDO,IDMAEDDO,Ps.ENDO,Ps.SUENDO,NOKOEN,Ps.ENDOFI,Ps.SUENDOFI,NOENDOFI,Ps.TIDO,Ps.NUDO,OBDO,OCDO,Ps.FEEMDO,FEERLI,Ps.FEER,
       SULIDO,SUCURSAL,BOSULIDO,BODEGA,
       TIPR,KOPRCT,NOKOPR,UD0#Ud#PR,
       CAPRCO#Ud#,CAPREX#Ud#,SALDO_Ud#Ud#,
       Ps.MODO,Ps.TIMODO,TAMOPPPR,PPPRNE,PPPRNERE#Ud#,PM_TRANS,PM_ACTUAL,
	   Edo.KOFUDO As 'CODRESPONSABLE',Tf.NOKOFU As 'RESPONSABLE',KOFULIDO As 'CODVENDEDOR',FUNCIONARIO As 'VENDEDOR',
       TOT_SALDOxPRECIO,TOT_SALDOxPRECIOREAL,
       TOT_SALDOxPM_TRANS,TOT_SALDOxPM_ACTUAL,STFI#Ud#,
       FMPR,SUPER_FAMILIA,PFPR,FAMILIA,HFPR,SUB_FAMILIA,MRPR,Ps.MARCA,RUPR,RUBRO,CLALIBPR,CLAS_LIBRE

From #Tabla_Paso# Ps
Left Join MAEEDO Edo On Ps.IDMAEEDO = Edo.IDMAEEDO
Left Join TABFU Tf On Edo.KOFUDO = Tf.KOFU
Where 1 > 0
#Filtro#
Order by IDMAEDDO