Select SULIDO,SUCURSAL,Sum(SALDO_Ud1) As SALDO_Ud1,Sum(TOT_SALDOxPRECIOREAL) As TOT_SALDOxPRECIOREAL
From BAKAPP_SA.dbo.Tbl_PasoDPM_Ppr
Group By SULIDO,SUCURSAL
Union 
Select 'ZZZ','TOTAL',Sum(SALDO_Ud1),Sum(TOT_SALDOxPRECIOREAL)
From BAKAPP_SA.dbo.Tbl_PasoDPM_Ppr