
Select KOPRCT,NOKOPR,
       --UD0#Ud#PR,
       SUM(CAPRCO#Ud#) As CAPRCO#Ud#,
       SUM(CAPREX#Ud#) As CAPREX#Ud#,
       SUM(SALDO_Ud#Ud#) As SALDO_Ud#Ud#,
       PM_TRANS,
       PM_ACTUAL,
       --TOT_SALDOxPRECIO,
       --TOT_SALDOxPM_TRANS,
       --TOT_SALDOxPM_ACTUAL,
       SUM(STFI#Ud#) As STFI#Ud#,
       FMPR,SUPER_FAMILIA,PFPR,FAMILIA,HFPR,SUB_FAMILIA,MRPR,MARCA,RUPR,RUBRO,CLALIBPR,CLAS_LIBRE
From #Tabla_Paso#
Where 1 > 0
#Filtro#
Group By KOPRCT,NOKOPR,UD0#Ud#PR,PM_TRANS,PM_ACTUAL,
         FMPR,SUPER_FAMILIA,PFPR,FAMILIA,HFPR,SUB_FAMILIA,MRPR,MARCA,RUPR,RUBRO,CLALIBPR,CLAS_LIBRE
Order by KOPRCT

/*
Select KOPRCT,SULIDO,SUCURSAL,BOSULIDO,BODEGA,
       SUM(CAPRCO#Ud#) As CAPRCO#Ud#,
       SUM(CAPREX#Ud#) As CAPREX#Ud#,
       SUM(SALDO_Ud#Ud#) As SALDO_Ud#Ud#,
       SUM(STFI#Ud#) As STFI#Ud#
From #Tabla_Paso#
Where 1 > 0
#Filtro#
Group By KOPRCT,SULIDO,SUCURSAL,BOSULIDO,BODEGA
Order by SULIDO,BOSULIDO
*/  
       
Select IDMAEEDO,IDMAEDDO,
       ENDO,SUENDO,NOKOEN,
       ENDOFI,SUENDOFI,NOENDOFI,
       TIDO,NUDO,OBDO,OCDO,FEEMDO,FEERLI,
       SULIDO,SUCURSAL,BOSULIDO,BODEGA,
       TIPR,KOPRCT,NOKOPR,UD0#Ud#PR,
       CAPRCO#Ud#,CAPREX#Ud#,SALDO_Ud#Ud#,MODO,TIMODO,TAMOPPPR,PPPRNE,PPPRNERE#Ud#,PM_TRANS,PM_ACTUAL,
       TOT_SALDOxPRECIO,TOT_SALDOxPRECIOREAL,
       TOT_SALDOxPM_TRANS,TOT_SALDOxPM_ACTUAL,STFI#Ud#,
       FMPR,SUPER_FAMILIA,PFPR,FAMILIA,HFPR,SUB_FAMILIA,MRPR,MARCA,RUPR,RUBRO,CLALIBPR,CLAS_LIBRE
From #Tabla_Paso#
Where 1 > 0
#Filtro#
Order by IDMAEDDO