
DECLARE @IdMaeedo Int

SET @IdMaeedo = #IdMaeedo#

-- 0 ENCABEZADO
SELECT *,
       Isnull((Select Top 1 NOTIDO From TABTIDO T1 Where T1.TIDO = MD.TIDO),'') As 'Tipo_de_Documento'
FROM MAEEDO MD WHERE IDMAEEDO = @IdMaeedo     

-- 1 DETALLE
SELECT *,
       CASE UDTRPR WHEN 1 THEN UD01PR ELSE UD02PR END AS 'UnTrans',
       CASE UDTRPR WHEN 1 THEN CAPRCO1 ELSE CAPRCO2 END AS 'Cant_Trans',
       ISNULL((SELECT TOP 1 KOPRAL FROM TABCODAL WHERE KOPR = MAEDDO.KOPRCT AND KOEN = ENDO),'') AS 'Alternativo_1',
       ISNULL((SELECT TOP 1 KOPRAL FROM TABCODAL WHERE KOPR = MAEDDO.KOPRCT AND KOEN = ENDOFI),'') AS 'Alternativo_2'
       FROM MAEDDO WHERE IDMAEEDO = @IdMaeedo      

-- 2 IMPUESTOS POR LINEA       
SELECT * FROM MAEIMLI WHERE IDMAEEDO = @IdMaeedo   

-- 3 DESCUENTOS POR LINEA
SELECT * FROM MAEDTLI WHERE IDMAEEDO = @IdMaeedo   

-- 4 VENCIMIENTO 
SELECT * FROM MAEVEN WHERE IDMAEEDO = @IdMaeedo    

-- 5 OBSERVACIONES
SELECT * FROM MAEEDOOB WHERE IDMAEEDO = @IdMaeedo  

-- 6 SUB TOTALES, SUMAS DE DESCUENTOS
SELECT   SUM(PPPRNE* CASE UDTRPR WHEN 1 THEN CAPRCO1 ELSE CAPRCO2 END) AS SUB_NETO,
         SUM(VADTNELI) AS SUM_DESCUENTOS FROM MAEDDO 
         WHERE IDMAEEDO = @IdMaeedo               