'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Recursos_Informe_Produccion
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Bk_Produccion.Recursos_Informe_Produccion", GetType(Recursos_Informe_Produccion).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 
        '''-- Informe de estado de avance de OT segun operaciones realizadas
        '''Select NUMOT,Cast(&apos;&apos; As Varchar(100)) As REFERENCIA,
        '''       Cast(Null As date) As FIOT,
        '''       Cast(0 as Int) As Dias_Transc,
        '''       Cast(0 As Int) As Dias_Hb,
        '''	   Cast(0 As Int) As Dias_Sb,
        '''	   Cast(0 As Int) As Dias_Dm,
        '''       (Select Sum(FABRICAR) From POTL Where Z1.NUMOT = POTL.NUMOT) As Fabricar,
        '''	   (Select Sum(REALIZADO) From POTL Where Z1.NUMOT = POTL.NUMOT) As Realizado,
        '''       SUM( Case When REALIZADO &gt;= FABRICAR Then 1 E [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SQLQuery_Informe_de_OT_avance() As String
            Get
                Return ResourceManager.GetString("SQLQuery_Informe_de_OT_avance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 
        '''-- Informe de estado de avance de OT segun operaciones realizadas
        '''Select POTPR.NUMOT,Cast(&apos;&apos; As Varchar(100)) As REFERENCIA,
        '''       Cast(Null As date) As FIOT,
        '''       Cast(0 As Int) As Dias_Transc,
        '''       Cast(0 As Int) As Dias_Hb,
        '''	   Cast(0 As Int) As Dias_Sb,
        '''	   Cast(0 As Int) As Dias_Dm,
        '''    --   Sum(POTL.FABRICAR) As Fabricar,
        '''	   --Sum(POTL.REALIZADO) As Realizado,
        '''	   (Select Sum(FABRICAR) From POTL Where POTPR.NUMOT = POTL.NUMOT) As Fabricar,
        '''	   (Select Sum(REALIZADO) From POTL Where P [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SQLQuery_Informe_de_OT_avance_Vs_SubOt_por_Operaciones() As String
            Get
                Return ResourceManager.GetString("SQLQuery_Informe_de_OT_avance_Vs_SubOt_por_Operaciones", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 
        '''
        '''SELECT PDATFAD.*,Cast(0 As Bit) As En_Proceso,
        '''      Cast(FLOOR(HORAINI) AS Float) as Hh_Ini,
        '''	  Cast(ROUND(HORAINI- floor(HORAINI),2)*100 AS Float) as Mi_Ini,
        '''	  Cast(FLOOR(HORATER) AS Float) as Hh_Ter,
        '''	  Cast(ROUND(HORATER- floor(HORATER),2)*100 AS Float) as Mi_Ter,
        '''      convert(Float,DATEPART (HH,Getdate()))+(convert(Float,DATEPART (MI,Getdate()))/100) As Hora_Actual,Cast(0 As Float) As Tiempo_Actual,
        '''POBREFAD.OBRERO,Cast(&apos;&apos; AS Varchar(50)) AS NOMBREOB,POBREFAD.TIEMPOOB,UDADOP=POPER.UDAD,POPE [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SQLQuery_Informe_DFA_en_ejecucion() As String
            Get
                Return ResourceManager.GetString("SQLQuery_Informe_DFA_en_ejecucion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a 
        '''Select IDPOTPR,IDPOTL,NUMOT,Cast(&apos;&apos; As varchar(100)) As REFERENCIA,NREGOTL,CODIGO,Cast(&apos;&apos; As varchar(50)) As DESCRIPCION_PR,OPERACION,Cast(&apos;&apos; As Varchar(50)) As NOMBREOP,CODMAQOT,
        '''       (Select NOMBREMAQ From PMAQUI Where CODMAQ = CODMAQOT) As MAQUINA,FABRICAR,REALIZADO,Cast(0 As Float) AS AVANCE 
        '''Into #Paso1	   
        '''From POTPR
        '''Where NUMOT In (Select NUMOT From POTE Where ESODD = &apos;&apos; And ESTADO = &apos;V&apos;)
        '''
        '''Update #Paso1 Set REFERENCIA = (Select Top 1 REFERENCIA From POTE Z2 Where Z1.NUMOT = Z2.NUMOT)
        '''From  [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SQLQuery_Informe_estado_de_Maquinas_Vs_Avence_y_cola_en_proceso() As String
            Get
                Return ResourceManager.GetString("SQLQuery_Informe_estado_de_Maquinas_Vs_Avence_y_cola_en_proceso", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
