
Declare @Fecha_Informe Date = '#Fecha_Informe#', --{d '2017-05-08'}
        @Fecha_6_Meses_Menos Date = Dateadd(MONTH,-6,Getdate()),
		@Fecha_1_Ano_Menos Date = Dateadd(YEAR,-1,Getdate()),
		@Fecha_2_Ano_Menos Date = Dateadd(YEAR,-2,Getdate()),
		@Fecha_3_Ano_Menos Date = Dateadd(YEAR,-3,Getdate())

-- CREACION DE LA TABLA DE PASO DEL INFORME
SELECT TOP 1 
			TABBOPR.KOPR,
			TABBOPR.EMPRESA,
			TABBOPR.KOSU,
		    CAST('' AS VARCHAR (50)) AS SUCURSAL,
			TABBOPR.KOBO,
			CAST('' AS VARCHAR (50)) AS BODEGA,
			MAEPR.NOKOPR,MAEPR.UD01PR,MAEPR.UD02PR,MAEPREM.PM, 
			MAEPREM.TIMOUL,MAEPREM.PPUL01,MAEPREM.PPUL02,MAEPREM.TAUL,MAEPREM.VALI,MAEPREM.PMIN, 
			MAEPR.FMPR,
			CAST('' AS VARCHAR(50)) AS SUPER_FAMILIA,
			MAEPR.PFPR,
			CAST('' AS VARCHAR(50)) AS FAMILIA,
			MAEPR.HFPR,
			CAST('' AS VARCHAR(50)) AS SUB_FAMILIA,
			MAEPR.MRPR,
			CAST('' AS VARCHAR(50)) AS MARCA,
			MAEPR.RUPR,
			CAST('' AS VARCHAR(50)) AS RUBRO,
			MAEPR.CLALIBPR,
			CAST('' AS VARCHAR(200)) AS CLAS_LIBRE,
			MAEPR.FEUL AS ULT_COMPRA, 
			MAEPR.FEUL AS ULT_VENTA, 
            CAST(0.0 AS FLOAT)  AS STFI, 
            CAST(0.0 AS FLOAT)  AS VALSTOCK, 
            CAST(0.0 AS FLOAT)  AS PRMEDIO, 
            CAST('' AS CHAR(2)) AS UNIDAD, 
            CAST(0.0 AS FLOAT)  AS PRECIO1, 
            CAST(0.0 AS FLOAT)  AS PRECIO2,
            CAST('' AS VARCHAR(3)) AS COD_OBSOLENCIA,
            CAST('' AS VARCHAR(30)) AS OBSOLENCIA,
            CAST(0 AS INT) AS Idmaeddo,
            CAST(NULL AS DATE) AS Fecha  
 INTO #STOCKVAL 
 FROM 
	TABBOPR WITH ( NOLOCK )  
		INNER JOIN MAEPREM ON MAEPREM.EMPRESA='xx' AND 
		TABBOPR.KOPR=MAEPREM.KOPR  
		INNER JOIN MAEPR ON MAEPR.KOPR=MAEPREM.KOPR  
		 WHERE TABBOPR.KOPR=':f56+23/:'
		 
-- FIN CREACION DE TABLA DE PASO DEL INFORME

-- CREACION DE TABLA DE PASO PARA STOCK VALORIZADO

CREATE TABLE #OPERST ( 
TIDO         CHAR(3) NOT NULL,
SUBTIDO      CHAR(3) NOT NULL,
FICO         INT NOT NULL DEFAULT (0),
FIAD         INT NOT NULL DEFAULT (0),
DEVENGVEN    INT NOT NULL DEFAULT (0),
COMPROMETIDO INT NOT NULL DEFAULT (0),
DEVENGCOM    INT NOT NULL DEFAULT (0),
PEDIDO       INT NOT NULL DEFAULT (0),
DESPNOFAC    INT NOT NULL DEFAULT (0),
RECENOFAC    INT NOT NULL DEFAULT (0),
TRANSITO     INT NOT NULL DEFAULT (0),
PRESHECHOS   INT NOT NULL DEFAULT (0),
PRESRECI     INT NOT NULL DEFAULT (0),
CONSHECHAS   INT NOT NULL DEFAULT (0),
CONSRECI     INT NOT NULL DEFAULT (0),
DEVENGNCV    INT NOT NULL DEFAULT (0),
DEVENGNCC    INT NOT NULL DEFAULT (0),
DEVOSINNCV   INT NOT NULL DEFAULT (0),
DEVOSINNCC   INT NOT NULL DEFAULT (0),
PEDFAB       INT NOT NULL DEFAULT (0), 
COMPROFAB    INT NOT NULL DEFAULT (0) ) 

INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('GAR','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('GCL','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('NVI','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('OCI','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('NVV','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('RES','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('PRO','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('OCC','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('GDI','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('GTI','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('GRI','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('GDV','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('GRC','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('GDP','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('GDP','PRE')
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('GDP','CON')
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('GRP','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('GRP','PRE')
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('GRP','CON')
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('GRD','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('GRD','PRE')
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('GRD','CON')
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('GDD','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('GDD','PRE')
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('GDD','CON')
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('BLV','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('BSV','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('BLX','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('FCV','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('FDB','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('FDV','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('FDX','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('FDZ','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('FEV','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('FVL','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('FVT','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('FVX','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('FVZ','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('RIN','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('ESC','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('FEE','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('BLC','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('FCC','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('FCT','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('FDC','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('RGA','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('NCV','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('NCX','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('NCZ','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('NEV','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('NCE','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('NCC','')   
INSERT INTO #OPERST (TIDO,SUBTIDO) VALUES ('NCB','')   


UPDATE #OPERST SET FICO=TABTIDO.FICO,FIAD=TABTIDO.FIAD FROM TABTIDO WHERE TABTIDO.TIDO=#OPERST.TIDO 
UPDATE #OPERST SET COMPROMETIDO=1 WHERE TIDO='NVI' 
UPDATE #OPERST SET PEDIDO=1 WHERE TIDO='OCI' 
UPDATE #OPERST SET COMPROMETIDO=1 WHERE TIDO IN  ('NVV','RES','PRO') 
UPDATE #OPERST SET PEDIDO=1 WHERE TIDO IN  ('OCC') 
UPDATE #OPERST SET TRANSITO=1 WHERE TIDO IN ('GTI','GDI')
UPDATE #OPERST SET TRANSITO=-1 WHERE TIDO='GRI' 
UPDATE #OPERST SET DESPNOFAC=1 WHERE TIDO='GDV' 
UPDATE #OPERST SET RECENOFAC=1 WHERE TIDO='GRC' 
UPDATE #OPERST SET DESPNOFAC=1 WHERE TIDO='GDP' AND SUBTIDO='' 
UPDATE #OPERST SET PRESHECHOS=1 WHERE TIDO='GDP' AND SUBTIDO='PRE' 
UPDATE #OPERST SET CONSHECHAS=1 WHERE TIDO='GDP' AND SUBTIDO='CON' 
UPDATE #OPERST SET RECENOFAC=1 WHERE TIDO='GRP' AND SUBTIDO='' 
UPDATE #OPERST SET PRESRECI=1 WHERE TIDO='GRP' AND SUBTIDO='PRE' 
UPDATE #OPERST SET CONSRECI=1 WHERE TIDO='GRP' AND SUBTIDO='CON' 
UPDATE #OPERST SET DEVOSINNCV=1 WHERE TIDO='GRD' AND SUBTIDO='' 
UPDATE #OPERST SET PRESHECHOS=1 WHERE TIDO='GRD' AND SUBTIDO='PRE' 
UPDATE #OPERST SET CONSHECHAS=1 WHERE TIDO='GRD' AND SUBTIDO='CON' 
UPDATE #OPERST SET DEVOSINNCC=1 WHERE TIDO='GDD' AND SUBTIDO='' 
UPDATE #OPERST SET PRESRECI=1 WHERE TIDO='GDD' AND SUBTIDO='PRE' 
UPDATE #OPERST SET CONSRECI=1 WHERE TIDO='GDD' AND SUBTIDO='CON' 
UPDATE #OPERST SET DEVENGVEN=1 WHERE TIDO IN  ('BLV','BSV','BLX','FCV','FDB','FDV','FDX','FDZ','FEV','FVL','FVT','FVX','FXV','FYV','FVZ','RIN','ESC','FEE','FDE') 
UPDATE #OPERST SET DEVENGCOM=1 WHERE TIDO IN  ('BLC','FCC','FCT','FDC','RGA','SRF','FCZ','FCL') 
UPDATE #OPERST SET DEVENGNCV=1 WHERE TIDO IN  ('NCV','NCX','NCZ','NEV','NCE') 
UPDATE #OPERST SET DEVENGNCC=1 WHERE TIDO IN  ('NCC','NCB') 

-- FIN CREACION DE TABLA DE PASO PARA TIPO DE DOCUMENTOS


SELECT 
	    A.IDMAEDDO,A.IDRST,A.ARCHIRST,A.TIDO,COALESCE(EDO.SUBTIDO,'') AS SUBTIDO,
	    A.EMPRESA,A.SULIDO,A.BOSULIDO,A.KOPRCT,A.CAPRCO1,A.CAPRAD1,A.CAPREX1,A.CAPRCO2,A.CAPRAD2,A.CAPREX2  
INTO #DDO  
FROM MAEDDO AS A INNER JOIN MAEEDO AS EDO ON A.IDMAEEDO=EDO.IDMAEEDO  
WHERE 
	A.FEEMLI <= @Fecha_Informe AND 
	A.PRCT=0    AND 
	A.LILG IN ('SI','CR')    AND 
	A.TIDO NOT IN ('DIN','COV') 

CREATE INDEX #DDO_5964406 ON #DDO ( IDRST )



UPDATE #DDO SET 
     CAPREX1=CAPREX1-COALESCE((SELECT SUM(X.CAPRCO1) 
                                FROM MAEDDO AS X WITH (NOLOCK) 
                                WHERE X.IDRST=#DDO.IDMAEDDO AND X.ARCHIRST='MAEDDO' AND X.FEEMLI> @Fecha_Informe ),0),
     CAPREX2=CAPREX2-COALESCE((SELECT SUM(X.CAPRCO2) 
                                FROM MAEDDO AS X WITH (NOLOCK) 
                                WHERE X.IDRST=#DDO.IDMAEDDO AND X.ARCHIRST='MAEDDO' AND X.FEEMLI> @Fecha_Informe ),0),
SUBTIDO=(CASE 
			WHEN SUBTIDO IN ('AJU','IMP','EXP','EXE','NVV','OCC','000','100','010','001','101') THEN '' 
			ELSE SUBTIDO 
		 END )

SELECT 
EMPRESA,KOPRCT,SULIDO,BOSULIDO,TIDO,SUBTIDO,SUM(CAPRCO1) AS CAPRCO1,SUM(CAPRAD1) AS CAPRAD1,SUM(CAPREX1) AS CAPREX1,SUM(CAPRCO2) AS CAPRCO2,SUM(CAPRAD2) AS CAPRAD2,
SUM(CAPREX2) AS CAPREX2,CAST(0 AS FLOAT) AS FISICO1,      CAST(0 AS FLOAT) AS FISICO2,CAST(0 AS FLOAT) AS DEVENGVEN1,   
CAST(0 AS FLOAT) AS DEVENGVEN2,CAST(0 AS FLOAT) AS COMPROMETIDO1,CAST(0 AS FLOAT) AS COMPROMETIDO2,CAST(0 AS FLOAT) AS DEVENGCOM1 ,  
CAST(0 AS FLOAT) AS DEVENGCOM2,CAST(0 AS FLOAT) AS PEDIDO1 ,     CAST(0 AS FLOAT) AS PEDIDO2,CAST(0 AS FLOAT) AS DESPNOFAC1 , 
 CAST(0 AS FLOAT) AS DESPNOFAC2,CAST(0 AS FLOAT) AS RECENOFAC1 ,  CAST(0 AS FLOAT) AS RECENOFAC2,CAST(0 AS FLOAT) AS TRANSITO1 , 
 CAST(0 AS FLOAT) AS TRANSITO2,CAST(0 AS FLOAT) AS PRESHECHOS1 , CAST(0 AS FLOAT) AS PRESHECHOS2,CAST(0 AS FLOAT) AS PRESRECI1 ,  
 CAST(0 AS FLOAT) AS PRESRECI2,CAST(0 AS FLOAT) AS CONSHECHAS1 , CAST(0 AS FLOAT) AS CONSHECHAS2,CAST(0 AS FLOAT) AS CONSRECI1 ,  
 CAST(0 AS FLOAT) AS CONSRECI2,CAST(0 AS FLOAT) AS DEVENGNCV1,   CAST(0 AS FLOAT) AS DEVENGNCV2,CAST(0 AS FLOAT) AS DEVENGNCC1,  
 CAST(0 AS FLOAT) AS DEVENGNCC2,CAST(0 AS FLOAT) AS DEVOSINNCV1,  CAST(0 AS FLOAT) AS DEVOSINNCV2,CAST(0 AS FLOAT) AS DEVOSINNCC1,  
 CAST(0 AS FLOAT) AS DEVOSINNCC2,CAST(0 AS FLOAT) AS PEDFAB1,      CAST(0 AS FLOAT) AS PEDFAB2, CAST(0 AS FLOAT) AS COMPROFAB1,  
 CAST(0 AS FLOAT) AS COMPROFAB2 INTO #DDOGRUPO 
 FROM #DDO 
 GROUP BY EMPRESA,KOPRCT,SULIDO,BOSULIDO,TIDO,SUBTIDO


UPDATE #DDOGRUPO  SET 
FISICO1       =CAPRCO1*FICO+CAPRAD1*FIAD,
FISICO2       =CAPRCO2*FICO+CAPRAD2*FIAD,
DEVENGVEN1    =(CAPRCO1-CAPRAD1-CAPREX1)*O.DEVENGVEN,
DEVENGVEN2    =(CAPRCO2-CAPRAD2-CAPREX2)*O.DEVENGVEN,
COMPROMETIDO1 =(CAPRCO1-CAPRAD1-CAPREX1)*O.COMPROMETIDO,
COMPROMETIDO2 =(CAPRCO2-CAPRAD2-CAPREX2)*O.COMPROMETIDO,
DEVENGCOM1    =(CAPRCO1-CAPRAD1-CAPREX1)*O.DEVENGCOM,
DEVENGCOM2    =(CAPRCO2-CAPRAD2-CAPREX2)*O.DEVENGCOM,
PEDIDO1       =(CAPRCO1-CAPRAD1-CAPREX1)*O.PEDIDO,
PEDIDO2       =(CAPRCO2-CAPRAD2-CAPREX2)*O.PEDIDO,
DESPNOFAC1    =(CAPRCO1-CAPRAD1-CAPREX1)*O.DESPNOFAC,
DESPNOFAC2    =(CAPRCO2-CAPRAD2-CAPREX2)*O.DESPNOFAC,
RECENOFAC1    =(CAPRCO1-CAPRAD1-CAPREX1)*O.RECENOFAC,
RECENOFAC2    =(CAPRCO2-CAPRAD2-CAPREX2)*O.RECENOFAC,
TRANSITO1     =(CAPRCO1-CAPRAD1-CAPREX1)*O.TRANSITO,
TRANSITO2     =(CAPRCO2-CAPRAD2-CAPREX2)*O.TRANSITO,
PRESHECHOS1   =(-1)*CAPRCO1*O.PRESHECHOS,
PRESHECHOS2   =(-1)*CAPRCO2*O.PRESHECHOS,
PRESRECI1     =(-1)*CAPRCO1*O.PRESRECI,
PRESRECI2     =(-1)*CAPRCO2*O.PRESRECI,
CONSHECHAS1   =(-1)*CAPRCO1*O.CONSHECHAS,
CONSHECHAS2   =(-1)*CAPRCO2*O.CONSHECHAS,
CONSRECI1     =(-1)*CAPRCO1*O.CONSRECI,
CONSRECI2     =(-1)*CAPRCO2*O.CONSRECI,
DEVENGNCV1    =(CAPRCO1-CAPRAD1-CAPREX1)*O.DEVENGNCV,
DEVENGNCV2    =(CAPRCO2-CAPRAD2-CAPREX2)*O.DEVENGNCV,
DEVENGNCC1    =(CAPRCO1-CAPRAD1-CAPREX1)*O.DEVENGNCC,
DEVENGNCC2    =(CAPRCO2-CAPRAD2-CAPREX2)*O.DEVENGNCC,
DEVOSINNCV1   =(CAPRCO1-CAPRAD1-CAPREX1)*O.DEVOSINNCV,
DEVOSINNCV2   =(CAPRCO2-CAPRAD2-CAPREX2)*O.DEVOSINNCV,
DEVOSINNCC1   =(CAPRCO1-CAPRAD1-CAPREX1)*O.DEVOSINNCC,
DEVOSINNCC2   =(CAPRCO2-CAPRAD2-CAPREX2)*O.DEVOSINNCC  

FROM #OPERST AS O  WHERE O.TIDO=#DDOGRUPO.TIDO AND O.SUBTIDO=#DDOGRUPO.SUBTIDO 


SELECT EMPRESA,KOPRCT,SULIDO,BOSULIDO,
SUM(FISICO1      ) AS FISICO1      ,
SUM(FISICO2      ) AS FISICO2      ,
SUM(DEVENGVEN1   ) AS DEVENGVEN1   ,
SUM(DEVENGVEN2   ) AS DEVENGVEN2   ,
SUM(COMPROMETIDO1) AS COMPROMETIDO1,
SUM(COMPROMETIDO2) AS COMPROMETIDO2,
SUM(DEVENGCOM1   ) AS DEVENGCOM1   ,
SUM(DEVENGCOM2   ) AS DEVENGCOM2   ,
SUM(PEDIDO1      ) AS PEDIDO1      ,
SUM(PEDIDO2      ) AS PEDIDO2      ,
SUM(DESPNOFAC1   ) AS DESPNOFAC1   ,
SUM(DESPNOFAC2   ) AS DESPNOFAC2   ,
SUM(RECENOFAC1   ) AS RECENOFAC1   ,
SUM(RECENOFAC2   ) AS RECENOFAC2   ,
SUM(TRANSITO1    ) AS TRANSITO1    ,
SUM(TRANSITO2    ) AS TRANSITO2    ,
SUM(PRESHECHOS1  ) AS PRESHECHOS1  ,
SUM(PRESHECHOS2  ) AS PRESHECHOS2  ,
SUM(PRESRECI1    ) AS PRESRECI1    ,
SUM(PRESRECI2    ) AS PRESRECI2    ,
SUM(CONSHECHAS1  ) AS CONSHECHAS1  ,
SUM(CONSHECHAS2  ) AS CONSHECHAS2  ,
SUM(CONSRECI1    ) AS CONSRECI1    ,
SUM(CONSRECI2    ) AS CONSRECI2    ,
SUM(DEVENGNCV1   ) AS DEVENGNCV1   ,
SUM(DEVENGNCV2   ) AS DEVENGNCV2   ,
SUM(DEVENGNCC1   ) AS DEVENGNCC1   ,
SUM(DEVENGNCC2   ) AS DEVENGNCC2   ,
SUM(DEVOSINNCV1  ) AS DEVOSINNCV1  ,
SUM(DEVOSINNCV2  ) AS DEVOSINNCV2  ,
SUM(DEVOSINNCC1  ) AS DEVOSINNCC1  ,
SUM(DEVOSINNCC2  ) AS DEVOSINNCC2    
INTO #STAFECHA  
FROM #DDOGRUPO  
GROUP BY EMPRESA,KOPRCT,SULIDO,BOSULIDO 

CREATE INDEX #SAF_5964938 ON #STAFECHA ( EMPRESA,KOPRCT,SULIDO,BOSULIDO )

INSERT INTO #STOCKVAL 
        (KOPR,EMPRESA,KOSU,KOBO,NOKOPR,UD01PR,UD02PR,PM,TIMOUL,PPUL01,PPUL02,TAUL,VALI,PMIN,
        FMPR,PFPR,HFPR,MRPR,RUPR,CLALIBPR,
        ULT_COMPRA,ULT_VENTA,STFI,VALSTOCK,PRMEDIO,UNIDAD,PRECIO1,PRECIO2,Idmaeddo) 
        SELECT TABBOPR.KOPR,TABBOPR.EMPRESA,TABBOPR.KOSU,TABBOPR.KOBO,MAEPR.NOKOPR,MAEPR.UD01PR,MAEPR.UD02PR,MAEPREM.PM,
               MAEPREM.TIMOUL,MAEPREM.PPUL01,MAEPREM.PPUL02,MAEPREM.TAUL,MAEPREM.VALI,MAEPREM.PMIN,
               MAEPR.FMPR,MAEPR.PFPR,MAEPR.HFPR,MAEPR.MRPR,MAEPR.RUPR,MAEPR.CLALIBPR,
         CAST('' AS DATETIME ) AS ULT_COMPRA,
         CAST('' AS DATETIME ) AS ULT_VENTA, 
         ISNULL(SAF.FISICO1,0.0) AS STFI ,
         CAST(0.0 AS FLOAT) AS VALSTOCK, 
         CAST(0.0 AS FLOAT) AS PRMEDIO, 
         'UNIDAD'=MAEPR.UD01PR,0.0,0.0,
         ISNULL((Select Top 1 IDMAEDDO 
			From MAEDDO Do 
				Where Do.KOPRCT = MAEPR.KOPR And TIDO IN ('FCV','FDV','BLV') Order By FEEMLI Desc),0)
  
FROM TABBOPR WITH ( NOLOCK )  
	LEFT JOIN #STAFECHA AS SAF ON SAF.EMPRESA=TABBOPR.EMPRESA AND 
	SAF.SULIDO=TABBOPR.KOSU AND 
	SAF.BOSULIDO=TABBOPR.KOBO AND 
	SAF.KOPRCT=TABBOPR.KOPR  
		INNER  JOIN MAEPREM ON TABBOPR.KOPR=MAEPREM.KOPR AND 
			TABBOPR.EMPRESA=MAEPREM.EMPRESA  
				INNER JOIN MAEPR ON MAEPR.KOPR=MAEPREM.KOPR  
				    #Excluir_Productos_SSN#         --  AND MAEPR.TIPR <> 'SSN'  -- EXLUIR PRODUCTOS TIPO SERVICIO
				    #Excluir_Productos_FLN#         --  AND MAEPR.TIPR <> 'FLN'  -- EXCLUIR PRODUCTOS TIPO LIBRE
				    #Filtros_Productos#               --  AND MAEPR.FMPR IN ( '001 ','003 ')
				    #Excluir_Productos_Bloqueados#  -- NOT COALESCE(MAEPR.BLOQUEAPR,'') IN ( 'C','V','T','X' )  
				      	LEFT  JOIN MAEST ON TABBOPR.EMPRESA='01' AND 
							TABBOPR.KOSU=MAEST.KOSU AND 
							TABBOPR.KOBO=MAEST.KOBO AND 
							TABBOPR.KOPR=MAEST.KOPR 
WHERE 1 > 0
#Filtro_Bodegas#							
						

UPDATE #STOCKVAL SET PRMEDIO=( SELECT TOP 1 PPPRPM  
FROM MAEDDO WITH (NOLOCK)  INNER JOIN MAEEDO ON MAEEDO.IDMAEEDO=MAEDDO.IDMAEEDO AND MAEEDO.EMPRESA='01'  
WHERE 
      KOPRCT=#STOCKVAL.KOPR  AND 
      FEEMLI <= @Fecha_Informe AND 
      LILG IN ('SI','GR')  AND 
      (MAEEDO.TIDO='DIN' OR LEFT(MAEEDO.TIDO,1)='G' OR CAPRAD1>0)  

ORDER BY KOPRCT DESC,FEEMLI DESC,MAEEDO.HORAGRAB DESC ) 

UPDATE #STOCKVAL SET FMPR = '' 
WHERE FMPR NOT IN (SELECT KOFM FROM TABFM)

UPDATE #STOCKVAL SET SUCURSAL = ISNULL((SELECT TOP 1 NOKOSU FROM TABSU Ts 
                                        WHERE Ts.EMPRESA = #STOCKVAL.EMPRESA And 
                                        Ts.KOSU = #STOCKVAL.KOSU),'')  
                                        
UPDATE #STOCKVAL SET BODEGA = ISNULL((SELECT TOP 1 NOKOBO FROM TABBO Ts 
							  WHERE Ts.EMPRESA = #STOCKVAL.EMPRESA And 
									Ts.KOSU = #STOCKVAL.KOSU And 
									Ts.KOBO = #STOCKVAL.KOBO ),'')  
									
----------------------- CLASIFICACIONES DEL PRODUCTO ------------------------------------------------------------
									
UPDATE #STOCKVAL SET SUPER_FAMILIA = ISNULL((SELECT TOP 1 NOKOFM FROM TABFM Tf 
                                             WHERE Tf.KOFM = #STOCKVAL.FMPR),'Sin Super Famila')
UPDATE #STOCKVAL SET FAMILIA = ISNULL((SELECT TOP 1 NOKOPF FROM TABPF Pf 
                                             WHERE Pf.KOFM = #STOCKVAL.FMPR And
                                                   Pf.KOPF = #STOCKVAL.PFPR ),'Sin Famila')
UPDATE #STOCKVAL SET SUB_FAMILIA = ISNULL((SELECT TOP 1 NOKOHF FROM TABHF Hf 
                                             WHERE Hf.KOFM = #STOCKVAL.FMPR And
                                                   Hf.KOPF = #STOCKVAL.PFPR And
                                                   Hf.KOHF = #STOCKVAL.HFPR ),'Sin Sub-Famila')                                                   

UPDATE #STOCKVAL SET MARCA = ISNULL((SELECT TOP 1 NOKOMR FROM TABMR Tm WHERE Tm.KOMR = #STOCKVAL.MRPR),'Sin Marca')
UPDATE #STOCKVAL SET RUBRO = ISNULL((SELECT TOP 1 NOKORU FROM TABRU Tr WHERE Tr.KORU = #STOCKVAL.RUPR),'Sin Rubro')
UPDATE #STOCKVAL SET CLAS_LIBRE = ISNULL((SELECT TOP 1 NOKOCARAC 
										  FROM TABCARAC Tr 
											WHERE Tr.KOTABLA = 'CLALIBPR' AND Tr.KOCARAC = #STOCKVAL.CLALIBPR),'Sin Clasificación')


--------------------------------------------------------------------------------------------------------------

UPDATE #STOCKVAL SET PRMEDIO= 0 WHERE PRMEDIO IS NULL
UPDATE #STOCKVAL SET VALSTOCK = ROUND( STFI * PRMEDIO,2)

UPDATE #STOCKVAL SET Fecha = ISNULL((Select Top 1 FEEMLI From MAEDDO Do Where Do.IDMAEDDO = #STOCKVAL.Idmaeddo),'19000101')

UPDATE #STOCKVAL SET COD_OBSOLENCIA = '001',OBSOLENCIA = '> 6 MESES'
WHERE Fecha >= @Fecha_6_Meses_Menos

UPDATE #STOCKVAL SET COD_OBSOLENCIA = '002',OBSOLENCIA = '< 6 MESES'
Where Fecha < @Fecha_6_Meses_Menos And Fecha >= @Fecha_1_Ano_Menos

UPDATE #STOCKVAL SET COD_OBSOLENCIA = '003',OBSOLENCIA = '< 1 AÑO'
Where Fecha < @Fecha_1_Ano_Menos And Fecha >= @Fecha_2_Ano_Menos

UPDATE #STOCKVAL SET COD_OBSOLENCIA = '004',OBSOLENCIA = '< 2 AÑO'
Where Fecha <  @Fecha_2_Ano_Menos And Fecha >= @Fecha_3_Ano_Menos

UPDATE #STOCKVAL SET COD_OBSOLENCIA = '005',OBSOLENCIA = '< 3 AÑO'
Where Fecha <  @Fecha_3_Ano_Menos 

SELECT * 
Into #Tabla_Paso#
FROM #STOCKVAL 

CREATE INDEX Ix_ISV_#Funcionario#_01 ON #Tabla_Paso# (EMPRESA,KOSU,KOBO)
CREATE INDEX Ix_ISV_#Funcionario#_02 ON #Tabla_Paso# (EMPRESA,KOSU,FMPR)
CREATE INDEX Ix_ISV_#Funcionario#_03 ON #Tabla_Paso# (EMPRESA,KOPR)
CREATE INDEX Ix_ISV_#Funcionario#_04 ON #Tabla_Paso# (KOPR)

DROP TABLE #DDOGRUPO 
DROP TABLE #DDO 
DROP TABLE #OPERST 
DROP TABLE #STAFECHA

--DROP TABLE #STOCKVAL_FM
DROP TABLE #STOCKVAL
