
-- FILTRO SUCURSAL
SELECT KOSU,
       FMPR,SUPER_FAMILIA,
       SUM(STFI)AS STFI,
       CAST(0 AS FLOAT) AS PORC_STFI,
       SUM(VALSTOCK) AS VALSTOCK,
       CAST(0 AS FLOAT) AS PORC_VALSTOCK
INTO #STOCKVAL_FM 
FROM #Tabla_Paso#
WHERE 1 > 0
#FILTRO#
GROUP BY KOSU,FMPR,SUPER_FAMILIA

UPDATE #STOCKVAL_FM SET PORC_STFI = STFI/(SELECT SUM(STFI) FROM #STOCKVAL_FM)
WHERE STFI > 0

UPDATE #STOCKVAL_FM SET PORC_VALSTOCK = VALSTOCK/(SELECT SUM(VALSTOCK) FROM #STOCKVAL_FM)
WHERE VALSTOCK > 0

-- Select totales 00
--SELECT SUM(VALSTOCK) As TOTAL_VALSTOCK,SUM(STFI) As TOTAL_STFI FROM #STOCKVAL_FM

-- Select Informes X Sucursal 01

INSERT INTO #STOCKVAL_FM (KOSU,FMPR,SUPER_FAMILIA,STFI,PORC_STFI,VALSTOCK,PORC_VALSTOCK)
SELECT 'ZZZ','ZZZ','TOTALES',SUM(STFI),SUM(PORC_STFI),SUM(VALSTOCK),SUM(PORC_VALSTOCK)
FROM #STOCKVAL_FM

SELECT FMPR,SUPER_FAMILIA,SUM(STFI) AS STFI,
       ROUND(SUM(PORC_STFI),3) AS PORC_STFI,
       SUM(VALSTOCK) AS VALSTOCK,
       ROUND(SUM(PORC_VALSTOCK),3) AS PORC_VALSTOCK 
FROM #STOCKVAL_FM
WHERE 1 > 0 
GROUP BY FMPR,SUPER_FAMILIA
ORDER BY FMPR,SUPER_FAMILIA

SELECT KOSU,
       FMPR,SUPER_FAMILIA,SUM(STFI) AS STFI,
       ROUND(SUM(PORC_STFI),3) AS PORC_STFI,
       SUM(VALSTOCK) AS VALSTOCK,
       ROUND(SUM(PORC_VALSTOCK),3) AS PORC_VALSTOCK 
FROM #STOCKVAL_FM
WHERE 1 > 0 
GROUP BY KOSU,FMPR,SUPER_FAMILIA
ORDER BY KOSU,FMPR,SUPER_FAMILIA

DROP TABLE #STOCKVAL_FM