Declare @Idmaedpce as int = #Idmaedpce#


SELECT TOP 1 
       Mc.*,convert(nvarchar, convert(datetime, (HORAGRAB*1.0/3600)/24), 108) AS 'HORA_GRAB',
       (Select NOKOCJ From TABCJ Cj Where Cj.EMPRESA = Mc.EMPRESA And Cj.KOSU = Mc.SUREDP And Cj.KOCJ = Mc.CJREDP) AS CAJA,
       (Select NOKOSU From TABSU Su Where Su.EMPRESA = Mc.EMPRESA And Su.KOSU = Mc.SUREDP) AS SUCURSAL,
       Tdp.NOKOENDP,Tdp.CTACTE,
       -- MAEEN
       Een.IDMAEEN, Een.KOEN, Een.TIEN, Een.RTEN, Een.SUEN, Een.TIPOSUC, Een.NOKOEN, Een.SIEN, Een.GIEN, Een.PAEN, Een.CIEN, Een.CMEN, Een.DIEN, Een.ZOEN, Een.FOEN, Een.FAEN, 
       Een.CNEN, Een.KOFUEN, Een.LCEN, Een.LVEN, Een.CRSD, Een.CRCH, Een.CRLT, Een.CRPA, Een.CRTO, Een.CREN, Een.FEVECREN, Een.FEULTR, Een.NUVECR, Een.DCCR, Een.INCR, Een.POPICR, 
       Een.KOPLCR, Een.CONTAB, Een.SUBAUXI, Een.CONTABVTA, Een.SUBAUXIVTA, Een.CODCC, Een.NUTRANSMI AS Expr1, Een.RUEN, Een.CPEN, Een.OBEN, Een.DIPRVE, Een.EMAIL, Een.CNEN2, 
       Een.COBRADOR, Een.PROTEACUM, Een.PROTEVIGE, Een.CPOSTAL, Een.HABILITA, Een.CODCONVE, Een.NOTRAEDEUD, Een.NOKOENAMP, Een.BLOQUEADO, Een.DIMOPER, Een.PREFEN, 
       Een.BLOQENCOM, Een.TIPOEN, Een.ACTIEN, Een.TAMAEN, Een.PORPREFEN, Een.CLAVEEN, Een.NVVPIDEPIE, Een.RECEPELECT, Een.ACTECO, Een.DIASVENCI, Een.CATTRIB, Een.AGRETIVA, 
       Een.AGRETIIBB, Een.AGRETGAN, Een.AGPERIVA, Een.AGPERIIBB, Een.TRANSPOEN, Een.FECREEN, Een.FIRMA, Een.MOCTAEN, Een.CTASDELAEN, Een.NACIONEN, Een.DIRPAREN, Een.FECNACEN,
       Een.ESTCIVEN, Een.PROFECEN, Een.CONYUGEN, Een.RUTCONEN, Een.RUTSOCEN, Een.SEXOEN, Een.RELACIEN, Een.ANEXEN1, Een.ANEXEN2, Een.ANEXEN3, Een.ANEXEN4, Een.OCCOBLI, 
       Een.VALIVENPAG, Een.EMAILCOMER, Een.TIPOCONTR, Een.FEREFAUTO, Een.DIACOBRA, Een.CUENTABCO, Een.KOENDPEN, Een.SUENDPEN, Een.RUTALUN, Een.RUTAMAR, Een.RUTAMIE, 
       Een.RUTAJUE, Een.RUTAVIE, Een.RUTASAB, Een.RUTADOM, Een.CATLEGRET, Een.IMPTORET, Een.ENTILIGA, Een.PORCELIGA, Een.ACTECOBCO,
       CAST('' As Varchar(20))  As 'Bk_Rut', 
       CAST('' As Varchar(200)) As 'Bk_Chc_Escrito_1_Bruto',
       CAST('' As Varchar(200)) As 'Bk_Chc_Escrito_2_Bruto'
       
Into #Paso_Encabezado       
FROM   dbo.MAEDPCE Mc LEFT OUTER JOIN
       dbo.TABENDP Tdp ON Mc.EMDP = Tdp.KOENDP AND Mc.EMPRESA = Tdp.EMPRESA LEFT OUTER JOIN
                      dbo.MAEEN Een ON Mc.ENDP = Een.KOEN
                      --dbo.MAEEN Een ON Mc.ENDP = Een.KOEN
WHERE IDMAEDPCE = @Idmaedpce  

-- Funciones especiales de BakApp
	
SELECT CAST( 1 AS Bit) AS Chk,MAEDPCD.*,MAEEDO.IDMAEEDO,
       MAEEDO.EMPRESA,MAEEDO.TIDO,MAEEDO.NUDO,MAEEDO.ENDO,MAEEDO.SUENDO,MAEEDO.FEEMDO,MAEEDO.FEULVEDO AS FEVE,
       MAEDPCD.VAASDP AS VAVE,MAEDPCD.VAASDP AS SALDO,
       Isnull((Select top 1 NOKOEN From MAEEN Where KOEN = MAEEDO.ENDO And SUEN = MAEEDO.SUENDO),'') As RAZON 
Into #Paso_Detalle        
FROM MAEDPCD LEFT OUTER JOIN MAEEDO ON MAEEDO.IDMAEEDO=MAEDPCD.IDRST AND MAEDPCD.ARCHIRST ='MAEEDO' 
WHERE  MAEDPCD.IDMAEDPCE = @Idmaedpce 
ORDER BY IDMAEDPCD  OPTION ( FAST 20 ) 	
	
Select * From #Paso_Encabezado
Select * From #Paso_Detalle

Drop Table #Paso_Encabezado
Drop Table #Paso_Detalle

--SELECT TOP 10 * FROM MAEEDO WHERE TIDO = 'BLV' ORDER BY FEEMDO DESC 