Declare @Koen Char(13),
        @Fecha Datetime,
        @Empresa Char(2)


Select @Koen = '#Koen#',@Fecha = '#Fecha#',@Empresa = '#Empresa#'

SELECT TOP 1 * FROM MAEEN WITH ( NOLOCK )  WHERE KOEN=@Koen

--1
SELECT KOMO,VAMO,NOKOMO  FROM MAEMO WIHT (NOLOCK)  WHERE FEMO = @Fecha ORDER BY IDMAEMO 

--2
SELECT TOP 1 PAGAFEVEN FROM CONFIGP WITH ( NOLOCK )  WHERE EMPRESA = @Empresa  

--3
SELECT EDO.IDMAEEDO,EDO.EMPRESA, EDO.TIDO, EDO.NUDO, EDO.ENDO, EDO.SUENDO, EDO.MODO, EDO.TIMODO, EDO.TAMODO, EDO.ESPGDO, EDO.FEULVEDO, 
       ROUND(EDO.VABRDO,2) AS VABRDO, 
       ROUND(EDO.VAABDO,2) AS VAABDO,
       ROUND(EDO.VAIVARET,2) AS VAIVARET, 
       ROUND(EDO.VAIVDO,2) AS VAIVDO, 
       ROUND(EDO.VANEDO,2) AS VANEDO,EDO.BLOQUEAPAG  
       FROM MAEEDO AS EDO  WITH ( NOLOCK )  
       WHERE 
		EDO.ENDO=@Koen AND 
		EDO.TIDO IN  ('BLV','BSV','BLX','FCV','FDB','FDV','FDX','FDZ','FEV','FVL','FVT','FVX','FVZ','RIN','ESC','FEE','NCC','NCB') AND 
		EDO.ESPGDO = 'P'  AND 
		EDO.NUDONODEFI = 0  AND 
		EDO.EMPRESA = @Empresa  
		ORDER BY EDO.TIDO,EDO.NUDO 

--4
SELECT SUM(ROUND(VEN.VAVE,2)-ROUND(VEN.VAABVE,2)) AS SALDOVEN  
FROM MAEEDO AS EDO  WITH ( NOLOCK )  
	INNER JOIN MAEVEN AS VEN ON VEN.IDMAEEDO=EDO.IDMAEEDO  AND 
		VEN.FEVE<=@Fecha AND 
		VEN.ESPGVE=' '  
	WHERE 
		EDO.ENDO=@Koen  AND 
		EDO.TIDO IN ('BLV','BSV','BLX','FCV','FDB','FDV','FDX','FDZ','FEV','FVL','FVT','FVX','FVZ','RIN','ESC','FEE','NCC','NCB') AND 
		EDO.EMPRESA = @Empresa  AND 
		EDO.ESPGDO = 'P' AND 
		EDO.NUDONODEFI = 0 

--5
SELECT SUM( 
			CASE  
				WHEN UDTRPR=1 AND 
				     PRCT=0 AND 
				     CAPRCO1<>0 AND 
				     CAPRCO1-CAPRAD1-CAPREX1>0 THEN (VABRLI*(CAPRCO1-CAPRAD1-CAPREX1))/CAPRCO1  
				WHEN UDTRPR=1 AND PRCT=0 AND CAPRCO1=0  THEN 0  
				WHEN UDTRPR=1 AND PRCT=1 AND TICT='D' AND CAPRCO1-CAPRAD1-CAPREX1>0 THEN (CAPRCO1-CAPRAD1-CAPREX1)*(-1.0)  
				WHEN UDTRPR=1 AND PRCT=1 AND TICT='R' AND CAPRCO1-CAPRAD1-CAPREX1>0 THEN (CAPRCO1-CAPRAD1-CAPREX1)  
				WHEN UDTRPR=2 AND PRCT=0 AND CAPRCO2<>0 AND CAPRCO2-CAPRAD2-CAPREX2>0 THEN (VABRLI*(CAPRCO2-CAPRAD2-CAPREX2))/CAPRCO2  
				WHEN UDTRPR=2 AND PRCT=0 AND CAPRCO2=0  THEN 0  
				WHEN UDTRPR=2 AND PRCT=1 AND TICT='D' AND CAPRCO2-CAPRAD2-CAPREX2>0 THEN (CAPRCO2-CAPRAD2-CAPREX2)*(-1.0)  
				WHEN UDTRPR=2 AND PRCT=1 AND TICT='R' AND CAPRCO2-CAPRAD2-CAPREX2>0 THEN (CAPRCO2-CAPRAD2-CAPREX2)  
				ELSE 0 
			END * 
			CASE 
				WHEN TIDO='GRD' THEN -1 
				ELSE 1 
			END) AS GUIACTE  
FROM MAEEDO WITH ( NOLOCK )  INNER JOIN (
								SELECT IDMAEEDO,UDTRPR,PRCT,TICT,CAPRCO1,CAPRAD1,CAPREX1,CAPRCO2,CAPRAD2,CAPREX2,VABRLI  
									FROM MAEDDO WITH ( NOLOCK )  
									WHERE ENDO=@Koen  AND 
										TIDO IN ('GDV','GRD')  AND 
										ESLIDO=' '  AND 
										LILG IN ('SI','GR') ) AS MAEDDO ON MAEEDO.IDMAEEDO=MAEDDO.IDMAEEDO  
WHERE 
	MAEEDO.ENDO = @Koen  AND 
	MAEEDO.TIDO IN ('GDV','GRD')  AND 
	EMPRESA = @Empresa   

--6
SELECT TOP 1 NVVAFECRE FROM CONFIGP WITH ( NOLOCK )  WHERE EMPRESA = @Empresa  

--7
SELECT EDO.IDDOCCOE,EDO.EMPRESA,EDO.TIDO, EDO.NUDO, EDO.ENDO, EDO.SUENDO, EDO.MODO, EDO.TIMODO, EDO.TAMODO, EDO.ESPGDO, 
		ROUND(EDO.VABRDO,2) AS VABRDO, ROUND(EDO.VAABDO,2) AS VAABDO, EDO.FEVEDO  
FROM CDOCCOE AS EDO  WITH ( NOLOCK )  INNER JOIN CFORMCON ON CFORMCON.KOFORMU=EDO.TIDO AND CFORMCON.VAABDO > 0 AND CFORMCON.ARCHIENDO='MAEEN   '  
WHERE 
	EDO.ENDO=@Koen AND 
	EDO.ESPGDO = 'P'  AND 
	EDO.SIMILSISTE ='V'  AND 
	EDO.EMPRESA = @Empresa 

--8
SELECT Cast(0 As Int) As ID,Cast(0 As Bit) As Nueva_Linea,DPCE.IDMAEDPCE,DPCE.EMPRESA,DPCE.TIDP, DPCE.NUDP, DPCE.ENDP, DPCE.EMDP, DPCE.SUEMDP, DPCE.CUDP,DPCE.NUCUDP, DPCE.FEEMDP, DPCE.FEVEDP, DPCE.MODP, 
       DPCE.TIMODP, DPCE.TAMODP,
       DPCE.VADP, 
       Cast(0 As Float) As VADP2, 
       DPCE.VAABDP, 
       DPCE.VAASDP As VAASDP_ORI,
       DPCE.VAASDP,
       (DPCE.VADP - DPCE.VAASDP) As SALDO, 
       DPCE.VAVUDP, 
       DPCE.ESASDP,
       DPCE.ESPGDP,
       DPCE.SUREDP,
       DPCE.CJREDP,
       DPCE.KOFUDP,
       DPCE.KOTNDP,
       DPCE.SUTNDP,
       DPCE.NUTRANSMI,
       DPCE.NUCOCO,
       DPCE.KOTU,
       DPCE.REFANTI,
       DPCE.DOCUENANTI,
       DPCE.IMDP,
       DPCE.NULICO,
       DPCE.PERIODO,
       DPCE.CUOTAS,
       DPCE.ARCHIRSD,
       DPCE.IDRSD,
       Cast(0 As Float) As Asig_TJV,
       Cast(0 As Bit) As Usar,
       Cast(0 As Float) As LEY20956,
       Cast('' As Varchar(500)) As Estatus

       FROM MAEDPCE AS DPCE  WITH ( NOLOCK )  
       WHERE 
		DPCE.ENDP = @Koen AND 
		DPCE.TIDP IN  ('ATB','CHV','CPV','CRV','DEP','EFV','LTV','PAV','RBV','RGV','RIV','TJV','VUE')  AND 
		DPCE.ESASDP = 'P'  AND 
		DPCE.ESPGDP<> 'N'  AND 
		DPCE.EMPRESA = @Empresa 

--9
SELECT DPCE.IDMAEDPCE,DPCE.EMPRESA,DPCE.TIDP, DPCE.NUDP, DPCE.ENDP, DPCE.EMDP, DPCE.SUEMDP, DPCE.CUDP,       
       DPCE.NUCUDP, DPCE.FEEMDP, DPCE.FEVEDP, DPCE.MODP, DPCE.TIMODP, DPCE.TAMODP,       
	   DPCE.VADP, DPCE.VAABDP, DPCE.VAASDP, DPCE.VAVUDP, DPCE.ESPGDP, DPCE.REFANTI  
FROM MAEDPCE AS DPCE  WITH ( NOLOCK )  
WHERE 
	DPCE.ENDP = @Koen  AND 
	DPCE.TIDP IN  ('ATB','CHV','CPV','CRV','DEP','EFV','LTV','PAV','RBV','RGV','RIV','TJV','VUE')  AND 
	( DPCE.ESPGDP = 'P' OR DPCE.ESPGDP = 'R' )  AND 
	DPCE.EMPRESA = @Empresa 
	

--10
SELECT CAST(0 AS INT) AS ID,CAST(0 AS INT) AS ID_PADRE,CAST(0 AS INT) AS ID_PAGO,
       CAST(0 AS INT) AS IDMAEDPCE,
       EDO.IDMAEEDO AS IDRST,
       'MAEEDO' AS ARCHIRST,
       EDO.TAMODO AS TCASIG,
       EDO.EMPRESA, 
       EDO.TIDO AS DP, 
       EDO.NUDO AS NUDP, 
       EDO.ENDO AS ENDP, 
      -- EDO.SUENDO, 
       '' AS EMDP,'' AS SUEMDP,'' AS CUDP,'' AS NUCUDP,EDO.FEEMDO AS FEEMDP,EDO.FEULVEDO AS FEVEDP,EDO.MODO AS MODP, 
       EDO.TIMODO AS TIMODP, EDO.TAMODO AS TAMODP, 
       ROUND(EDO.VABRDO,2) AS VADP, 
       ROUND(EDO.VAABDO,2) AS VAABDP,
       ROUND(EDO.VABRDO,2) -  ROUND(EDO.VAABDO,2) as SALDO,
       CAST(0 AS FLOAT) AS ABONO,
       CAST(0 AS FLOAT) AS ABONO2,
       ROUND(EDO.VABRDO,2) -  ROUND(EDO.VAABDO,2) as SALDO_ACT,
       0 As Orden,
       Cast('' As Varchar(30)) As Fevedp_Str,	    
       Cast('' As Varchar(30)) As Modp_Str,	    
       Cast('' As Varchar(30)) As Vadp_Str,	    
       Cast('' As Varchar(30)) As Saldo_Str,	    
       Cast('' As Varchar(30)) As Saldo_Act_Str,
       Cast(0 As Float) As LEY20956
	   	        
       FROM MAEEDO AS EDO  WITH ( NOLOCK )  
       WHERE 
		EDO.ENDO=@Koen AND 
		EDO.TIDO IN  ('BLV','BSV','BLX','FCV','FDB','FDV','FDX','FDZ','FEV','FVL','FVT','FVX','FVZ',
		              'RIN','ESC','FEE','NCC','NCB') AND 
		EDO.ESPGDO = 'P'  AND 
		EDO.NUDONODEFI = 0  AND 
		EDO.EMPRESA = @Empresa
Union
SELECT CAST(0 AS INT) AS ID,CAST(0 AS INT) AS ID_PADRE,CAST(0 AS INT) AS ID_PAGO,
       CAST(0 AS INT) AS IDMAEDPCE,
       DPCE.IDMAEDPCE AS IDRST,
       'MAEDPCE' AS ARCHIRST,
       DPCE.TAMODP AS TCASIG,
       DPCE.EMPRESA,DPCE.TIDP AS DP, DPCE.NUDP, DPCE.ENDP, DPCE.EMDP, DPCE.SUEMDP, DPCE.CUDP,       
       DPCE.NUCUDP, DPCE.FEEMDP, DPCE.FEVEDP, DPCE.MODP, DPCE.TIMODP, DPCE.TAMODP,       
	   DPCE.VADP, 
	   DPCE.VAABDP,
	   (DPCE.VADP - DPCE.VAABDP) AS SALDO,--, DPCE.VAASDP--, DPCE.VAVUDP, DPCE.ESPGDP, DPCE.REFANTI 
	   CAST(0 AS FLOAT) AS ABONO,
       CAST(0 AS FLOAT) AS ABONO2,
	   (DPCE.VADP - DPCE.VAABDP) AS SALDO_ACT,       
       1 As Orden,
       Cast('' As Varchar(30)) As Fevedp_Str,	    
       Cast('' As Varchar(30)) As Modp_Str,	    
       Cast('' As Varchar(30)) As Vadp_Str,	    
       Cast('' As Varchar(30)) As Saldo_Str,	    
       Cast('' As Varchar(30)) As Saldo_Act_Str,
       Cast(0 As Float) As LEY20956

FROM MAEDPCE AS DPCE  WITH ( NOLOCK )  
WHERE 
	DPCE.ENDP = @Koen  AND 
		--DPCE.TIDP IN  ('ATB','CHV','CPV','CRV','DEP','EFV','LTV','PAV','RBV','RGV','RIV','TJV','VUE')  AND 
	      DPCE.TIDP IN  ('ATB','CHV','CPV','DEP','LTV','PAV','RBV','RGV','RIV','VUE')  AND 
	( DPCE.ESPGDP = 'P' OR DPCE.ESPGDP = 'R' )  AND 
	DPCE.EMPRESA = @Empresa 	
	
ORDER BY Orden,FEVEDP
	
