Declare @Idmaedpce Int 

Select @Idmaedpce = #Idmaedpce#

SELECT MAEDPCE.* FROM MAEDPCE WITH ( NOLOCK ) 
WHERE  MAEDPCE.IDMAEDPCE = @Idmaedpce 
ORDER BY MAEDPCE.EMPRESA ,MAEDPCE.TIDP  OPTION ( FAST 20 ) 

--SELECT CAST( 1 AS Bit) AS Chk,MAEDPCD.*,MAEEDO.IDMAEEDO,
--       MAEEDO.EMPRESA,MAEEDO.TIDO,MAEEDO.NUDO,MAEEDO.ENDO,MAEEDO.SUENDO,MAEEDO.FEEMDO,MAEEDO.FEULVEDO AS FEVE,
--       MAEDPCD.VAASDP AS VAVE,MAEDPCD.VAASDP AS SALDO,
--       Isnull((Select top 1 NOKOEN From MAEEN Where KOEN = MAEEDO.ENDO And SUEN = MAEEDO.SUENDO),'') As RAZON 
--FROM MAEDPCD LEFT OUTER JOIN MAEEDO ON MAEEDO.IDMAEEDO=MAEDPCD.IDRST AND MAEDPCD.ARCHIRST ='MAEEDO' 
--WHERE  MAEDPCD.IDMAEDPCE = @Idmaedpce 
--ORDER BY IDMAEDPCD  OPTION ( FAST 20 ) 

Select CAST( 1 AS Bit) AS Chk,Detp.*,Detp.VAASDP As VAVE,Detp.VAASDP AS SALDO,
	   Case Detp.ARCHIRST When 'MAEEDO' Then Edo.IDMAEEDO When 'MAEDPCE' Then Dpce.IDMAEDPCE Else '' End As Id,
	   Case Detp.ARCHIRST When 'MAEEDO' Then Edo.EMPRESA When 'MAEDPCE' Then Dpce.EMPRESA Else '' End As Empresa,
	   Case Detp.ARCHIRST When 'MAEEDO' Then Edo.TIDO When 'MAEDPCE' Then Dpce.TIDP Else '' End As Td,
	   Case Detp.ARCHIRST When 'MAEEDO' Then Edo.NUDO When 'MAEDPCE' Then Dpce.NUDP Else '' End As Numero,
	   Case Detp.ARCHIRST When 'MAEEDO' Then Edo.ENDO When 'MAEDPCE' Then Dpce.ENDP Else '' End As Entidad,
	   Case Detp.ARCHIRST When 'MAEEDO'  Then Isnull((Select top 1 NOKOEN From MAEEN Where KOEN = Edo.ENDO And SUEN = Edo.SUENDO),'') 
						  When 'MAEDPCE' Then Isnull((Select top 1 NOKOEN From MAEEN Where KOEN = Dpce.ENDP),'') Else '' End As RazonSocial,
	   Case Detp.ARCHIRST When 'MAEEDO' Then Edo.IDMAEEDO When 'MAEDPCE' Then Dpce.IDMAEDPCE Else '' End As IDMAEEDO,
	   Case Detp.ARCHIRST When 'MAEEDO' Then Edo.TIDO When 'MAEDPCE' Then Dpce.TIDP Else '' End As TIDO,
	   Case Detp.ARCHIRST When 'MAEEDO' Then Edo.NUDO When 'MAEDPCE' Then Dpce.NUDP Else '' End As NUDO,
	   Case Detp.ARCHIRST When 'MAEEDO' Then Edo.ENDO When 'MAEDPCE' Then Dpce.ENDP Else '' End As ENDO,
	   Case Detp.ARCHIRST When 'MAEEDO' Then Edo.SUENDO When 'MAEDPCE' Then '' Else '' End As SUENDO,
	   Case Detp.ARCHIRST When 'MAEEDO' Then Edo.FEEMDO When 'MAEDPCE' Then Dpce.FEEMDP Else '' End As FEEMDO,
	   Case Detp.ARCHIRST When 'MAEEDO' Then Edo.FEULVEDO When 'MAEDPCE' Then Dpce.FEVEDP Else '' End As FEVE

FROM MAEDPCD Detp 
Inner Join MAEDPCE Enc On Enc.IDMAEDPCE = Detp.IDMAEDPCE
Left Join MAEEDO Edo ON Edo.IDMAEEDO=Detp.IDRST AND Detp.ARCHIRST ='MAEEDO' 
Left Join MAEDPCE Dpce ON Dpce.IDMAEDPCE=Detp.IDRST AND Detp.ARCHIRST ='MAEDPCE' 
Where Detp.IDMAEDPCE = @Idmaedpce And Enc.TIDP <> Detp.TIDOPA
Order By IDMAEDPCD 


SELECT CAST( 0 AS bit) AS Chk,* FROM MAEEN 
WHERE KOEN IN 
(SELECT DISTINCT MAEEDO.ENDO 
	FROM MAEDPCD LEFT OUTER JOIN MAEEDO ON MAEEDO.IDMAEEDO=MAEDPCD.IDRST AND MAEDPCD.ARCHIRST ='MAEEDO ' 
	WHERE MAEDPCD.IDMAEDPCE = @Idmaedpce)
