Declare @Idmaedpce As Int

Select @Idmaedpce = #Idmaedpce#

SELECT TOP 1 IDMAEDDO,MAEEDO.TIDO,MAEEDO.NUDO,MAEEDO.ENDO,FEEMDO FROM MAEDDO  WITH ( NOLOCK ) INNER JOIN MAEEDO ON MAEDDO.IDMAEEDO = MAEEDO.IDMAEEDO  WHERE MAEDDO.ARCHIRST='MAEDPCE' AND MAEDDO.IDRST=@Idmaedpce
SELECT TOP 1 IDMAEDPCD,TIDP,NUDP,ENDP,FEEMDP FROM MAEDPCD  WITH ( NOLOCK ) INNER JOIN MAEDPCE ON MAEDPCD.IDMAEDPCE = MAEDPCE.IDMAEDPCE  WHERE MAEDPCD.ARCHIRST='MAEDPCE' AND MAEDPCD.IDRST=@Idmaedpce
SELECT TOP 1 IDCOMPRD1,NUMECOM,FECHCOM FROM CCOMPRD1  WITH ( NOLOCK ) INNER JOIN CCOMPRD ON CCOMPRD1.IDCOMPRD = CCOMPRD.IDCOMPRD INNER JOIN CCOMPRE ON CCOMPRD.IDCOMPRE = CCOMPRE.IDCOMPRE  WHERE CCOMPRD1.ARCHIRST='MAEDPCE' AND CCOMPRD1.IDRST=@Idmaedpce
SELECT TOP 1 IDCARTOLD,NUCAR,CTACTECAR FROM CCARTOLD  WITH ( NOLOCK ) INNER JOIN CCARTOLE ON CCARTOLD.IDCARTOLE = CCARTOLE.IDCARTOLE  WHERE CCARTOLD.ARCHIRST='MAEDPCE' AND CCARTOLD.IDRST=@Idmaedpce
SELECT TOP 1 IDDOCCOD,TIDO,NUDO,ENDO,FEEMDO FROM CDOCCOD  WITH ( NOLOCK ) INNER JOIN CDOCCOE ON CDOCCOE.IDDOCCOE = CDOCCOD.IDDOCCOE  WHERE CDOCCOD.ARCHIRST='MAEDPCE' AND CDOCCOD.IDRST=@Idmaedpce
SELECT TOP 1 IDPOTLCOM,POTL.NUMOT,POTL.NREG,POTL.CODIGO,POTL.GLOSA FROM POTLCOM  WITH ( NOLOCK ) INNER JOIN POTL ON POTLCOM.IDPOTL = POTL.IDPOTL INNER JOIN POTE ON POTL.IDPOTE = POTE.IDPOTE  WHERE POTLCOM.ARCHIRST='MAEDPCE' AND POTLCOM.IDRST=@Idmaedpce
SELECT TOP 1 IDPDATFAD,PDATFAE.NUMDF,PDATFAE.FECHA FROM PDATFAD  WITH ( NOLOCK ) INNER JOIN PDATFAE ON PDATFAD.IDPDATFAE = PDATFAE.IDPDATFAE  WHERE PDATFAD.ARCHIRST='MAEDPCE' AND PDATFAD.IDRST=@Idmaedpce
SELECT TOP 1 IDPDATTAD,PDATTAE.NUMDF,PDATTAE.FECHA FROM PDATTAD  WITH ( NOLOCK ) INNER JOIN PDATTAE ON PDATTAD.IDPDATTAE = PDATTAE.IDPDATTAE  WHERE PDATTAD.ARCHIRST='MAEDPCE' AND PDATTAD.IDRST=@Idmaedpce
SELECT TOP 1 * FROM PTICKET WITH ( NOLOCK )  WHERE ARCHIRST='MAEDPCE' AND IDRST=@Idmaedpce
SELECT TOP 1 * FROM PODCD WITH ( NOLOCK )  WHERE ARCHIRST='MAEDPCE' AND IDRST=@Idmaedpce
SELECT TOP 1 * FROM MAEDPCE WITH ( NOLOCK )  WHERE IDMAEDPCE=@Idmaedpce
SELECT * FROM MAEDPCD WITH ( NOLOCK )  WHERE IDMAEDPCE=@Idmaedpce

SELECT MAEDPCD.TIDOPA,MAEDPCD.ARCHIRST,MAEDPCD.IDRST,MAEDPCD.VAASDP,MAEEDO.IDMAEEDO, MAEEDO.TIDO,MAEEDO.NUDO,MAEEDO.ENDO,MAEEDO.TIMODO,MAEEDO.TAMODO,MAEEDO.VAABDO,CDOCCOE.IDDOCCOE, 
CDOCCOE.TIDO AS TIDOF,CDOCCOE.TIMODO AS TIMODOF,CDOCCOE.VAABDO AS VAABDOF,MAEDPCE.IDMAEDPCE, MAEDPCE.TIDP,MAEDPCE.TIMODP,MAEDPCE.TAMODP,MAEDPCE.TIDP,MAEDPCE.NUDP,
MAEDPCE.ENDP,MAEDPCE.VAVUDP,MAEDPCE.VADP,MAEDPCE.VAABDP,MAEDPCE.FEEMDP,MAEDPCD.REFERENCIA  
FROM MAEDPCE WITH ( NOLOCK )  
	LEFT JOIN MAEDPCD ON MAEDPCD.IDMAEDPCE=MAEDPCE.IDMAEDPCE  
		LEFT JOIN MAEEDO ON MAEDPCD.TIDOPA=MAEEDO.TIDO AND MAEDPCD.IDRST=MAEEDO.IDMAEEDO AND MAEDPCD.ARCHIRST='MAEEDO  '  
			LEFT JOIN CDOCCOE ON MAEDPCD.TIDOPA=CDOCCOE.TIDO AND MAEDPCD.IDRST=CDOCCOE.IDDOCCOE AND MAEDPCD.ARCHIRST='CDOCCOE '  WHERE MAEDPCE.IDMAEDPCE=@Idmaedpce