'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.8009
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class _Rec_Alertas
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Funciones_BakApp._Rec_Alertas", GetType(_Rec_Alertas).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DECLARE 
        '''
        '''@Empresa   Char(2),
        '''@Sucursal  Char(3),
        '''@Bodega    Char(3),
        '''@Codigo    Char(13),
        '''@Orden     Int,
        '''@StockUd1  Float,
        '''@StockUd2  Float,
        '''@Fecha  Date  
        '''
        '''Select @Empresa  = &apos;#Empresa#&apos;,
        '''       @Sucursal = &apos;#Sucursal#&apos;,
        '''       @Bodega   = &apos;#Bodega#&apos;, 
        '''	   @Codigo   = &apos;#@Codigo#&apos;,
        '''	   @Fecha    = &apos;#Fecha#&apos;
        '''
        '''SELECT D.KOPRCT,D.EMPRESA,D.TIDO,E.SUBTIDO,D.SULIDO,D.BOSULIDO,
        '''            
        '''       CASE 
        '''             WHEN D.TIDO IN (&apos;BLV&apos;,&apos;FCV&apos;) AND D.TIDOPA IN (&apos;&apos;,&apos;NVV&apos;) AND D.CAPREX1 &gt; 0 THE [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Stock_productos_por_emp_suc_bod() As String
            Get
                Return ResourceManager.GetString("Stock_productos_por_emp_suc_bod", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
