'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Recursos_Inf
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BkSpecialPrograms.Recursos_Inf", GetType(Recursos_Inf).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a -- COMPORTAMIENTO DE PAGO
        '''
        '''SELECT  Edo.IDMAEEDO, 
        '''        Edo.TIDO AS TIPO_DOC, 
        '''        Edo.NUDO AS NO_DOC, 
        '''        Edo.ESPGDO AS ESTADO_PAGO,
        '''        Edo.ENDO AS CODIGO, 
        '''        Me.NOKOEN AS CLIENTE, 
        '''        Edo.FEEMDO AS EMISION, 
        '''        Edo.FEULVEDO AS FECHA_VCMTO, 
        '''        DATEDIFF(d,Edo.FEEMDO,Edo.FEULVEDO) as DIAS_VCTO,
        '''        CASE 
        '''		    WHEN Edo.TIDO = &apos;NCV&apos; THEN Edo.VABRDO * - 1 
        '''		    ELSE Edo.VABRDO * 1 
        '''		END AS VALOR_DOCTO, 
        '''        CASE 
        '''            WHEN Edo.TIDO = &apos;NCV&apos;  [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SQLQuery_Informe_de_comportamiento_de_pagos() As String
            Get
                Return ResourceManager.GetString("SQLQuery_Informe_de_comportamiento_de_pagos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a -- CONSULTA SQL PARA INFORME SEA GARDEN 
        '''-- INFORME INFORME DE ESTADO DE CRÉDITOS VIGENTES ON LINE
        '''-- CARTERA
        '''
        '''-- CARTERA
        '''/*
        '''SELECT     TOP (100) PERCENT dbo.MAEDPCE.TIDP AS TIPO_DOC, dbo.MAEDPCE.EMDP AS BANCO, dbo.MAEDPCE.ENDP AS CODIGO, dbo.MAEEN.NOKOEN AS CLIENTE, dbo.MAEDPCE.FEVEDP, 
        '''                      dbo.MAEDPCE.VADP AS MONTO, dbo.MAEDPCE.CUDP AS CUENTA, dbo.MAEDPCE.NUCUDP AS N_DOC
        '''FROM         dbo.MAEDPCE INNER JOIN
        '''                      dbo.MAEEN ON dbo.MAEDPCE.ENDP = dbo.MAEEN.KOEN
        '''WHE [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SQLQuery_Informe_de_estado_de_creditos_vigentes_on_line() As String
            Get
                Return ResourceManager.GetString("SQLQuery_Informe_de_estado_de_creditos_vigentes_on_line", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
